// packages/react/src/text-field/TextField.tsx
import { useRef, type InputHTMLAttributes, type ReactNode } from "react";
import { Icon } from "../icon/Icon";
import { useTextField } from "./use-text-field";

type InputType = "text" | "search" | "email" | "password" | "tel" | "url" | "number";

export interface TextFieldProps {
  /** Visible label and accessible name for the control. */
  label: string;
  /** Visually hide the label while keeping it as the control's accessible name. */
  hideLabel?: boolean;
  /** Initial or current value. */
  value?: string;
  /** Native input type. */
  type?: InputType;
  /** Native placeholder. It does not replace the label. */
  placeholder?: string;
  /** Hint linked to the control through `aria-describedby`. */
  description?: string;
  /** Error message that marks the control invalid and is announced. */
  error?: string;
  /** Confirmation message announced politely when the field is valid. */
  success?: string;
  /** Prevent interaction and form submission. */
  disabled?: boolean;
  /** Mark the native input as required. */
  required?: boolean;
  /** Keep the input focusable and submittable but prevent edits. */
  readOnly?: boolean;
  /** Native form field name. */
  name?: string;
  /** Native maximum length constraint. */
  maxLength?: number;
  /** Native minimum length constraint. */
  minLength?: number;
  /** Native validation pattern. */
  pattern?: string;
  /** Preferred virtual keyboard mode. */
  inputMode?: InputHTMLAttributes<HTMLInputElement>["inputMode"];
  /** Native autofill hint. */
  autoComplete?: InputHTMLAttributes<HTMLInputElement>["autoComplete"];
  /** Enable or disable browser spelling correction. */
  spellCheck?: boolean;
  /** Called once after a user edit is committed locally. */
  onValueChange?: (value: string) => void;
  /** Decorative content placed inside the control at the inline start. */
  left?: ReactNode;
  /** Decorative content placed inside the control at the inline end. */
  right?: ReactNode;
}

/** A native single-line input with shared field semantics and styling. */
export function TextField({
  label,
  hideLabel = false,
  value = "",
  type = "text",
  placeholder,
  description,
  error,
  success,
  disabled = false,
  required = false,
  readOnly = false,
  name,
  maxLength,
  minLength,
  pattern,
  inputMode,
  autoComplete,
  spellCheck,
  onValueChange,
  left,
  right,
}: TextFieldProps) {
  const controlRef = useRef<HTMLInputElement>(null);
  const api = useTextField({
    value,
    disabled,
    required,
    readOnly,
    invalid: Boolean(error),
    hasDescription: Boolean(description),
    hasSuccess: Boolean(success),
    onValueChange,
    controlRef,
  });
  const showSuccessIcon = Boolean(success) && !error && !right;

  return (
    <div
      className={[
        "text-field",
        error ? "text-field--invalid" : "",
        success && !error ? "text-field--success" : "",
        disabled ? "text-field--disabled" : "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      <label
        {...api.labelProps}
        className={hideLabel ? "field__label field__label--hidden" : "field__label"}
      >
        {label}
        {required && (
          <span className="field__required" aria-hidden="true">
            {" *"}
          </span>
        )}
      </label>

      <div className="field__input">
        {left && (
          <span className="field__icon field__icon--left" aria-hidden="true">
            {left}
          </span>
        )}
        <input
          {...api.controlProps}
          ref={controlRef}
          className={[
            "field__control",
            left ? "field__control--icon-left" : "",
            right || showSuccessIcon ? "field__control--icon-right" : "",
          ]
            .filter(Boolean)
            .join(" ")}
          type={type}
          name={name}
          placeholder={placeholder}
          maxLength={maxLength}
          minLength={minLength}
          pattern={pattern}
          inputMode={inputMode}
          autoComplete={autoComplete}
          spellCheck={spellCheck}
          value={api.value}
          onChange={(event) => api.setValue(event.currentTarget.value)}
        />
        {right ? (
          <span className="field__icon field__icon--right" aria-hidden="true">
            {right}
          </span>
        ) : showSuccessIcon ? (
          <span className="field__icon field__icon--right field__icon--success" aria-hidden="true">
            <Icon>
              <polyline points="20 6 9 17 4 12" />
            </Icon>
          </span>
        ) : null}
      </div>

      {description && (
        <p className="field__description" {...api.descriptionProps}>
          {description}
        </p>
      )}
      {error ? (
        <p className="field__error" {...api.errorProps}>
          <span className="field__msg-icon" aria-hidden="true">
            <Icon size="1em">
              <path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
              <line x1="12" y1="9" x2="12" y2="13" />
              <line x1="12" y1="17" x2="12" y2="17" />
            </Icon>
          </span>
          {error}
        </p>
      ) : success ? (
        <p className="field__success" {...api.successProps}>
          <span className="field__msg-icon" aria-hidden="true">
            <Icon size="1em">
              <polyline points="20 6 9 17 4 12" />
            </Icon>
          </span>
          {success}
        </p>
      ) : null}
    </div>
  );
}

// packages/svelte/src/lib/text-field/TextField.svelte
<script lang="ts">
  /**
   * TextField — the styled, batteries-included single-line text field. Behaviour
   * and accessibility (label association, `aria-describedby` for the hint,
   * error and success text, `aria-invalid` / `aria-required`) come from the
   * headless text field
   * (`@design-system/core`); this layer adds the label, control, optional
   * description and error message, and the focus / invalid styling.
   *
   * Covers the common single-line `type`s (text, search, email, password, tel,
   * url, number). Passing a non-empty `error` puts the field in the invalid
   * state and announces the message. Colors and sizing are themeable CSS custom
   * properties (`--ds-field-*`).
   */
  import type { HTMLInputAttributes } from "svelte/elements";
  import { textField as core } from "@design-system/core";
  import { createTextField } from "./create-text-field";
  import Icon from "../icon/Icon.svelte";

  type InputType = "text" | "search" | "email" | "password" | "tel" | "url" | "number";
  type InputMode = "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";

  /** Visible label, tied to the control. */
  export let label: string;
  export let value = "";
  export let type: InputType = "text";
  export let placeholder: string | undefined = undefined;
  /** Optional hint shown under the control and linked via aria-describedby. */
  export let description: string | undefined = undefined;
  /** Error message; when non-empty the field becomes invalid and announces it. */
  export let error: string | undefined = undefined;
  /** Success/validated message; shows a green check and a confirming caption. */
  export let success: string | undefined = undefined;
  export let disabled = false;
  export let required = false;
  export let readOnly = false;
  /** Form field name — the value is submitted under it. */
  export let name: string | undefined = undefined;
  /** Native length limits; the browser enforces them and reports them. */
  export let maxlength: number | undefined = undefined;
  export let minlength: number | undefined = undefined;
  /** Native format constraint (paired with `title` for the browser's message). */
  export let pattern: string | undefined = undefined;
  /** Keyboard hint on touch devices. */
  export let inputmode: InputMode | undefined = undefined;
  /** Autofill hint, e.g. `"email"` or `"one-time-code"`. */
  export let autocomplete: HTMLInputAttributes["autocomplete"] = undefined;
  /** Turn spelling correction off for codes and identifiers. */
  export let spellcheck: boolean | undefined = undefined;
  /** Called whenever the value changes. */
  export let onValueChange: ((value: string) => void) | undefined = undefined;

  const field = createTextField({
    value,
    disabled,
    required,
    readOnly,
    invalid: !!error,
    hasDescription: !!description,
    hasSuccess: !!success,
    onValueChange,
  });
  const {
    state: fieldState,
    labelAction,
    controlAction,
    descriptionAction,
    errorAction,
    successAction,
    setValue,
  } = field;

  // Keep the headless state in sync with reactive props so the wiring
  // (aria-invalid, aria-describedby, disabled…) stays correct.
  $: field.setFlags({
    disabled,
    required,
    readOnly,
    invalid: !!error,
    hasDescription: !!description,
    hasSuccess: !!success,
  });

  function onInput(event: Event) {
    value = (event.currentTarget as HTMLInputElement).value;
    setValue(value);
  }

  // A built-in green check (right) when validated, unless a custom right slot is used.
  $: showSuccessIcon = !!success && !error && !$$slots.right;
</script>

<div
  class="field"
  class:field--invalid={!!error}
  class:field--success={!!success && !error}
  class:field--disabled={disabled}
>
  <!-- The ids are declared here as well as applied by the actions, so the
       server-rendered markup already ties the label to its control: before
       hydration the field would otherwise be a control with no name. -->
  <label
    class="field__label"
    for={core.controlId($fieldState.id)}
    id={core.labelId($fieldState.id)}
    use:labelAction
  >
    {label}{#if required}<span class="field__required" aria-hidden="true"> *</span>{/if}
  </label>

  <div class="field__input">
    {#if $$slots.left}
      <span class="field__icon field__icon--left" aria-hidden="true"><slot name="left" /></span>
    {/if}
    <input
      class="field__control"
      class:field__control--icon-left={$$slots.left}
      class:field__control--icon-right={$$slots.right || showSuccessIcon}
      {type}
      {name}
      {placeholder}
      {value}
      {maxlength}
      {minlength}
      {pattern}
      {inputmode}
      {autocomplete}
      {spellcheck}
      id={core.controlId($fieldState.id)}
      on:input={onInput}
      use:controlAction
    />
    {#if $$slots.right}
      <span class="field__icon field__icon--right" aria-hidden="true"><slot name="right" /></span>
    {:else if showSuccessIcon}
      <span class="field__icon field__icon--right field__icon--success" aria-hidden="true">
        <Icon><polyline points="20 6 9 17 4 12" /></Icon>
      </span>
    {/if}
  </div>

  {#if description}
    <p class="field__description" id={core.descriptionId($fieldState.id)} use:descriptionAction>
      {description}
    </p>
  {/if}
  {#if error}
    <p class="field__error" id={core.errorId($fieldState.id)} use:errorAction>
      <span class="field__msg-icon" aria-hidden="true">
        <Icon size="1em">
          <path
            d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"
          />
          <line x1="12" y1="9" x2="12" y2="13" />
          <line x1="12" y1="17" x2="12" y2="17" />
        </Icon>
      </span>
      {error}
    </p>
  {:else if success}
    <p class="field__success" id={core.successId($fieldState.id)} use:successAction>
      <span class="field__msg-icon" aria-hidden="true">
        <Icon size="1em"><polyline points="20 6 9 17 4 12" /></Icon>
      </span>
      {success}
    </p>
  {/if}
</div>

<style>
  .field {
    display: grid;
    gap: var(--ds-field-gap, 0.375rem);
    inline-size: var(--ds-field-width, 18rem);
    font: inherit;
    color: var(--ds-color-text, #282420);
  }

  .field__label {
    font-size: 0.875rem;
    font-weight: 600;
  }
  /* A disabled control dims its label too, so the relationship reads clearly. */
  .field--disabled .field__label {
    color: var(--ds-color-text-disabled, #757067);
  }
  .field__required {
    color: var(--ds-color-danger-body-text, #be3b50);
  }

  /* Wraps the control so leading/trailing icons can overlay it. */
  .field__input {
    position: relative;
    display: flex;
    align-items: center;
  }
  .field__icon {
    position: absolute;
    display: inline-flex;
    align-items: center;
    color: var(--ds-color-text-secondary, #524c44);
    pointer-events: none;
  }
  .field__icon :global(svg) {
    inline-size: 1.15em;
    block-size: 1.15em;
  }
  .field__icon--left {
    inset-inline-start: 0.7rem;
  }
  .field__icon--right {
    inset-inline-end: 0.7rem;
  }
  /* Compound selectors so the icon padding beats the `.field__control` padding
     shorthand regardless of source order (otherwise text overlaps the icon). */
  .field__control.field__control--icon-left {
    padding-inline-start: 2.3rem;
  }
  .field__control.field__control--icon-right {
    padding-inline-end: 2.3rem;
  }

  .field__control {
    inline-size: 100%;
    box-sizing: border-box;
    padding: var(--ds-field-padding, 0.5rem 0.75rem);
    border: 1px solid var(--ds-color-control-border, #757067);
    border-radius: var(--ds-field-radius, var(--ds-radius-control, 0.5rem));
    background: var(--ds-color-background, #fff);
    color: inherit;
    font: inherit;
    transition:
      border-color 120ms ease,
      box-shadow 120ms ease;
  }
  .field__control::placeholder {
    color: var(--ds-color-text-secondary, #524c44);
  }
  .field__control:focus-visible {
    outline: none;
    border-color: var(--ds-color-focus-ring, #8e6cd4);
    box-shadow: var(--ds-focus-ring-shadow);
  }

  /* Invalid: a danger ring (same ring+halo gradation as focus, danger color)
     around the border, shown whenever the field is in error — not only on focus. */
  .field__control:global([data-invalid]) {
    border-color: var(--ds-color-danger, #be3b50);
    box-shadow:
      0 0 0 var(--ds-focus-ring-width, 2px) var(--ds-color-danger, #be3b50),
      0 0 0 calc(var(--ds-focus-ring-width, 2px) + var(--ds-focus-halo-width, 3px))
        color-mix(in srgb, var(--ds-color-danger, #be3b50) 30%, transparent);
  }

  .field__control:global([data-disabled]) {
    background: var(--ds-color-disabled, #c7c1b7);
    color: var(--ds-color-text-disabled, #757067);
    cursor: not-allowed;
  }

  /* Help and error text match the control's (placeholder) text size. */
  .field__description {
    margin: 0;
    color: var(--ds-color-text-secondary, #524c44);
  }
  .field__error,
  .field__success {
    margin: 0;
    display: flex;
    align-items: center;
    gap: 0.35rem;
  }
  .field__error {
    color: var(--ds-color-danger-body-text, #be3b50);
  }
  .field__success {
    color: var(--ds-color-success-body-text, #3e7523);
  }
  .field__msg-icon {
    display: inline-flex;
    flex: none;
  }
  /* Success/validated: green check inside the field + green border. */
  .field__icon--success {
    color: var(--ds-color-success, #3e7523);
  }
  .field--success .field__control {
    border-color: var(--ds-color-success, #3e7523);
  }
</style>
