// packages/svelte/src/lib/card/Card.svelte
<script lang="ts">
  /**
   * Card — a presentational content container. Three shapes from one component:
   *
   * - `variant="media"` + `orientation="vertical"` (default): the classic card —
   *   media on top, then tags, title, description, and a footer for actions.
   * - `variant="media"` + `orientation="horizontal"`: media on the left, the
   *   title with a tag beside it and the description below, actions on the right.
   * - `variant="dashboard"`: an icon over a title on the left, a large value with
   *   a smaller change/percentage beside it on the right (a metric tile).
   *
   * The media area is an image (`imageSrc`) or, when the `icon` snippet is provided,
   * an icon in its place. Tags and actions are snippets so you compose them with the
   * existing `Tag` and `ButtonGroup`/`Button` components (e.g. a ghost action on
   * the left and the primary action on the right).
   *
   * Accessibility: renders as an `<article>`; when a `title` string is given it
   * becomes a heading (level via `headingLevel`) and labels the card
   * (`aria-labelledby`). Colors/spacing are themeable (`--ds-card-*`).
   */
  import type { Snippet } from "svelte";
  import { stableId } from "../internal/stable-id";

  interface Props {
    variant?: "media" | "dashboard";
    orientation?: "vertical" | "horizontal";
    /** Surface hierarchy. `secondary` uses the quieter secondary card surface token. */
    surface?: "default" | "secondary";
    /** Image URL for the media area (ignored when the `icon` snippet is used). */
    imageSrc?: string;
    /** Alt text for the image. Defaults to empty (decorative). */
    imageAlt?: string;
    /**
     * Card title. A string is rendered as a heading and labels the card; a
     * snippet replaces the heading with your own markup.
     */
    title?: string | Snippet;
    /** Heading level for the title (2–6). Defaults to `3`. */
    headingLevel?: 2 | 3 | 4 | 5 | 6;
    /** Body description: plain text, or a snippet for rich content. */
    description?: string | Snippet;
    /** Dashboard: the large metric value. */
    value?: string | number;
    /** Dashboard: the smaller change/percentage shown beside the value. */
    change?: string;
    /** Dashboard: direction of the change, for coloring. */
    trend?: "up" | "down" | "neutral";
    /** Icon in the media area (media variant) or beside the title (dashboard). */
    icon?: Snippet;
    /** Custom media content, in place of the image or icon. */
    media?: Snippet;
    /** Tags shown with the title. */
    tags?: Snippet;
    /** Dashboard: extra content after the value and change. */
    metric?: Snippet;
    /** Actions area at the end of the card. */
    actions?: Snippet;
    /** Extra body content below the description. */
    children?: Snippet;
  }

  let {
    variant = "media",
    orientation = "vertical",
    surface = "default",
    imageSrc,
    imageAlt = "",
    title,
    headingLevel = 3,
    description,
    value,
    change,
    trend = "neutral",
    icon,
    media,
    tags,
    metric,
    actions,
    children,
  }: Props = $props();

  const titleId = stableId("ds-card");
  const labelledBy = $derived(typeof title === "string" && title ? titleId : undefined);
  const hasMedia = $derived(Boolean(imageSrc) || Boolean(icon) || Boolean(media));
</script>

{#snippet heading()}
  {#if typeof title === "function"}
    {@render title()}
  {:else if title}
    <svelte:element this={`h${headingLevel}`} class="card__title" id={titleId}>
      {title}
    </svelte:element>
  {/if}
{/snippet}

{#if variant === "dashboard"}
  <article class="card card--dashboard" data-surface={surface} aria-labelledby={labelledBy}>
    <div class="card__dash-head">
      {#if icon}
        <span class="card__icon" aria-hidden="true">{@render icon()}</span>
      {/if}
      {@render heading()}
    </div>
    <div class="card__metric">
      {#if value != null}<span class="card__value">{value}</span>{/if}
      {#if change}<span class="card__change" data-trend={trend}>{change}</span>{/if}
      {@render metric?.()}
    </div>
  </article>
{:else}
  <article
    class="card card--media"
    data-orientation={orientation}
    data-surface={surface}
    aria-labelledby={labelledBy}
  >
    {#if hasMedia}
      <div class={["card__media", icon && !imageSrc && !media && "card__media--icon"]}>
        {#if media}
          {@render media()}
        {:else if icon}
          <span class="card__icon" aria-hidden="true">{@render icon()}</span>
        {:else if imageSrc}
          <img class="card__image" src={imageSrc} alt={imageAlt} />
        {/if}
      </div>
    {/if}

    <div class="card__body">
      <div class="card__head">
        {@render heading()}
        {#if tags}
          <div class="card__tags">{@render tags()}</div>
        {/if}
      </div>

      {#if description}
        <div class="card__description">
          {#if typeof description === "function"}{@render description()}{:else}{description}{/if}
        </div>
      {/if}

      {#if children}
        <div class="card__content">{@render children()}</div>
      {/if}
    </div>

    {#if actions}
      <div class="card__actions">{@render actions()}</div>
    {/if}
  </article>
{/if}

<style>
  .card {
    box-sizing: border-box;
    background: var(--ds-card-bg, var(--ds-color-background, #fff));
    color: var(--ds-card-text, var(--ds-color-text, #282420));
    border: 1px solid var(--ds-card-border, var(--ds-color-border, #c7c1b7));
    border-radius: var(--ds-card-radius, var(--ds-radius-surface, 0.75rem));
    overflow: hidden;
  }
  .card[data-surface="secondary"] {
    background: var(--ds-card-secondary-bg, var(--ds-color-neutral-surface, #f4f2ef));
  }

  /* ---- Media card, vertical (classic) ---- */
  .card--media {
    display: flex;
    flex-direction: column;
  }
  .card__media {
    flex: none;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--ds-card-media-bg, var(--ds-color-neutral-surface, #f4f2ef));
  }
  .card__image {
    display: block;
    inline-size: 100%;
    block-size: 100%;
    object-fit: cover;
  }
  .card__media--icon {
    padding: var(--ds-card-icon-padding, 1.5rem);
    color: var(--ds-card-icon-color, var(--ds-color-text-secondary, #524c44));
  }
  .card__icon {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    inline-size: var(--ds-card-icon-size, 2.5rem);
    block-size: var(--ds-card-icon-size, 2.5rem);
  }
  .card__icon :global(svg) {
    inline-size: 100%;
    block-size: 100%;
  }

  .card__body {
    flex: 1;
    min-inline-size: 0;
    display: flex;
    flex-direction: column;
    gap: var(--ds-card-gap, 0.5rem);
    padding: var(--ds-card-padding, 1rem);
  }

  .card__head {
    display: flex;
    flex-direction: column;
    gap: 0.4rem;
    min-inline-size: 0;
  }
  /* Vertical: tags sit above the title. */
  .card__tags {
    order: -1;
    display: flex;
    flex-wrap: wrap;
    gap: 0.35rem;
  }

  .card__title {
    margin: 0;
    font-size: var(--ds-card-title-size, 1.05rem);
    font-weight: 600;
    line-height: var(--ds-line-height-tight, 1.2);
  }
  .card__description {
    margin: 0;
    color: var(--ds-card-description-text, var(--ds-color-text-secondary, #524c44));
    line-height: var(--ds-line-height, 1.4);
  }
  .card__content {
    margin-block-start: 0.25rem;
  }

  .card__actions {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    padding: var(--ds-card-actions-padding, 0.75rem 1rem);
    /* No footer divider by default — opt in via --ds-card-actions-border. */
    border-block-start: 1px solid var(--ds-card-actions-border, transparent);
  }

  /* ---- Media card, horizontal ---- */
  .card--media[data-orientation="horizontal"] {
    flex-direction: row;
    align-items: stretch;
  }
  .card--media[data-orientation="horizontal"] .card__media {
    inline-size: var(--ds-card-horizontal-media-size, 8rem);
    align-self: stretch;
  }
  .card--media[data-orientation="horizontal"] .card__media--icon {
    inline-size: auto;
    padding-inline: 1.25rem;
  }
  /* Horizontal: title and tag share a line, description sits below. */
  .card--media[data-orientation="horizontal"] .card__head {
    flex-direction: row;
    align-items: center;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
  .card--media[data-orientation="horizontal"] .card__tags {
    order: 0;
  }
  /* Horizontal: actions move to the right, vertically centered, no top border. */
  .card--media[data-orientation="horizontal"] .card__actions {
    align-items: center;
    justify-content: flex-end;
    border-block-start: 0;
    padding-inline-end: 1rem;
  }

  /* ---- Dashboard (metric tile) ---- */
  .card--dashboard {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
    padding: var(--ds-card-padding, 1rem);
  }
  .card__dash-head {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    min-inline-size: 0;
  }
  .card--dashboard .card__icon {
    color: var(--ds-card-icon-color, var(--ds-color-text-secondary, #524c44));
    inline-size: var(--ds-card-dash-icon-size, 1.75rem);
    block-size: var(--ds-card-dash-icon-size, 1.75rem);
  }
  .card__metric {
    display: flex;
    align-items: baseline;
    gap: 0.4rem;
    white-space: nowrap;
  }
  .card__value {
    font-size: var(--ds-card-value-size, 1.75rem);
    font-weight: 700;
    line-height: 1;
  }
  .card__change {
    font-size: var(--ds-card-change-size, 0.8125rem);
    font-weight: 600;
  }
  .card__change[data-trend="up"] {
    color: var(--ds-color-success-text, #334e22);
  }
  .card__change[data-trend="down"] {
    color: var(--ds-color-danger-text, #7f313c);
  }
  .card__change[data-trend="neutral"] {
    color: var(--ds-color-text-secondary, #524c44);
  }
</style>

// packages/react/src/card/Card.tsx
import { useId, type ReactNode } from "react";
import { cx } from "../internal/cx";

export interface CardProps {
  /** `media` (default): media, text and actions. `dashboard`: a metric tile. */
  variant?: "media" | "dashboard";
  /** Media card layout. Defaults to `vertical`. */
  orientation?: "vertical" | "horizontal";
  /** Surface hierarchy. `secondary` uses the quieter secondary card surface. */
  surface?: "default" | "secondary";
  /** Image URL for the media area, used as given (ignored with `icon` or `media`). */
  imageSrc?: string;
  /** Alt text for the image. Empty by default (decorative). */
  imageAlt?: string;
  /**
   * Card title. A string renders as a heading and names the card; other
   * markup replaces the heading.
   */
  title?: ReactNode;
  /** Heading level for a string title (2 to 6). Defaults to `3`. */
  headingLevel?: 2 | 3 | 4 | 5 | 6;
  /** Body description: text or markup. */
  description?: ReactNode;
  /** Dashboard: the large metric value. */
  value?: string | number;
  /** Dashboard: the smaller change shown beside the value. */
  change?: string;
  /** Dashboard: direction of the change, for its colour. */
  trend?: "up" | "down" | "neutral";
  /** Decorative icon in the media area (media) or beside the title (dashboard). */
  icon?: ReactNode;
  /** Custom media, in place of the image or the icon. */
  media?: ReactNode;
  /** Tags shown with the title. */
  tags?: ReactNode;
  /** Dashboard: extra content after the value and the change. */
  metric?: ReactNode;
  /** Actions at the end of the card. */
  actions?: ReactNode;
  /** Extra body content below the description. */
  children?: ReactNode;
}

/**
 * Card: a presentational container in three shapes.
 *
 * - `variant="media"`, `orientation="vertical"` (default): media on top, then
 *   tags, title, description and the actions.
 * - `variant="media"`, `orientation="horizontal"`: media at the start, the
 *   title with its tags and the description, actions at the end.
 * - `variant="dashboard"`: an icon over a title, a large value with a
 *   smaller change beside it (a metric tile).
 *
 * The media area holds `imageSrc`, or `icon` in its place, or your own
 * `media`. Tags and actions are markup, to compose with `Tag` and `Button`.
 *
 * Accessibility: an `<article>`; a string `title` is a heading at
 * `headingLevel` and names the card (`aria-labelledby`). Themeable via
 * `--ds-card-*`.
 */
export function Card({
  variant = "media",
  orientation = "vertical",
  surface = "default",
  imageSrc,
  imageAlt = "",
  title,
  headingLevel = 3,
  description,
  value,
  change,
  trend = "neutral",
  icon,
  media,
  tags,
  metric,
  actions,
  children,
}: CardProps) {
  const titleId = `ds-card-${useId()}`;
  const named = typeof title === "string" && title !== "";
  const labelledBy = named ? titleId : undefined;
  const Heading = `h${headingLevel}` as const;
  const heading = named ? (
    <Heading className="card__title" id={titleId}>
      {title}
    </Heading>
  ) : (
    title
  );
  const iconNode = icon ? (
    <span className="card__icon" aria-hidden="true">
      {icon}
    </span>
  ) : null;

  if (variant === "dashboard") {
    return (
      <article className="card card--dashboard" data-surface={surface} aria-labelledby={labelledBy}>
        <div className="card__dash-head">
          {iconNode}
          {heading}
        </div>
        <div className="card__metric">
          {value != null ? <span className="card__value">{value}</span> : null}
          {change ? (
            <span className="card__change" data-trend={trend}>
              {change}
            </span>
          ) : null}
          {metric}
        </div>
      </article>
    );
  }

  const hasMedia = Boolean(imageSrc || iconNode || media);
  return (
    <article
      className="card card--media"
      data-orientation={orientation}
      data-surface={surface}
      aria-labelledby={labelledBy}
    >
      {hasMedia ? (
        <div
          className={cx(
            "card__media",
            !imageSrc && !media && iconNode !== null && "card__media--icon",
          )}
        >
          {media
            ? media
            : (iconNode ?? <img className="card__image" src={imageSrc} alt={imageAlt} />)}
        </div>
      ) : null}
      <div className="card__body">
        <div className="card__head">
          {heading}
          {tags ? <div className="card__tags">{tags}</div> : null}
        </div>
        {description ? <div className="card__description">{description}</div> : null}
        {children ? <div className="card__content">{children}</div> : null}
      </div>
      {actions ? <div className="card__actions">{actions}</div> : null}
    </article>
  );
}
