// packages/react/src/menubar/Menubar.tsx
import { menu as core, menubar as bar } from "@design-system/core";
import { useCallback, useId, useMemo, useRef, useState } from "react";
import { createPortal, flushSync } from "react-dom";
import type { MenuEntry } from "../dropdown-menu/DropdownMenu";
import { useI18n } from "../i18n/i18n";
import { attachFloating } from "../internal/floating";
import { MenuPopup } from "../internal/menu";
import { usePortalHost } from "../internal/portal-host";
import { normalizeProps } from "../normalize";

/** One top-level menu in a menubar. */
export interface MenubarMenu {
  /** Stable value identifying the menu, passed to `onSelect`. */
  value: string;
  /** Visible trigger label. */
  label: string;
  /** Items, separators, groups and submenus, in the order shown. */
  items: MenuEntry[];
  /** A disabled menu takes focus on its trigger but never opens. */
  disabled?: boolean;
}

export interface MenubarProps {
  /** Accessible name for the menubar. */
  label: string;
  /** The top-level menus. */
  menus: MenubarMenu[];
  /** Called with the chosen item's menu value and item value, after the menu has closed. */
  onSelect?: (menuValue: string, itemValue: string) => void;
}

// Menus are tracked by value, so a reorder keeps each state with its menu.
interface BarState {
  focusedValue: string | null;
  openValue: string | null;
  activeValue: string | null;
  openPath: string[];
}

const ALL_CLOSED = { openValue: null, activeValue: null, openPath: [] };
const INITIAL: BarState = { focusedValue: null, ...ALL_CLOSED };

/**
 * Menubar: a horizontal bar of menus (WAI-ARIA menubar pattern), like an
 * application menu (File, Edit, View). Each top menu is a headless menu
 * (`@design-system/core`) with groups, separators, checkable items and
 * submenus (`docs/menu-submenu-spec.md`); the core `menubar` module adds the
 * roving tab stop across the triggers, one open menu at a time, and the left
 * and right arrows: into a submenu on a submenu trigger, to the next top menu
 * anywhere else, mirrored in right-to-left text. Hovering another trigger
 * while a menu is open switches to it.
 *
 * Themeable via `--ds-menu-*` (shared with Dropdown Menu) and
 * `--ds-menubar-*`.
 */
export function Menubar({ label, menus, onSelect }: MenubarProps) {
  const { locale, dir } = useI18n();
  const id = `ds-menubar-${useId()}`;
  const [state, setState] = useState<BarState>(INITIAL);
  const barRef = useRef<HTMLDivElement>(null);
  const host = usePortalHost(barRef);
  const menuId = useCallback((index: number) => `${id}-menu-${index}`, [id]);
  const triggerOf = useCallback(
    (index: number) => document.getElementById(core.triggerId(menuId(index))),
    [menuId],
  );
  const focusTrigger = useCallback((index: number) => triggerOf(index)?.focus(), [triggerOf]);

  const openIndex = menus.findIndex((menu) => menu.value === state.openValue);
  const focusedIndex = Math.max(
    0,
    menus.findIndex((menu) => menu.value === state.focusedValue),
  );
  // The open menu went away, or turned off: every menu is closed.
  if (state.openValue !== null && (openIndex === -1 || menus[openIndex]?.disabled)) {
    setState((s) => ({ ...s, ...ALL_CLOSED }));
  }

  const setOpenAt = useCallback(
    (value: string, index: number, open: boolean) => {
      if (open) {
        setState((s) =>
          s.openValue === value ? s : { ...s, openValue: value, focusedValue: value },
        );
        return;
      }
      // Closed in the DOM and focus back before the core reports the choice.
      flushSync(() => setState((s) => (s.openValue === value ? { ...s, openValue: null } : s)));
      focusTrigger(index);
    },
    [focusTrigger],
  );
  const setActiveValue = useCallback((activeValue: string | null) => {
    setState((s) => (s.activeValue === activeValue ? s : { ...s, activeValue }));
  }, []);
  const setOpenPath = useCallback((openPath: string[]) => {
    setState((s) => ({ ...s, openPath }));
  }, []);

  // One connected menu per top menu; only the open one carries the shared
  // focus and open path.
  const apis = useMemo(
    () =>
      menus.map((menu, index) => {
        const open = openIndex === index;
        return core.connect({
          state: {
            open,
            activeValue: open ? state.activeValue : null,
            openPath: open ? state.openPath : [],
            items: menu.items,
            disabled: menu.disabled ?? false,
            id: menuId(index),
          },
          setOpen: (next) => setOpenAt(menu.value, index, next),
          setActiveValue,
          setOpenPath,
          onSelect: onSelect && ((value) => onSelect(menu.value, value)),
          direction: dir,
          normalize: normalizeProps,
        });
      }),
    [menus, openIndex, state, menuId, dir, setOpenAt, setActiveValue, setOpenPath, onSelect],
  );

  const barApi = useMemo(
    () =>
      bar.connect({
        state: {
          menus: menus.map((menu) => ({ value: menu.value, disabled: menu.disabled })),
          focusedIndex,
          openIndex,
        },
        setFocusedIndex: (index) => {
          const focusedValue = menus[index]?.value ?? null;
          setState((s) => (s.focusedValue === focusedValue ? s : { ...s, focusedValue }));
        },
        openMenu: (index) => apis[index]?.openMenu("first"),
        closeMenu: (index) => apis[index]?.closeMenu(),
        focusTrigger,
        direction: dir,
        normalize: normalizeProps,
      }),
    [menus, focusedIndex, openIndex, apis, focusTrigger, dir],
  );

  // Closed without the core's close, which would move focus.
  const dismiss = () => setState((s) => ({ ...s, ...ALL_CLOSED }));

  return (
    <div ref={barRef} className="menubar" aria-label={label} {...barApi.menubarProps}>
      {menus.map((menu, index) => {
        const api = apis[index]!;
        return (
          <div key={menu.value} className="menubar__menu">
            <button
              className="menubar__trigger"
              type="button"
              {...api.triggerProps}
              {...barApi.getTriggerProps(index)}
            >
              {menu.label}
            </button>
            {api.open && host
              ? createPortal(
                  <MenuPopup
                    api={api}
                    prefix="menubar"
                    direction={dir}
                    lang={locale}
                    setOpenPath={setOpenPath}
                    position={(popup) => {
                      const trigger = triggerOf(index);
                      return trigger
                        ? attachFloating(trigger, popup, { sameWidth: true })
                        : () => {};
                    }}
                    inside={() => [triggerOf(index)]}
                    onDismiss={dismiss}
                  />,
                  host,
                )
              : null}
          </div>
        );
      })}
    </div>
  );
}

// packages/svelte/src/lib/menubar/Menubar.svelte
<script lang="ts">
  /**
   * Menubar — a horizontal bar of menus (WAI-ARIA menubar pattern), like an
   * application menu (File / Edit / View). Each menu reuses the headless menu
   * (`@design-system/core`) for open/close, arrow & Home/End item navigation,
   * typeahead, focus moving into the menu and Escape/outside to close; this
   * component adds the menubar coordination: roving tabindex across the triggers,
   * ArrowLeft/Right to move between them (or switch the open menu), Home/End, and
   * hover-to-switch while a menu is open.
   *
   * Pass `menus` ({ value, label, items, disabled? }) and an accessible `label`
   * for the bar; `onSelect(menuValue, itemValue)` runs when an item is chosen.
   * Themeable via `--ds-menu-*` (shared with DropdownMenu) and `--ds-menubar-*`.
   */
  import { createMenubar, type MenubarMenu } from "./create-menubar";
  import { portal } from "../internal/portal";
  import { getI18n } from "../i18n/create-i18n";

  /** Accessible name for the menubar. */
  const { locale: i18nLocale, dir: i18nDir } = getI18n();

  export let label: string;
  /** The top-level menus. */
  export let menus: MenubarMenu[];
  /** Called with the chosen item's menu value and item value. */
  export let onSelect: ((menuValue: string, itemValue: string) => void) | undefined = undefined;

  const menubar = createMenubar({ menus, onSelect });
  const { menubarAction, focusedIndex, menus: items } = menubar;
</script>

<div
  class="menubar"
  role="menubar"
  aria-label={label}
  aria-orientation="horizontal"
  use:menubarAction
>
  {#each items as menu, i (menu.value)}
    <div class="menubar__menu">
      <button
        class="menubar__trigger"
        type="button"
        role="menuitem"
        tabindex={i === $focusedIndex ? 0 : -1}
        use:menu.triggerAction
      >
        {menu.label}
      </button>

      <!-- Portalled out of the bar, so the bar's keydown (Arrow switching)
           must be attached here too. -->
      <div
        class="menubar__popup"
        lang={$i18nLocale}
        dir={$i18nDir}
        use:portal
        use:menubarAction
        use:menu.menuAction
      >
        {#each menu.items as item (item.value)}
          <button class="menubar__item" type="button" use:menu.itemAction={item.value}>
            {item.label ?? item.value}
          </button>
        {/each}
      </div>
    </div>
  {/each}
</div>

<style>
  .menubar {
    display: inline-flex;
    gap: var(--ds-menubar-gap, 0.125rem);
    padding: var(--ds-menubar-padding, 0.25rem);
    border: 1px solid var(--ds-color-border, #c7c1b7);
    border-radius: var(--ds-menubar-radius, var(--ds-radius-surface, 0.75rem));
    background: var(--ds-color-background, #fff);
    color: var(--ds-color-text, #282420);
    font: inherit;
  }

  .menubar__menu {
    display: inline-block;
  }

  .menubar__trigger {
    display: inline-flex;
    align-items: center;
    padding: var(--ds-menubar-trigger-padding, 0.375rem 0.625rem);
    border: 0;
    border-radius: var(--ds-menu-radius, var(--ds-radius-control, 0.5rem));
    background: transparent;
    color: inherit;
    font: inherit;
    font-weight: 600;
    cursor: pointer;
  }
  .menubar__trigger:hover,
  .menubar__trigger:global([data-state="open"]) {
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  .menubar__trigger:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
  }
  .menubar__trigger:global([data-disabled]) {
    color: var(--ds-color-text-disabled, #757067);
    cursor: not-allowed;
  }

  .menubar__popup {
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-menu-z-index, 50);
    min-inline-size: var(--ds-menu-min-width, 12rem);
    margin: 0;
    padding: var(--ds-menu-padding, 0.25rem);
    display: flex;
    flex-direction: column;
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #c7c1b7);
    border-radius: var(--ds-menu-popup-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(
      --ds-elevation-overlay,
      0 10px 15px -3px rgb(0 0 0 / 0.1),
      0 4px 6px -4px rgb(0 0 0 / 0.1)
    );
  }
  .menubar__popup:global([data-state="closed"]) {
    display: none;
  }

  .menubar__item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    inline-size: 100%;
    padding: 0.45rem 0.55rem;
    border: 0;
    border-radius: var(--ds-radius-control, 0.5rem);
    background: transparent;
    color: inherit;
    font: inherit;
    text-align: start;
    cursor: pointer;
  }
  .menubar__item:hover {
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  .menubar__item:focus-visible {
    outline: none;
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  .menubar__item:global([data-disabled]) {
    color: var(--ds-color-text-disabled, #757067);
    cursor: not-allowed;
  }
</style>
