// packages/svelte/src/lib/meter/Meter.svelte
<script lang="ts">
  /**
   * Meter — a styled gauge (WAI-ARIA meter pattern): a track with a fill that
   * reflects a value within a known range (e.g. disk usage, battery). Behaviour
   * and accessibility (role, aria-value*, low/medium/high banding) come from the
   * headless meter (`@design-system/core`); this layer adds the track, fill and
   * per-level colors.
   *
   * Provide a `label` for the accessible name. Colors, height and radius are
   * themeable via `--ds-meter-*` (per level: `--ds-meter-fill-poor|medium|high`).
   */
  import { createMeter } from "./create-meter";

  /** Current measured value. */
  export let value = 0;
  /** Minimum value. */
  export let min = 0;
  /** Maximum value. */
  export let max = 100;
  /** Upper bound of the "low" range. */
  export let low: number | undefined = undefined;
  /** Lower bound of the "high" range. */
  export let high: number | undefined = undefined;
  /**
   * Where the good end of the scale is. Defaults to `max`, so more reads as
   * better; set it near `min` for a measure where less is better.
   */
  export let optimum: number | undefined = undefined;
  /** Accessible name for the meter. */
  export let label: string;

  const meter = createMeter({ value, min, max, low, high, optimum });
  const { rootAction, indicatorAction, percentage } = meter;

  $: meter.sync({ value, min, max, low, high, optimum });
</script>

<!-- The role is declared here as well as applied by the action, so the
     server-rendered markup is valid before hydration. -->
<div
  class="meter"
  role="meter"
  aria-valuemin={min}
  aria-valuemax={max}
  aria-valuenow={Math.min(Math.max(value, min), max)}
  use:rootAction
  aria-label={label}
>
  <div class="meter__indicator" use:indicatorAction style="inline-size: {$percentage}%;"></div>
</div>

<style>
  .meter {
    inline-size: var(--ds-meter-width, 16rem);
    block-size: var(--ds-meter-height, 0.5rem);
    overflow: hidden;
    background: var(--ds-meter-track, var(--ds-color-border, #e2e8f0));
    border-radius: var(--ds-meter-radius, 999px);
  }
  .meter__indicator {
    block-size: 100%;
    background: var(--ds-meter-fill, var(--ds-brand-primary, #8dcc7a));
    border-radius: inherit;
    transition: inline-size 200ms ease;
  }
  .meter__indicator:global([data-quality="poor"]) {
    background: var(--ds-meter-fill-poor, #e6735c);
  }
  .meter__indicator:global([data-quality="suboptimal"]) {
    background: var(--ds-meter-fill-suboptimal, var(--ds-color-warning-500, #d97706));
  }
  .meter__indicator:global([data-quality="optimal"]) {
    background: var(--ds-meter-fill-optimal, #8dcc7a);
  }
  @media (prefers-reduced-motion: reduce) {
    .meter__indicator {
      transition: none;
    }
  }
</style>

// packages/react/src/meter/Meter.tsx
import { useMeter } from "./use-meter";

export interface MeterProps {
  /** Current measured value. */
  value?: number;
  min?: number;
  max?: number;
  /** Upper bound of the "low" band. */
  low?: number;
  /** Lower bound of the "high" band. */
  high?: number;
  /**
   * Where the good end of the scale is. Defaults to `max`, so more reads as
   * better; set it near `min` for a measure where less is better.
   */
  optimum?: number;
  /** Accessible name for the meter. */
  label: string;
}

/**
 * Meter: a gauge (WAI-ARIA meter pattern), a track with a fill that shows a
 * value within a known range, such as disk usage or battery. The role, the
 * ARIA value and the low, medium and high bands come from the headless meter
 * (`@design-system/core`); the fill is coloured by how good the value is.
 *
 * A meter reports a measurement; for the completion of a task use
 * `Progress`.
 *
 * `label` names it. Themeable via `--ds-meter-*`.
 */
export function Meter({ value, min, max, low, high, optimum, label }: MeterProps) {
  const api = useMeter({ value, min, max, low, high, optimum });
  return (
    <div {...api.rootProps} className="meter" aria-label={label}>
      <div
        {...api.indicatorProps}
        className="meter__indicator"
        // The fill follows the value and the shared sheet leaves its size to
        // the adapter, so it goes inline as in the other adapters.
        style={{ inlineSize: `${api.percentage}%` }}
      />
    </div>
  );
}
