// packages/react/src/popover/Popover.tsx
import { useRef, type MouseEvent, type PointerEvent, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Button } from "../button/Button";
import type { ButtonVariant } from "../button/use-button";
import { useI18n } from "../i18n/i18n";
import type { Placement } from "../internal/floating";
import { usePortalHost } from "../internal/portal-host";
import { useHoverPreview } from "./use-hover-preview";
import { usePopover } from "./use-popover";

export interface PopoverProps {
  /** Opening contract: an intentional click, or a hover and focus preview. */
  trigger?: "click" | "hover";
  /** Visual variant for the trigger Button (`trigger="click"` only). */
  triggerVariant?: ButtonVariant;
  /** Initial / controlled open state. */
  open?: boolean;
  /** Preferred placement of the panel. */
  placement?: Placement;
  /** Delay before opening on hover, in ms (`trigger="hover"` only). */
  openDelay?: number;
  /** Delay before closing on leave, in ms (`trigger="hover"` only). */
  closeDelay?: number;
  /** Name for the panel. Defaults to being named by the trigger. */
  label?: string;
  /** Called whenever the user opens or closes the panel. */
  onOpenChange?: (open: boolean) => void;
  /**
   * The trigger button's content (defaults to the catalog's label), or the
   * focusable trigger element itself in hover mode.
   */
  triggerContent?: ReactNode;
  /** The card. */
  children?: ReactNode;
}

type ModeProps = Required<
  Pick<PopoverProps, "triggerVariant" | "open" | "placement" | "openDelay" | "closeDelay">
> &
  Pick<PopoverProps, "label" | "onOpenChange" | "triggerContent" | "children">;

/**
 * Popover: a styled, non-modal floating card anchored to a trigger. Two
 * opening contracts, one component:
 *
 * - **`trigger="click"`** (default): a Button opens it intentionally.
 *   Behaviour and accessibility (`aria-haspopup` and `aria-expanded` wiring,
 *   Escape to close) come from the headless popover (`@design-system/core`);
 *   the adapter adds Floating UI positioning, closing on an outside press or
 *   when focus leaves, and focus management (into the panel on open, back to
 *   the trigger after Escape).
 * - **`trigger="hover"`** (the pattern other libraries call a hover card):
 *   the card previews on hover and keyboard focus of `triggerContent`
 *   (typically a link), with open and close delays; focus never moves into
 *   the card, and the card holds nothing focusable. The first click or tap
 *   opens the preview instead of activating the trigger; once open, the
 *   trigger's own action proceeds, and a second tap closes it. Hover content
 *   is supplementary: essential information and interactive content belong
 *   to `trigger="click"`.
 *
 * Inside an open dialog the card renders in the dialog (ADR 0016). `open` is
 * a controllable mirror (ADR 0011). Themeable via `--ds-popover-*`.
 */
export function Popover({
  trigger = "click",
  triggerVariant = "default",
  open = false,
  placement = "bottom",
  openDelay = 300,
  closeDelay = 200,
  label,
  onOpenChange,
  triggerContent,
  children,
}: PopoverProps) {
  const props = {
    triggerVariant,
    open,
    placement,
    openDelay,
    closeDelay,
    label,
    onOpenChange,
    triggerContent,
    children,
  };
  // The two contracts wire different behaviour to different markup.
  return trigger === "hover" ? <HoverPopover {...props} /> : <ClickPopover {...props} />;
}

function ClickPopover({
  triggerVariant,
  open,
  placement,
  label,
  onOpenChange,
  triggerContent,
  children,
}: ModeProps) {
  const { t, locale, dir } = useI18n();
  const {
    api,
    open: isOpen,
    triggerRef,
    panelRef,
  } = usePopover({
    open,
    placement,
    label,
    onOpenChange,
  });
  const host = usePortalHost(triggerRef);

  return (
    <>
      <Button variant={triggerVariant} {...api.triggerProps} ref={triggerRef}>
        {triggerContent ?? t("dialog.trigger")}
      </Button>
      {isOpen && host
        ? createPortal(
            <div
              {...api.contentProps}
              ref={panelRef}
              className="popover__content"
              lang={locale}
              dir={dir}
            >
              {children}
            </div>,
            host,
          )
        : null}
    </>
  );
}

function HoverPopover({
  open,
  placement,
  openDelay,
  closeDelay,
  onOpenChange,
  triggerContent,
  children,
}: ModeProps) {
  const { locale, dir } = useI18n();
  const {
    api,
    open: isOpen,
    triggerRef,
    cardRef,
    show,
    hide,
    hold,
  } = useHoverPreview({
    open,
    placement,
    openDelay,
    closeDelay,
    onOpenChange,
  });
  const host = usePortalHost(triggerRef);
  // Touch has no hover: the tap owns touch, so the card does not flash.
  const touch = useRef(false);

  const onPointerEnter = (event: PointerEvent) => {
    if (event.pointerType !== "touch") show();
  };
  const onPointerDown = (event: PointerEvent) => {
    touch.current = event.pointerType !== "mouse";
  };
  // The first activation shows the preview instead of the trigger's own
  // action; once open the default proceeds (a link navigates), and a second
  // tap closes it: the popover contract where hover does not exist.
  const onClick = (event: MouseEvent) => {
    if (!isOpen) {
      event.preventDefault();
      show(0);
    } else if (touch.current) {
      hide(0);
    }
  };

  return (
    <>
      {/* The wrapper carries the hover and focus listeners; the element passed
          in (typically a link) stays the focusable trigger. */}
      <span
        {...api.triggerProps}
        ref={triggerRef}
        className="popover__hover-trigger"
        onPointerEnter={onPointerEnter}
        onPointerLeave={() => hide()}
        onFocus={() => show(0)}
        onPointerDown={onPointerDown}
        onClick={onClick}
      >
        {triggerContent}
      </span>
      {isOpen && host
        ? createPortal(
            <div
              {...api.contentProps}
              ref={cardRef}
              className="popover__content"
              lang={locale}
              dir={dir}
              onPointerEnter={hold}
              onPointerLeave={() => hide()}
            >
              {children}
            </div>,
            host,
          )
        : null}
    </>
  );
}

// packages/svelte/src/lib/popover/Popover.svelte
<script lang="ts">
  /**
   * Popover — a styled, non-modal floating card anchored to a trigger. Two
   * opening contracts, one component:
   *
   * - **`trigger="click"`** (default): a Button opens it intentionally.
   *   Behaviour and accessibility (open/close, `aria-haspopup`/`aria-expanded`
   *   wiring, Escape to close) come from the headless popover
   *   (`@design-system/core`); the adapter adds Floating-UI positioning
   *   (flip/shift), outside-press + focus-leave dismissal, and focus management
   *   (focus moves into the panel on open, returns to the trigger on Escape).
   * - **`trigger="hover"`** (the pattern formerly shipped as HoverCard): the
   *   card previews on hover **and keyboard focus** of the slotted trigger
   *   (typically a link), with open/close delays; focus never moves into the
   *   card, and the card holds nothing focusable. The first click/tap opens the
   *   preview instead of activating the trigger; once open, the default action
   *   (e.g. link navigation) proceeds — so touch users get the popover
   *   contract. Hover content must be **supplementary**: never put essential
   *   information only in here. Interactive content belongs to
   *   `trigger="click"`.
   *
   * Slots: `trigger` (button content, or the focusable element itself in hover
   * mode) and the default slot (the card). Themeable via `--ds-popover-*`.
   */
  import { createPopover, type PopoverContext } from "./create-popover";
  import { portal } from "../internal/portal";
  import { createHoverCard } from "../hover-card/create-hover-card";
  import Button from "../button/Button.svelte";
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  /** Opening contract: an intentional click, or a hover/focus preview. */
  export let trigger: "click" | "hover" = "click";
  /** Visual variant for the trigger Button (`trigger="click"` only). */
  export let triggerVariant: "default" | "primary" | "secondary" | "ghost" | "danger" = "default";
  /** Initial open state. */
  export let open = false;
  /** Preferred placement of the panel. */
  export let placement: PopoverContext["placement"] = "bottom";
  /** Delay before opening on hover, in ms (`trigger="hover"` only). */
  export let openDelay = 300;
  /** Delay before closing on leave, in ms (`trigger="hover"` only). */
  export let closeDelay = 200;
  /** Name for the panel. Defaults to being named by the trigger. */
  export let label: string | undefined = undefined;
  /** Called whenever the open state changes. */
  export let onOpenChange: ((open: boolean) => void) | undefined = undefined;

  const handleOpenChange = (next: boolean) => {
    open = next;
    onOpenChange?.(next);
  };

  const behavior =
    trigger === "hover"
      ? createHoverCard({ open, placement, openDelay, closeDelay, onOpenChange: handleOpenChange })
      : createPopover({ open, placement, label, onOpenChange: handleOpenChange });
  const { triggerAction, contentAction, open: isOpen, setOpen } = behavior;

  $: behavior.setOpen(open);
  // Hover mode is a different primitive with no panel name of its own.
  $: if (trigger !== "hover") behavior.setLabel?.(label);

  // First activation (a tap, or a click that beat the hover delay) shows the
  // preview instead of the trigger's own action; once open, the default
  // proceeds (e.g. the link navigates). This is what makes hover mode work on
  // touch, where hover does not exist.
  const previewFirst = (event: MouseEvent) => {
    if (!$isOpen) {
      event.preventDefault();
      setOpen(true);
    }
  };
</script>

{#if trigger === "hover"}
  <!-- The wrapper carries the hover/focus listeners; the slotted element
       (typically a link) stays the focusable trigger. -->
  <!-- svelte-ignore a11y_no_static_element_interactions a11y_click_events_have_key_events -->
  <span class="popover__hover-trigger" use:triggerAction on:click={previewFirst}>
    <slot name="trigger" />
  </span>
{:else}
  <Button variant={triggerVariant} action={triggerAction}>
    <slot name="trigger">{$t("dialog.trigger")}</slot>
  </Button>
{/if}

{#if $isOpen}
  <div class="popover__content" use:portal use:contentAction>
    <slot />
  </div>
{/if}

<style>
  .popover__hover-trigger {
    display: inline-flex;
  }

  .popover__content {
    /* Positioned by the adapter (Floating UI) with a fixed strategy. */
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-popover-z-index, 100);
    box-sizing: border-box;
    inline-size: max-content;
    max-inline-size: var(--ds-popover-max-width, 20rem);
    padding: var(--ds-popover-padding, 0.875rem 1rem);
    background: var(--ds-color-background, #fff);
    color: var(--ds-color-text, #0f172a);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-popover-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(
      --ds-elevation-overlay,
      0 10px 15px -3px rgb(0 0 0 / 0.1),
      0 4px 6px -4px rgb(0 0 0 / 0.1)
    );
  }
  /* Quieter focus: keep the elevation, tint the border and lay a thin ring just
     inside it — rather than wrapping the whole card in a thick outer ring. */
  .popover__content:focus-visible {
    outline: none;
    border-color: var(--ds-color-focus-ring, #7b52cc);
    box-shadow:
      inset 0 0 0 1px var(--ds-color-focus-ring, #7b52cc),
      var(
        --ds-elevation-overlay,
        0 10px 15px -3px rgb(0 0 0 / 0.1),
        0 4px 6px -4px rgb(0 0 0 / 0.1)
      );
  }
</style>
