// packages/svelte/src/lib/aspect-ratio/AspectRatio.svelte
<script lang="ts">
  /**
   * AspectRatio — constrains its content to a fixed width-to-height ratio using
   * the CSS `aspect-ratio` property. Presentational only (no ARIA role): drop in
   * an image, video, iframe or any block content via the default slot, and it is
   * cropped to fill the box.
   *
   * Radius is themeable via `--ds-aspect-ratio-radius`.
   */
  /** Width-to-height ratio, e.g. `16 / 9`, `4 / 3`, `1`. */
  export let ratio = 1;
</script>

<!-- The ratio flows through a private variable: the prop always sets it
     inline, so an external custom-property override could never win. -->
<div class="aspect-ratio" style="--_aspect-ratio: {ratio};" data-aspect-ratio>
  <slot />
</div>

<style>
  .aspect-ratio {
    aspect-ratio: var(--_aspect-ratio, 1);
    inline-size: 100%;
    overflow: hidden;
    border-radius: var(--ds-aspect-ratio-radius, 0);
  }
  /* Common embedded media fills the box. */
  .aspect-ratio :global(img),
  .aspect-ratio :global(video),
  .aspect-ratio :global(iframe) {
    inline-size: 100%;
    block-size: 100%;
    object-fit: cover;
    display: block;
  }
</style>

// packages/react/src/aspect-ratio/AspectRatio.tsx
import type { CSSProperties, ReactNode } from "react";

export interface AspectRatioProps {
  /** Width-to-height ratio, such as `16 / 9`, `4 / 3` or `1`. */
  ratio?: number;
  /** The media or block content to fit in the box. */
  children?: ReactNode;
}

/**
 * AspectRatio: holds its content to a fixed width-to-height ratio with the
 * CSS `aspect-ratio` property. Presentational only (no role): an image,
 * video, iframe or any block content is cropped to fill the box.
 *
 * Radius is themeable via `--ds-aspect-ratio-radius`.
 */
export function AspectRatio({ ratio = 1, children }: AspectRatioProps) {
  return (
    <div
      className="aspect-ratio"
      // The shared sheet reads the ratio from this private custom property;
      // the prop always sets it, so an outside override could never win.
      style={{ "--_aspect-ratio": ratio } as CSSProperties}
      data-aspect-ratio=""
    >
      {children}
    </div>
  );
}
