// packages/svelte/src/lib/error-state/ErrorState.svelte
<script lang="ts">
  /**
   * ErrorState — a centered, full-page (or full-section) message shown when
   * something has gone wrong: a failed request, a 500, a lost connection. This
   * is an *error* state, distinct from an *empty* state (no content yet): use
   * this when an action or load failed and the user needs to recover.
   *
   * Layout: a status `FeedbackIcon` (danger by default), a `title`, an optional
   * `description`, and a recovery action area at the bottom: a single `Button`
   * from `actionLabel`/`onAction` (e.g. "Try again"), or a configurable group
   * from an `actions` array. It is **not** dismissable: an error state
   * replaces the content it covers, so there is nothing to close.
   *
   * Reuses the existing `FeedbackIcon` and `Button`. Swap the icon for another
   * glyph or an ad-hoc illustration via the `icon` snippet (e.g. a bespoke 404
   * artwork), or replace the whole action area with an `actions` snippet.
   * Themeable via `--ds-error-state-*`.
   *
   * Accessibility: the region is a `role="alert"`, so when it appears it is
   * announced. Meaning never rests on color alone — the title (and the icon
   * glyph) carry it (WCAG 1.4.1).
   */
  import type { Snippet } from "svelte";
  import FeedbackIcon from "../feedback-icon/FeedbackIcon.svelte";
  import Button from "../button/Button.svelte";
  import Link from "../link/Link.svelte";
  import type { ButtonVariant } from "../button/create-button";

  interface Props {
    /** The headline — what went wrong, in plain language. */
    title: string;
    /** Optional secondary line — detail or next step. */
    description?: string;
    /** Feedback status driving the default icon's color and glyph. */
    status?: "info" | "success" | "warning" | "danger" | "neutral";
    /** Heading level for the title, so it fits the surrounding document outline. */
    headingLevel?: 1 | 2 | 3 | 4 | 5 | 6;
    /** Recovery button label (e.g. "Try again"). Omit to render no button. */
    actionLabel?: string;
    /** Called when the recovery button is pressed. */
    onAction?: () => void;
    /**
     * Configurable action group. An entry with `href` renders a `Link` (a
     * direct pathway, e.g. "Learn more" documentation); the others render
     * `Button`s: the first gets the `default` variant and the rest `ghost`,
     * unless an entry sets its own `variant`. Takes precedence over
     * `actionLabel`. A snippet instead replaces the whole area.
     */
    actions?:
      | {
          label: string;
          onAction?: () => void;
          variant?: ButtonVariant;
          href?: string;
          target?: string;
        }[]
      | Snippet;
    /** Density: `md` for full pages and sections, `sm` inside cards, panels and table areas. */
    size?: "md" | "sm";
    /** Glyph or illustration in place of the default `FeedbackIcon`. */
    icon?: Snippet;
    /** Extra content between the description and the actions. */
    children?: Snippet;
  }

  let {
    title,
    description,
    status = "danger",
    headingLevel = 2,
    actionLabel,
    onAction,
    actions = [],
    size = "md",
    icon,
    children,
  }: Props = $props();

  const actionItems = $derived(Array.isArray(actions) ? actions : []);
</script>

<div class="error-state" role="alert" data-size={size}>
  <span class="error-state__icon">
    {#if icon}
      {@render icon()}
    {:else}
      <FeedbackIcon {status} box="tint" shape="round" />
    {/if}
  </span>

  <svelte:element this={`h${headingLevel}`} class="error-state__title">
    {title}
  </svelte:element>

  {#if description}
    <p class="error-state__description">{description}</p>
  {/if}

  {@render children?.()}

  {#if typeof actions === "function" || actionItems.length || actionLabel}
    <div class="error-state__actions">
      {#if typeof actions === "function"}
        {@render actions()}
      {:else if actionItems.length}
        {#each actionItems as action, index (action.label)}
          {#if action.href}
            <Link href={action.href} target={action.target} onclick={() => action.onAction?.()}>
              {action.label}
            </Link>
          {:else}
            <Button
              variant={action.variant ?? (index === 0 ? "default" : "ghost")}
              onpress={action.onAction}
            >
              {action.label}
            </Button>
          {/if}
        {/each}
      {:else if actionLabel}
        <Button variant="default" onpress={onAction}>{actionLabel}</Button>
      {/if}
    </div>
  {/if}
</div>

<style>
  .error-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    gap: var(--ds-error-state-gap, 0.75rem);
    padding: var(--ds-error-state-padding, 3rem 1.5rem);
    max-inline-size: var(--ds-error-state-max-width, 24rem);
    margin-inline: auto;
    color: var(--ds-color-text, #282420);
  }
  /* A larger status icon than the inline default — this is the focal point. */
  .error-state__icon {
    --ds-feedback-icon-size: var(--ds-error-state-icon-size, 3.5rem);
    margin-block-end: 0.25rem;
  }
  .error-state__title {
    margin: 0;
    font-size: var(--ds-error-state-title-size, 1.25rem);
    font-weight: 700;
    line-height: var(--ds-line-height-tight, 1.2);
  }
  .error-state__description {
    margin: 0;
    color: var(--ds-color-text-secondary, #524c44);
  }
  .error-state__actions {
    margin-block-start: 0.5rem;
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    justify-content: center;
    align-items: center;
  }
  /* Compact density for cards, panels and table areas. */
  .error-state[data-size="sm"] {
    gap: var(--ds-error-state-gap, 0.5rem);
    padding: var(--ds-error-state-padding, 1.5rem 1rem);
  }
  .error-state[data-size="sm"] .error-state__icon {
    --ds-feedback-icon-size: var(--ds-error-state-icon-size, 2.5rem);
  }
  .error-state[data-size="sm"] .error-state__title {
    font-size: var(--ds-error-state-title-size, 1rem);
  }
</style>

// packages/react/src/error-state/ErrorState.tsx
import type { ReactNode } from "react";
import { FeedbackIcon, type FeedbackStatus } from "../feedback-icon/FeedbackIcon";
import { stateActions, type StateAction } from "../internal/state-actions";

/** One entry of the configurable action group. */
export type ErrorStateAction = StateAction;

export interface ErrorStateProps {
  /** The headline: what went wrong, in plain language. */
  title: string;
  /** Optional secondary line: detail or next step. */
  description?: string;
  /** Feedback status driving the default icon's colour and glyph. */
  status?: FeedbackStatus;
  /** Heading level for the title, so it fits the surrounding document outline. */
  headingLevel?: 1 | 2 | 3 | 4 | 5 | 6;
  /** Recovery button label (such as "Try again"). Omit it to render no button. */
  actionLabel?: string;
  /** Called when the recovery button is pressed. */
  onAction?: () => void;
  /**
   * The action area: entries, or markup of your own. An entry with `href`
   * renders a `Link`; the others render `Button`s, the first `default` and the
   * rest `ghost` unless an entry sets its own `variant`. Takes precedence over
   * `actionLabel`.
   */
  actions?: ErrorStateAction[] | ReactNode;
  /** Density: `md` for pages and sections, `sm` inside cards, panels and tables. */
  size?: "md" | "sm";
  /** A glyph or artwork of your own, in place of the status `FeedbackIcon`. */
  icon?: ReactNode;
  /** Extra content between the description and the actions. */
  children?: ReactNode;
}

/**
 * ErrorState: a centred message for a page or a section where something went
 * wrong: a failed request, a server error, a lost connection. Use it when the
 * user needs to recover; for a space that is simply empty, use `EmptyState`.
 *
 * Layout: a status `FeedbackIcon` (danger by default, or `icon`), a `title`,
 * an optional `description`, and a recovery area: one `Button` from
 * `actionLabel` and `onAction` ("Try again"), or the `actions` group. An
 * error state replaces the content it covers, so it has no dismiss control.
 * Themeable via `--ds-error-state-*`.
 *
 * Accessibility: the region is a `role="alert"`, announced when it appears.
 * The title and the glyph carry the meaning, never the colour alone.
 */
export function ErrorState({
  title,
  description,
  status = "danger",
  headingLevel = 2,
  actionLabel,
  onAction,
  actions,
  size = "md",
  icon,
  children,
}: ErrorStateProps) {
  const Heading = `h${headingLevel}` as const;
  const actionArea = stateActions(actions, actionLabel, onAction);
  return (
    <div className="error-state" role="alert" data-size={size}>
      <span className="error-state__icon">
        {icon ?? <FeedbackIcon status={status} box="tint" shape="round" />}
      </span>
      <Heading className="error-state__title">{title}</Heading>
      {description ? <p className="error-state__description">{description}</p> : null}
      {children}
      {actionArea ? <div className="error-state__actions">{actionArea}</div> : null}
    </div>
  );
}
