// packages/react/src/tabs/Tabs.tsx
import type { ReactNode } from "react";
import { Icon } from "../icon/Icon";
import { cx } from "../internal/cx";
import { useTabs, type ActivationMode, type TabItem } from "./use-tabs";

/**
 * A tab, with an optional display `label` (falls back to `value`) and its
 * panel `content`. May also carry a `count` (a trailing badge, read as part of
 * the tab's name), a leading `icon` (an SVG path `d` string), and `iconOnly`
 * to render just the icon (the label becomes the accessible name).
 */
export type TabsItem = TabItem & {
  label?: string;
  content?: ReactNode;
  count?: number;
  icon?: string;
  iconOnly?: boolean;
};

export interface TabsProps {
  items: TabsItem[];
  /** Initial (uncontrolled) or current (controlled) selected tab. */
  value?: string | null;
  /** `automatic` (default): arrows select while moving. `manual`: Enter or Space selects. */
  activationMode?: ActivationMode;
  /** Accessible name for the tab list (announced by screen readers). */
  label: string;
  /** Called whenever the selected tab changes. */
  onValueChange?: (value: string) => void;
  /** Rich content of one panel, rendered once per tab; wins over `content`. */
  renderPanel?: (item: TabsItem) => ReactNode;
}

/**
 * Tabs: the styled tabs widget (WAI-ARIA tabs pattern): roving tabindex,
 * arrow/Home/End navigation, automatic or manual activation. Behaviour and
 * accessibility come from the headless tabs (`@design-system/core`); this
 * layer adds the underline indicator and panels.
 *
 * Each item supplies a tab `label` (falling back to `value`) and its panel
 * `content`; `renderPanel` renders a panel from its item instead. For a strip
 * placed apart from its panels, use `useTabs`. Colors are themeable CSS
 * custom properties (`--ds-tabs-*`).
 */
export function Tabs({
  items,
  value = null,
  activationMode = "automatic",
  label,
  onValueChange,
  renderPanel,
}: TabsProps) {
  const { api } = useTabs({ items, value, activationMode, onValueChange });

  return (
    <div className="tabs">
      <div className="tabs__list" {...api.rootProps} aria-label={label}>
        {items.map((item) => {
          const name = item.label ?? item.value;
          const counted = item.count != null;
          return (
            <button
              key={item.value}
              type="button"
              className={cx("tabs__tab", item.iconOnly && "tabs__tab--icon-only")}
              {...api.getTabProps(item.value)}
              // The count is part of the name; the badge itself stays hidden
              // so it is not read as a separate word.
              aria-label={item.iconOnly ? (counted ? `${name} (${item.count})` : name) : undefined}
            >
              {item.icon ? (
                <span className="tabs__tab-icon" aria-hidden="true">
                  <Icon size="100%">
                    <path d={item.icon} />
                  </Icon>
                </span>
              ) : null}
              {item.iconOnly ? null : <span className="tabs__tab-label">{name}</span>}
              {counted ? (
                <span className="tabs__tab-count" aria-hidden="true">
                  {item.count}
                </span>
              ) : null}
              {counted && !item.iconOnly ? (
                <span className="tabs__sr">{` (${item.count})`}</span>
              ) : null}
            </button>
          );
        })}
      </div>
      {items.map((item) => (
        <div key={item.value} className="tabs__panel" {...api.getPanelProps(item.value)}>
          {renderPanel ? renderPanel(item) : item.content}
        </div>
      ))}
    </div>
  );
}

// packages/svelte/src/lib/tabs/Tabs.svelte
<script context="module" lang="ts">
  import type { TabItem } from "./create-tabs";

  /**
   * A tab, with an optional display label and its panel text. May also carry a
   * `count` (shown as a trailing badge — violet when the tab is selected, grey
   * otherwise), a leading `icon` (an SVG path `d` string), and `iconOnly` to
   * render just the icon (the label becomes the accessible name).
   */
  export type TabsItem = TabItem & {
    label?: string;
    content?: string;
    count?: number;
    icon?: string;
    iconOnly?: boolean;
  };
</script>

<script lang="ts">
  /**
   * Tabs — the styled, batteries-included tabs widget (WAI-ARIA tabs pattern):
   * roving tabindex, arrow/Home/End navigation, automatic or manual activation.
   * Behaviour and accessibility come from the headless tabs (`@design-system/core`);
   * this layer adds the underline indicator and panels.
   *
   * Each item supplies a tab `label` (falling back to `value`) and, optionally,
   * its panel `content` as text. For rich panel markup, use the scoped `panel`
   * slot — it renders once per tab with `let:item`, so the consumer can put any
   * content in the (correctly wired) panel and switch on `item.value`; the text
   * `content` is the fallback when the slot is absent. Colors are themeable CSS
   * custom properties (`--ds-tabs-*`).
   */
  import { createTabs, type ActivationMode } from "./create-tabs";
  import Icon from "../icon/Icon.svelte";

  export let items: TabsItem[];
  export let value: string | null = null;
  export let activationMode: ActivationMode = "automatic";
  /** Accessible name for the tab list (announced by screen readers). */
  export let label: string;
  /** Called whenever the selected tab changes. */
  export let onValueChange: ((value: string) => void) | undefined = undefined;

  const handleValueChange = (next: string) => {
    value = next;
    onValueChange?.(next);
  };

  const { rootAction, tabAction, panelAction, syncValue, setItems, setActivationMode } = createTabs(
    {
      items,
      value,
      activationMode,
      onValueChange: handleValueChange,
    },
  );

  $: syncValue(value);
  $: setItems(items);
  $: setActivationMode(activationMode);
</script>

<div class="tabs">
  <div class="tabs__list" use:rootAction aria-label={label}>
    {#each items as item (item.value)}
      <button
        class="tabs__tab"
        class:tabs__tab--icon-only={item.iconOnly}
        use:tabAction={item.value}
        aria-label={item.iconOnly ? (item.label ?? item.value) : undefined}
      >
        {#if item.icon}
          <span class="tabs__tab-icon" aria-hidden="true">
            <Icon size="100%"><path d={item.icon} /></Icon>
          </span>
        {/if}
        {#if !item.iconOnly}
          <span class="tabs__tab-label">{item.label ?? item.value}</span>
        {/if}
        {#if item.count != null}
          <span class="tabs__tab-count" aria-hidden="true">{item.count}</span>
        {/if}
      </button>
    {/each}
  </div>
  {#each items as item (item.value)}
    <div class="tabs__panel" use:panelAction={item.value}>
      <!-- Rich per-panel content via a scoped slot; falls back to the item's
           text `content` when no slot is provided (backward compatible). -->
      <slot name="panel" {item}>{item.content ?? ""}</slot>
    </div>
  {/each}
</div>

<style>
  .tabs__list {
    display: inline-flex;
    gap: 0.25rem;
    border-block-end: 1px solid var(--ds-color-border, #c7c1b7);
  }
  .tabs__tab {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: var(--ds-tabs-tab-padding, 0.4rem 0.8rem);
    border: none;
    background: none;
    cursor: pointer;
    font: inherit;
    /* Idle tabs use full-strength text (not muted grey). */
    color: var(--ds-color-text, #282420);
    border-block-end: 2px solid transparent;
    margin-block-end: -1px;
    transition:
      color 120ms ease,
      border-color 120ms ease;
  }
  .tabs__tab-icon {
    display: inline-flex;
    inline-size: 1.1em;
    block-size: 1.1em;
    flex: none;
  }
  .tabs__tab--icon-only {
    padding-inline: 0.55rem;
  }
  /* Count badge: grey pill by default, violet when the tab is selected. */
  .tabs__tab-count {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-inline-size: 1.25rem;
    padding-inline: 0.35rem;
    font-size: 0.75rem;
    font-weight: 600;
    line-height: 1.4;
    border-radius: var(--ds-radius-pill, 999px);
    color: var(--ds-color-text-secondary, #524c44);
    background: var(--ds-color-neutral-surface, #f4f2ef);
  }
  .tabs__tab:global([data-state="active"]) .tabs__tab-count {
    color: var(--ds-color-on-selected, var(--ds-color-on-secondary, #fff));
    background: var(--ds-color-selected, #7a52cc);
  }
  .tabs__tab:global([data-state="active"]) {
    /* Selected tab: the label stays the normal text color; only the underline
       carries the selection color (so the accent can change without recoloring
       the text). */
    font-weight: 700;
    color: var(--ds-color-text, #282420);
    border-block-end-color: var(--ds-color-selected, #7a52cc);
  }
  .tabs__tab:global(:focus-visible) {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }
  .tabs__tab:global([data-disabled]) {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .tabs__panel {
    padding-block: 0.75rem;
    color: var(--ds-color-text-secondary, #524c44);
  }
</style>
