// packages/react/src/combobox/Combobox.tsx
import { useEffect, useState, type MouseEvent, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Icon } from "../icon/Icon";
import { useI18n } from "../i18n/i18n";
import { useCombobox, type ComboboxItem } from "./use-combobox";

/** A combobox option, optionally carrying a leading icon (an SVG path `d`). */
export interface ComboboxOption extends ComboboxItem {
  icon?: string;
}

export interface ComboboxProps {
  /** Accessible name for the control. */
  label: string;
  /** Options. Each may carry a leading `icon`; with the search hidden, the
   *  control mirrors the selected option's icon. */
  items: ComboboxOption[];
  value?: string | null;
  /**
   * With `searchable={false}` the input becomes read-only and the list always
   * shows every option — a select-only combobox: the advanced Select (styled
   * popup, per-option icons) without the autocomplete.
   */
  searchable?: boolean;
  /**
   * Width behaviour: `fixed` (default) uses `--ds-combobox-width`, `wrap` fits
   * the longest option, `fill` takes 100% of the container.
   */
  width?: "wrap" | "fill" | "fixed";
  /** Input placeholder. Defaults to the catalog's "Search…". */
  placeholder?: string;
  disabled?: boolean;
  /** Clear button accessible name. Defaults to the catalog's "Clear". */
  clearLabel?: string;
  /** Text shown when no option matches. Defaults to the catalog's "No results". */
  emptyText?: string;
  /** Form field name — the selected option's value is submitted under it. */
  name?: string;
  onValueChange?: (value: string | null) => void;
  onInputValueChange?: (text: string) => void;
  /** Leading icon shown when `searchable={false}` and no option icon applies. */
  icon?: ReactNode;
}

/**
 * Combobox — a styled editable autocomplete (WAI-ARIA editable combobox), and
 * the design system's **advanced select**.
 *
 * Behaviour and accessibility come from the headless combobox
 * (`@design-system/core`); this adapter owns the DOM concerns — filtering,
 * popup positioning (flip/shift via Floating UI), close-on-outside-pointer and
 * keeping the active option in view. DOM focus stays on the input; the
 * highlighted option travels through `aria-activedescendant`.
 *
 * Use it over `Select` whenever options need to be *drawn* (icons, rich
 * content) or searched — see
 * `docs/adr/0003-native-select-advanced-combobox.md`. Themeable via
 * `--ds-combobox-*` (and the shared `--ds-select-*` listbox tokens).
 */
export function Combobox({
  label,
  items,
  value = null,
  searchable = true,
  width = "fixed",
  placeholder,
  disabled = false,
  clearLabel,
  emptyText,
  name,
  onValueChange,
  onInputValueChange,
  icon,
}: ComboboxProps) {
  const { t } = useI18n();

  const combobox = useCombobox({
    items,
    value,
    disabled,
    // Select-only mode never filters: the read-only input is a trigger, so the
    // list must always show every option (keyboard opening included).
    filter: searchable ? undefined : (all) => all,
    onValueChange,
    onInputValueChange,
  });

  const {
    api,
    items: visible,
    inputValue,
    value: selectedValue,
    open,
    inputRef,
    listboxRef,
    controlRef,
    floatingStyles,
    onInputChange,
    onInputPointerDown,
    openAll,
    setOpen,
  } = combobox;

  const resolvedPlaceholder = placeholder ?? t("combobox.placeholder");
  const resolvedClearLabel = clearLabel ?? t("combobox.clear");
  const resolvedEmptyText = emptyText ?? t("combobox.empty");

  const selected = items.find((item) => item.value === selectedValue);
  const hasIcons = items.some((item) => item.icon);
  const clearHidden = api.clearProps["aria-hidden"] === "true";

  // The listbox is portalled to the body, so it must not render before mount.
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  // The chevron toggles the list (showing all options when opening), so a
  // selected value can be changed without clearing it first. iOS Safari can
  // synthesize a duplicate "ghost" click; ignore one that lands right after the
  // last so the list doesn't open then immediately close.
  const [lastToggle, setLastToggle] = useState(-Infinity);
  const toggle = (event: MouseEvent) => {
    if (event.timeStamp - lastToggle < 350) return;
    setLastToggle(event.timeStamp);
    if (open) setOpen(false);
    else openAll();
  };

  const listbox = (
    <ul {...api.listboxProps} ref={listboxRef} className="combobox__listbox" style={floatingStyles}>
      {visible.length > 0 ? (
        visible.map((item) => {
          // The hook filters plain core items; the icon lives on the prop list.
          const optionIcon = items.find((i) => i.value === item.value)?.icon;
          return (
            <li key={item.value} {...api.getOptionProps(item.value)} className="combobox__option">
              <span className="combobox__check" aria-hidden="true">
                <Icon size="100%" strokeWidth={2.5}>
                  <polyline points="20 6 9 17 4 12" />
                </Icon>
              </span>
              {hasIcons && (
                <span className="combobox__option-icon" aria-hidden="true">
                  {optionIcon && (
                    <Icon size="100%">
                      <path d={optionIcon} />
                    </Icon>
                  )}
                </span>
              )}
              <span className="combobox__option-label">{item.label ?? item.value}</span>
            </li>
          );
        })
      ) : (
        <li className="combobox__empty" role="option" aria-selected="false" aria-disabled="true">
          {resolvedEmptyText}
        </li>
      )}
    </ul>
  );

  return (
    <div className="combobox" data-width={width}>
      {name && (
        <input
          type="hidden"
          name={name}
          value={selectedValue ?? ""}
          disabled={disabled || undefined}
        />
      )}

      <label {...api.labelProps} className="combobox__label">
        {label}
      </label>

      <div
        ref={controlRef}
        className={disabled ? "combobox__control combobox__control--disabled" : "combobox__control"}
      >
        {searchable ? (
          <span className="combobox__search" aria-hidden="true">
            <Icon size="100%">
              <circle cx="11" cy="11" r="8" />
              <line x1="21" y1="21" x2="16.65" y2="16.65" />
            </Icon>
          </span>
        ) : (
          (icon || selected?.icon) && (
            <span className="combobox__search" aria-hidden="true">
              {icon ??
                (selected?.icon && (
                  <Icon size="100%">
                    <path d={selected.icon} />
                  </Icon>
                ))}
            </span>
          )
        )}

        <input
          {...api.inputProps}
          ref={inputRef}
          className={
            searchable ? "combobox__input" : "combobox__input combobox__input--select-only"
          }
          type="text"
          placeholder={resolvedPlaceholder}
          readOnly={!searchable}
          disabled={disabled}
          value={inputValue}
          onChange={onInputChange}
          onPointerDown={onInputPointerDown}
        />

        {/* Invisible sizer: with width="wrap" the longest option (or the
            placeholder) sets a stable control width. */}
        <span className="combobox__sizer" aria-hidden="true">
          {items.map((item) => (
            <span key={item.value}>{item.label ?? item.value}</span>
          ))}
          <span>{resolvedPlaceholder}</span>
        </span>

        {/* The clear button always occupies its slot (hidden when empty) so the
            input width stays stable instead of jumping as text is typed. */}
        <button
          {...api.clearProps}
          className={clearHidden ? "combobox__clear combobox__clear--hidden" : "combobox__clear"}
          aria-label={resolvedClearLabel}
        >
          <Icon size="100%">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </Icon>
        </button>

        <button
          className="combobox__chevron"
          type="button"
          tabIndex={-1}
          aria-label={open ? "Close options" : "Show options"}
          disabled={disabled}
          onMouseDown={(event) => event.preventDefault()}
          onClick={toggle}
        >
          <Icon size="100%">
            <polyline points="6 9 12 15 18 9" />
          </Icon>
        </button>
      </div>

      {mounted && createPortal(listbox, document.body)}
    </div>
  );
}

// packages/svelte/src/lib/combobox/Combobox.svelte
<script lang="ts">
  /**
   * Combobox — a styled editable autocomplete (WAI-ARIA editable combobox).
   * Behaviour and accessibility (open/close, arrow navigation,
   * `aria-activedescendant`, selection, Escape) come from the headless combobox
   * (`@design-system/core`); this adapter owns filtering, popup positioning
   * (flip/shift via `@floating-ui/dom`), close-on-outside-pointer and keeping the
   * active option in view. DOM focus stays on the input.
   *
   * Pass `items` ({ value, label?, disabled? }) and an accessible `label`. Typing
   * filters the list; choosing an option fills the input. Themeable via
   * `--ds-combobox-*` (and the shared `--ds-select-*` listbox tokens).
   */
  import { combobox as core } from "@design-system/core";
  import { createCombobox, type ComboboxItem } from "./create-combobox";
  import { portal } from "../internal/portal";
  import Icon from "../icon/Icon.svelte";
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  /** Accessible name for the control. */
  export let label: string;
  /**
   * Options. Each may carry an optional leading `icon` (an SVG path `d`
   * string) shown before the label; with the search hidden, the control
   * mirrors the selected option's icon.
   */
  export let items: (ComboboxItem & { icon?: string })[];
  export let value: string | null = null;
  /**
   * With `searchable={false}` the text input becomes read-only and the list
   * always shows every option — a select-only combobox: the advanced Select
   * (styled popup, per-option icons) without the autocomplete.
   */
  export let searchable = true;
  /**
   * Width behaviour: `fixed` (default) uses `--ds-combobox-width` (16rem),
   * `wrap` fits the longest option, `fill` takes 100% of the container.
   */
  export let width: "wrap" | "fill" | "fixed" = "fixed";
  /** Input placeholder. Defaults to the i18n catalog's "Search…". */
  export let placeholder: string | undefined = undefined;
  export let disabled = false;
  /** Clear button accessible name. Defaults to the i18n catalog's "Clear". */
  export let clearLabel: string | undefined = undefined;
  /** Text shown when no option matches. Defaults to the i18n catalog's "No results". */
  export let emptyText: string | undefined = undefined;
  /** Form field name — the selected option's value is submitted under it. */
  export let name: string | undefined = undefined;
  export let onValueChange: ((value: string | null) => void) | undefined = undefined;
  export let onInputValueChange: ((text: string) => void) | undefined = undefined;

  const handleValueChange = (next: string | null) => {
    value = next;
    onValueChange?.(next);
  };
  const handleInputValueChange = (text: string) => {
    onInputValueChange?.(text);
  };

  const initialSelected = items.find((item) => item.value === value);
  const combobox = createCombobox({
    items,
    value,
    inputValue: initialSelected ? (initialSelected.label ?? initialSelected.value) : "",
    disabled,
    // Select-only mode never filters: the read-only input is a trigger, so the
    // list must always show every option (keyboard opening included).
    filter: searchable ? undefined : (all) => all,
    onValueChange: handleValueChange,
    onInputValueChange: handleInputValueChange,
  });
  const {
    state: comboboxState,
    controlAction,
    inputAction,
    listboxAction,
    optionAction,
    clearAction,
    items: visible,
    inputValue,
    value: selectedValue,
    open,
    openAll,
    setOpen,
    syncValue,
    syncInputValue,
    setItems,
    setDisabled,
  } = combobox;

  $: resolvedPlaceholder = placeholder ?? $t("combobox.placeholder");
  $: resolvedClearLabel = clearLabel ?? $t("combobox.clear");
  $: resolvedEmptyText = emptyText ?? $t("combobox.empty");

  $: selected = items.find((item) => item.value === value);
  $: selectedInputValue = selected ? (selected.label ?? selected.value) : "";
  $: syncValue(value);
  $: syncInputValue(selectedInputValue);
  $: setItems(items);
  $: setDisabled(disabled);
  $: iconByValue = new Map(items.map((item) => [item.value, item.icon]));
  $: hasIcons = items.some((item) => item.icon);

  // The chevron toggles the list open/closed (showing all options when opened),
  // so a selected value can be changed without clearing it first. iOS Safari can
  // synthesize a duplicate "ghost" click; ignore one that arrives right after the
  // last so the list doesn't open then immediately close.
  let lastToggle = -Infinity;
  function toggle(event: MouseEvent) {
    if (event.timeStamp - lastToggle < 350) return;
    lastToggle = event.timeStamp;
    if ($open) setOpen(false);
    else openAll();
  }
</script>

<div class="combobox" data-width={width}>
  {#if name}
    <input type="hidden" {name} value={$selectedValue ?? ""} />
  {/if}
  <!-- The ids are declared here as well as applied by the actions, so the
       server-rendered input already has a name and names its popup. -->
  <label
    class="combobox__label"
    for={core.inputId($comboboxState.id)}
    id={core.labelId($comboboxState.id)}>{label}</label
  >

  <div class="combobox__control" class:combobox__control--disabled={disabled} use:controlAction>
    {#if searchable}
      <span class="combobox__search" aria-hidden="true">
        <Icon size="100%">
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </Icon>
      </span>
    {:else if $$slots.icon || selected?.icon}
      <!-- No search: the leading slot (or the selected option's icon). -->
      <span class="combobox__search" aria-hidden="true">
        <slot name="icon">
          {#if selected?.icon}<Icon size="100%"><path d={selected.icon} /></Icon>{/if}
        </slot>
      </span>
    {/if}
    <input
      class="combobox__input"
      class:combobox__input--select-only={!searchable}
      type="text"
      placeholder={resolvedPlaceholder}
      readonly={!searchable}
      {disabled}
      value={$inputValue}
      use:inputAction
    />
    <!-- Invisible sizer: with width="wrap" the longest option (or the
         placeholder) sets a stable control width. -->
    <span class="combobox__sizer" aria-hidden="true">
      {#each items as item (item.value)}<span>{item.label ?? item.value}</span>{/each}
      <span>{resolvedPlaceholder}</span>
    </span>

    <!-- The clear button always occupies its slot (hidden when empty) so the
         input width stays stable instead of jumping as text is typed/cleared. -->
    <button
      class="combobox__clear"
      class:combobox__clear--hidden={!$inputValue || disabled}
      aria-label={resolvedClearLabel}
      tabindex={!$inputValue || disabled ? -1 : 0}
      aria-hidden={!$inputValue || disabled ? "true" : undefined}
      use:clearAction
    >
      <Icon size="100%">
        <line x1="18" y1="6" x2="6" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
      </Icon>
    </button>

    <button
      class="combobox__chevron"
      type="button"
      tabindex="-1"
      aria-label={$open ? $t("combobox.hide") : $t("combobox.show")}
      {disabled}
      on:mousedown|preventDefault
      on:click={toggle}
    >
      <Icon size="100%"><polyline points="6 9 12 15 18 9" /></Icon>
    </button>
  </div>

  <!-- The role is declared here as well as applied by the action: the options
       below carry theirs statically, and a role="option" outside a listbox is
       invalid markup before hydration. -->
  <ul
    class="combobox__listbox"
    id={core.listboxId($comboboxState.id)}
    role="listbox"
    aria-labelledby={core.labelId($comboboxState.id)}
    use:portal
    use:listboxAction
  >
    {#each $visible as item (item.value)}
      <li
        class="combobox__option"
        role="option"
        aria-selected={$selectedValue === item.value}
        use:optionAction={item.value}
      >
        <span class="combobox__check" aria-hidden="true">
          <Icon size="100%" strokeWidth={2.5}><polyline points="20 6 9 17 4 12" /></Icon>
        </span>
        {#if hasIcons}
          {@const icon = iconByValue.get(item.value)}
          <span class="combobox__option-icon" aria-hidden="true">
            {#if icon}
              <Icon size="100%"><path d={icon} /></Icon>
            {/if}
          </span>
        {/if}
        <span class="combobox__option-label">{item.label ?? item.value}</span>
      </li>
    {:else}
      <li class="combobox__empty" role="option" aria-selected="false" aria-disabled="true">
        {resolvedEmptyText}
      </li>
    {/each}
  </ul>
</div>

<style>
  .combobox {
    display: grid;
    gap: var(--ds-combobox-gap, 0.375rem);
    inline-size: var(--ds-combobox-width, 16rem);
    font: inherit;
    color: var(--ds-color-text, #0f172a);
  }
  .combobox:global([data-width="wrap"]) {
    inline-size: fit-content;
  }
  .combobox:global([data-width="fill"]) {
    inline-size: 100%;
  }

  .combobox__label {
    font-size: 0.875rem;
    font-weight: 600;
  }

  .combobox__control {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    box-sizing: border-box;
    padding-inline-end: 0.5rem;
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-combobox-radius, var(--ds-radius-control, 0.5rem));
    background: var(--ds-color-background, #fff);
    transition:
      border-color 120ms ease,
      box-shadow 120ms ease;
  }
  .combobox__control:focus-within {
    border-color: var(--ds-color-focus-ring, #2563eb);
    box-shadow: var(--ds-focus-ring-shadow);
  }
  .combobox__control--disabled {
    background: var(--ds-color-disabled, #e2e8f0);
    color: var(--ds-color-text-disabled, #94a3b8);
  }

  .combobox__search {
    display: inline-flex;
    flex: none;
    inline-size: 1.05em;
    block-size: 1.05em;
    margin-inline-start: 0.625rem;
    color: var(--ds-color-text-secondary, #57534e);
  }
  .combobox__input {
    flex: 1;
    min-inline-size: 0;
    padding: var(--ds-combobox-padding, 0.5rem 0.75rem);
    border: 0;
    background: transparent;
    color: inherit;
    font: inherit;
  }
  .combobox__input:focus {
    outline: none;
  }
  /* Select-only: the read-only input behaves as a trigger. */
  .combobox__input--select-only {
    cursor: pointer;
    font-weight: 500;
  }
  .combobox__input--select-only::placeholder {
    font-weight: 400;
  }
  /* Zero-height, invisible: contributes only its widest line for width="wrap". */
  .combobox__sizer {
    display: block;
    block-size: 0;
    overflow: hidden;
    visibility: hidden;
    padding-inline: var(--ds-combobox-sizer-padding, 0.75rem);
  }
  .combobox__sizer > span {
    display: block;
    white-space: nowrap;
  }

  .combobox__clear {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    inline-size: 1.25rem;
    block-size: 1.25rem;
    flex: none;
    padding: 0;
    border: 0;
    border-radius: var(--ds-radius-control, 0.5rem);
    background: transparent;
    color: var(--ds-color-text-secondary, #64748b);
    cursor: pointer;
  }
  .combobox__clear:hover {
    color: inherit;
  }
  /* Reserve the clear button's footprint when empty (no layout shift). */
  .combobox__clear--hidden {
    visibility: hidden;
    pointer-events: none;
  }
  .combobox__chevron {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    inline-size: 1.5rem;
    block-size: 1.5rem;
    flex: none;
    touch-action: manipulation;
    /* Breathing room from the clear button. */
    margin-inline-start: 0.25rem;
    padding: 0.2rem;
    border: 0;
    border-radius: var(--ds-radius-control, 0.5rem);
    background: transparent;
    color: var(--ds-color-text-secondary, #64748b);
    cursor: pointer;
    transition:
      background-color 120ms ease,
      color 120ms ease;
  }
  .combobox__chevron:hover:not(:disabled) {
    color: inherit;
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  .combobox__chevron:disabled {
    cursor: not-allowed;
  }

  .combobox__listbox {
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-select-z-index, 50);
    margin: 0;
    padding: var(--ds-select-listbox-padding, 0.25rem);
    list-style: none;
    max-block-size: var(--ds-select-max-height, 16rem);
    overflow-y: auto;
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-select-listbox-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(--ds-elevation-overlay, 0 10px 15px -3px rgb(0 0 0 / 0.1));
  }
  .combobox__listbox:global([data-state="closed"]) {
    display: none;
  }

  .combobox__option {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.4rem 0.5rem;
    border-radius: var(--ds-radius-control, 0.5rem);
    cursor: pointer;
    user-select: none;
  }
  .combobox__option:global([data-active]:not([data-state="selected"])) {
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  /* The selected option keeps a faint selection tint. */
  .combobox__option:global([data-state="selected"]) {
    background: color-mix(in srgb, var(--ds-color-selected, #7b52cc) 10%, transparent);
  }
  .combobox__option:global([data-disabled]) {
    color: var(--ds-color-text-disabled, #94a3b8);
    cursor: not-allowed;
  }
  .combobox__check {
    display: inline-flex;
    inline-size: 1rem;
    block-size: 1rem;
    flex: none;
    color: var(--ds-color-selected, #7b52cc);
    visibility: hidden;
  }
  /* Leading per-option icon (reserved width so labels align even when only
     some options carry an icon). */
  .combobox__option-icon {
    display: inline-flex;
    inline-size: var(--ds-combobox-option-icon-size, 1.1rem);
    block-size: var(--ds-combobox-option-icon-size, 1.1rem);
    flex: none;
    color: var(--ds-color-text-secondary, #57534e);
  }
  .combobox__option:global([data-state="selected"]) .combobox__check {
    visibility: visible;
  }
  .combobox__option:global([data-state="selected"]) .combobox__option-label {
    font-weight: 600;
  }

  .combobox__empty {
    padding: 0.5rem;
    color: var(--ds-color-text-secondary, #64748b);
    cursor: default;
  }
</style>
