// packages/react/src/avatar-group/AvatarGroup.tsx
import type { CSSProperties } from "react";
import { Avatar } from "../avatar/Avatar";
import { useI18n } from "../i18n/i18n";

export interface AvatarGroupItem {
  /** Required: the accessible name and the source of the initials. */
  name: string;
  /** Image URL; falls back to the initials when absent or it fails to load. */
  src?: string;
  /** Accessible name override; defaults to `name`. */
  alt?: string;
  /** Optional background for the initials avatar (any CSS colour). */
  color?: string;
}

export interface AvatarGroupProps {
  /** The people in the group. */
  items: AvatarGroupItem[];
  /** Maximum avatars to show before the rest collapse into a "+N" chip. */
  max?: number;
  size?: "sm" | "md" | "lg";
  shape?: "circle" | "square";
  /** Accessible name for the group. */
  label: string;
}

const UNSAFE_COLOR = /[;{}]/;

// The colour is data, so it is one value only: anything that could close the
// declaration and start another is dropped, as in the other adapters.
const colorStyle = (color: string | undefined): CSSProperties | undefined =>
  color && !UNSAFE_COLOR.test(color) ? ({ "--ds-avatar-bg": color } as CSSProperties) : undefined;

/**
 * AvatarGroup: a row of overlapping avatars (a team, attendees,
 * collaborators). Shows at most `max` and collapses the rest into a "+N"
 * chip.
 *
 * Accessibility: the row is a labelled group, each avatar keeps its own name,
 * and the chip is named from the catalog ("N more").
 *
 * Overlap, ring, size and shape are themeable (`--ds-avatar-group-*`),
 * inheriting the `Avatar` tokens.
 */
export function AvatarGroup({
  items,
  max = 4,
  size = "md",
  shape = "circle",
  label,
}: AvatarGroupProps) {
  const { t } = useI18n();
  const visible = items.slice(0, max);
  const overflow = items.length - visible.length;
  return (
    <div
      className="avatar-group"
      data-size={size}
      data-shape={shape}
      role="group"
      aria-label={label}
    >
      {visible.map((item, index) => (
        // Items carry no id and two people may share a name, so the position
        // is part of the key; the name remounts the avatar when the person
        // changes.
        <span
          key={`${index}:${item.name}`}
          className="avatar-group__item"
          // The shared sheet reads the tint from this custom property.
          style={colorStyle(item.color)}
        >
          <Avatar name={item.name} src={item.src} alt={item.alt} size={size} shape={shape} />
        </span>
      ))}
      {overflow > 0 ? (
        <span
          className="avatar-group__item avatar-group__overflow"
          data-size={size}
          data-shape={shape}
          role="img"
          aria-label={t("avatarGroup.more", { count: overflow })}
        >
          <span aria-hidden="true">+{overflow}</span>
        </span>
      ) : null}
    </div>
  );
}

// packages/svelte/src/lib/avatar-group/AvatarGroup.svelte
<script module lang="ts">
  export interface AvatarGroupItem {
    /** Required: accessible name + initials fallback. */
    name: string;
    /** Image URL; falls back to initials when absent or it fails to load. */
    src?: string;
    /** Accessible name override; defaults to `name`. */
    alt?: string;
    /** Optional background tint for the initials avatar (any CSS color). */
    color?: string;
  }
</script>

<script lang="ts">
  /**
   * AvatarGroup — a row of overlapping avatars (a team, attendees, collaborators).
   * Caps the visible count at `max` and renders a "+N" overflow chip for the rest.
   *
   * Accessibility:
   * - The row is a labelled group (`role="group"` + `label`) so assistive tech
   *   announces what the cluster represents.
   * - Each avatar keeps its own accessible name (via `Avatar`); the overflow chip
   *   exposes how many more there are ("N more").
   *
   * Overlap, ring, size and shape are themeable CSS custom properties
   * (`--ds-avatar-group-*`), inheriting the `Avatar` tokens.
   */
  import Avatar from "../avatar/Avatar.svelte";

  /** The people in the group. */
  export let items: AvatarGroupItem[];
  /** Maximum avatars to show before collapsing the rest into a "+N" chip. */
  export let max = 4;
  export let size: "sm" | "md" | "lg" = "md";
  export let shape: "circle" | "square" = "circle";
  /** Accessible name for the group (announced by screen readers). */
  export let label: string;

  $: visible = items.slice(0, max);
  $: overflow = Math.max(0, items.length - visible.length);

  // The colour is data, so it is one value only: anything that could close the
  // declaration and start another is dropped (server output is a plain string).
  const colorOf = (item: AvatarGroupItem) =>
    item.color && !/[;{}]/.test(item.color) ? item.color : undefined;
</script>

<div class="avatar-group" data-size={size} data-shape={shape} role="group" aria-label={label}>
  <!-- Items carry no id and two people may share a name, so the position is
       part of the key; the name remounts the avatar when the person changes. -->
  {#each visible as item, index (`${index}:${item.name}`)}
    <span class="avatar-group__item" style:--ds-avatar-bg={colorOf(item)}>
      <Avatar name={item.name} src={item.src} alt={item.alt} {size} {shape} />
    </span>
  {/each}
  {#if overflow > 0}
    <span
      class="avatar-group__item avatar-group__overflow"
      data-size={size}
      data-shape={shape}
      role="img"
      aria-label={`${overflow} more`}
    >
      <span aria-hidden="true">+{overflow}</span>
    </span>
  {/if}
</div>

<style>
  .avatar-group {
    display: inline-flex;
    flex-direction: row;
    align-items: center;
  }

  /* Overlap each avatar over its predecessor; a ring separates them. */
  .avatar-group__item {
    display: inline-flex;
    border-radius: inherit;
    /* No separator ring by default — avatars overlap directly. Opt into one
       (e.g. for photo avatars) by setting --ds-avatar-group-ring-width to a
       non-zero value; the ring color should match the background the group sits
       on so it only separates avatars and stays invisible at the outer edge. */
    box-shadow: 0 0 0 var(--ds-avatar-group-ring-width, 0)
      var(--ds-avatar-group-ring-color, var(--ds-color-background, #fff));
  }
  .avatar-group__item:not(:first-child) {
    margin-inline-start: var(--ds-avatar-group-overlap, -0.625rem);
  }

  /* Stack order: earlier avatars sit above later ones so the overlap reads
     left-to-right; the overflow chip stays on top. */
  .avatar-group__item {
    position: relative;
    z-index: 0;
  }

  .avatar-group__overflow {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex: none;
    inline-size: var(--ds-avatar-size, 2.5rem);
    block-size: var(--ds-avatar-size, 2.5rem);
    font-size: 0.8125rem;
    font-weight: 600;
    line-height: 1;
    user-select: none;
    background: var(--ds-avatar-group-overflow-bg, var(--ds-color-neutral-surface, #f4f2ef));
    color: var(--ds-avatar-group-overflow-color, var(--ds-color-text-secondary, #524c44));
  }
  .avatar-group__overflow:global([data-size="sm"]) {
    inline-size: var(--ds-avatar-size, 2rem);
    block-size: var(--ds-avatar-size, 2rem);
    font-size: 0.6875rem;
  }
  .avatar-group__overflow:global([data-size="lg"]) {
    inline-size: var(--ds-avatar-size, 3.5rem);
    block-size: var(--ds-avatar-size, 3.5rem);
    font-size: 1rem;
  }
  .avatar-group__overflow:global([data-shape="circle"]) {
    border-radius: 50%;
  }
  .avatar-group__overflow:global([data-shape="square"]) {
    border-radius: var(--ds-avatar-radius, var(--ds-radius-control, 0.5rem));
  }
</style>
