// packages/svelte/src/lib/time-field/TimeField.svelte
<script context="module" lang="ts">
  let timeFieldId = 0;
</script>

<script lang="ts">
  /**
   * TimeField — a styled segmented time input (hour : minute [: second] [AM/PM]).
   * Each segment is a `role="spinbutton"` driven by the headless time field
   * (`@design-system/core`): ArrowUp/Down increment/decrement (wrapping),
   * Left/Right move between segments, digits type with auto-advance, Backspace
   * clears, and A/P set the period in 12-hour mode. The value is the canonical
   * 24-hour ISO string (`HH:mm` or `HH:mm:ss`). Themeable via `--ds-time-field-*`.
   */
  import {
    createTimeField,
    type HourCycle,
    type TimeSegmentType,
    type TimeValueError,
  } from "./create-time-field";
  import { timeField as core } from "@design-system/core";
  import { getI18n } from "../i18n/create-i18n";
  import { get } from "svelte/store";

  const { t } = getI18n();

  export let value: string | null = null;
  export let hourCycle: HourCycle = 24;
  export let withSeconds = false;
  export let disabled = false;
  /** Domain-level invalid state. Structural time errors are detected automatically. */
  export let invalid = false;
  /** Visible, actionable error text supplied by the application. */
  export let error: string | undefined = undefined;
  /** Accessible label for the whole field. */
  export let label: string | undefined = undefined;
  /** Form field name — the formatted time (`HH:mm[:ss]`) is submitted under it (via a hidden input). */
  export let name: string | undefined = undefined;
  export let onValueChange: ((value: string | null) => void) | undefined = undefined;
  /** Called when the user finishes editing: focus leaves the field, or Enter. */
  export let onValueCommit: ((value: string | null) => void) | undefined = undefined;
  /** Earliest acceptable time (`"HH:mm[:ss]"`), inclusive. */
  export let min: string | undefined = undefined;
  /** Latest acceptable time (`"HH:mm[:ss]"`), inclusive. */
  export let max: string | undefined = undefined;
  /** Called when structural validation changes; `null` means no structural error. */
  export let onValidationChange: ((error: TimeValueError | null) => void) | undefined = undefined;

  const translate = get(t);
  const id = `ds-time-field-${++timeFieldId}`;
  const errorId = `${id}-error`;
  const field = createTimeField({
    id,
    value,
    hourCycle,
    withSeconds,
    min,
    max,
    disabled,
    invalid: invalid || Boolean(error),
    describedBy: errorId,
    messages: {
      hour: translate("timeField.hour"),
      minute: translate("timeField.minute"),
      second: translate("timeField.second"),
      dayPeriod: translate("timeField.dayPeriod"),
      empty: translate("timeField.empty"),
    },
    onValueChange,
    onValueCommit,
    onValidationChange,
  });
  const { state: tfState, api, rootAction, segmentAction, fieldAction } = field;

  $: field.syncConfig({ min, max, hourCycle, withSeconds });

  $: segments = core.segments($tfState.hourCycle, $tfState.withSeconds);
  const isEmpty = (seg: TimeSegmentType, text: string) =>
    text === "hh" ||
    text === "mm" ||
    text === "ss" ||
    (seg === "dayPeriod" && $tfState.parts.dayPeriod == null);

  const messageFor = (validationError: TimeValueError | null) => {
    switch (validationError) {
      case "invalid-format":
        return $t("timeField.invalidFormat");
      case "out-of-range":
        return $t("timeField.outOfRange");
      case "seconds-required":
        return $t("timeField.secondsRequired");
      case "seconds-not-allowed":
        return $t("timeField.secondsNotAllowed");
      case "range-underflow":
        return $t("timeField.rangeUnderflow", { min: min ?? "" });
      case "range-overflow":
        return $t("timeField.rangeOverflow", { max: max ?? "" });
      default:
        return undefined;
    }
  };

  $: validationMessage = error ?? messageFor($api.validationError);
</script>

<div class="time-field-control">
  <div
    class="time-field"
    class:time-field--disabled={disabled}
    class:time-field--invalid={invalid || Boolean(validationMessage)}
    use:rootAction
    use:fieldAction
    aria-label={label ?? $t("timeField.label")}
    aria-disabled={disabled || undefined}
    aria-invalid={invalid || Boolean(validationMessage) || undefined}
    aria-describedby={validationMessage ? errorId : undefined}
  >
    {#if name}
      <input type="hidden" {name} value={$api.value ?? ""} />
    {/if}
    {#each segments as seg, i (seg)}
      {#if i > 0}
        <span class="time-field__separator" aria-hidden="true"
          >{seg === "dayPeriod" ? " " : ":"}</span
        >
      {/if}
      {@const text = $api.getSegmentText(seg)}
      <!-- segmentAction applies role="spinbutton" at runtime, which the
         compiler cannot see in the static markup. -->
      <!-- svelte-ignore a11y-no-noninteractive-tabindex -->
      <span
        class="time-field__segment"
        class:time-field__segment--placeholder={isEmpty(seg, text)}
        class:time-field__segment--period={seg === "dayPeriod"}
        use:segmentAction={seg}
        tabindex={disabled ? -1 : 0}
      >
        {text}
      </span>
    {/each}
  </div>
  <p id={errorId} class="time-field__error" aria-live="polite" hidden={!validationMessage}>
    {validationMessage ?? ""}
  </p>
</div>

<style>
  .time-field-control {
    display: inline-flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 0.25rem;
  }
  .time-field {
    display: inline-flex;
    align-items: center;
    gap: 0.05rem;
    padding: 0.4rem 0.6rem;
    font: inherit;
    font-variant-numeric: tabular-nums;
    color: var(--ds-color-text, #282420);
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-control-border, #757067);
    border-radius: var(--ds-radius-control, 0.5rem);
  }
  .time-field:focus-within {
    border-color: var(--ds-color-focus-ring, #8e6cd4);
    box-shadow: var(--ds-focus-ring-shadow);
  }
  .time-field--disabled {
    opacity: 0.55;
  }
  .time-field--invalid {
    border-color: var(--ds-color-danger, #be3b50);
  }

  .time-field__separator {
    color: var(--ds-color-text-secondary, #524c44);
  }
  .time-field__segment {
    padding: 0.05rem 0.2rem;
    border-radius: var(--ds-radius-control, 0.5rem);
    cursor: text;
    outline: none;
    min-inline-size: 1.4em;
    text-align: center;
    white-space: nowrap;
    /* contenteditable, but editing is intercepted — hide the text caret. */
    caret-color: transparent;
  }
  .time-field__segment--period {
    min-inline-size: 2em;
  }
  /* Highlight the active segment on any focus (including touch), so it's always
     clear which part is being edited — `:focus-visible` alone misses touch. */
  .time-field__segment:focus {
    background: var(--ds-time-field-focus-bg, var(--ds-color-secondary, #7a52cc));
    color: var(--ds-time-field-focus-text, #fff);
  }
  .time-field__segment--placeholder {
    color: var(--ds-color-text-secondary, #524c44);
  }
  .time-field__error {
    margin: 0;
    color: var(--ds-color-danger, #be3b50);
    font-size: 0.875rem;
  }
</style>

// packages/react/src/time-field/TimeField.tsx
import { i18n as coreI18n } from "@design-system/core";
import { Fragment, useId, useRef } from "react";
import { useI18n } from "../i18n/i18n";
import type { MessageKey } from "../i18n/messages";
import { cx } from "../internal/cx";
import { useTimeField, type HourCycle, type TimeValueError } from "./use-time-field";

export interface TimeFieldProps {
  /** Initial (uncontrolled) or current (controlled) value, `HH:mm[:ss]` (24h), or `null`. */
  value?: string | null;
  /** 12 or 24 hours. Defaults to the provider locale's preference. */
  hourCycle?: HourCycle;
  /** Include a seconds segment. */
  withSeconds?: boolean;
  disabled?: boolean;
  /** Domain-level invalid state. Structural time errors are detected automatically. */
  invalid?: boolean;
  /** Visible, actionable error text supplied by the application. */
  error?: string;
  /** Accessible label for the whole field. Defaults to the catalog's. */
  label?: string;
  /** Form field name; the canonical time (`HH:mm[:ss]`) is submitted under it. */
  name?: string;
  /** Id of the owning form when the field renders outside of it. */
  form?: string;
  /** Earliest acceptable time (`HH:mm[:ss]`), inclusive. Reported, never enforced. */
  min?: string;
  /** Latest acceptable time (`HH:mm[:ss]`), inclusive. Reported, never enforced. */
  max?: string;
  /** Called with the canonical value when every required segment is filled, else `null`. */
  onValueChange?: (value: string | null) => void;
  /** Called when the user finishes editing: focus leaves the field, or Enter. */
  onValueCommit?: (value: string | null) => void;
  /** Called when an edit changes the structural error; `null` means none. */
  onValidationChange?: (error: TimeValueError | null) => void;
}

/**
 * The hour cycle a locale prefers. Read from a formatter's resolved options,
 * which every runtime answers alike, so the server and the browser render
 * the same segments.
 */
function localeHourCycle(locale: string): HourCycle {
  const cycle = coreI18n.dateTimeFormat(locale, { hour: "numeric" }).resolvedOptions().hourCycle;
  return cycle === "h11" || cycle === "h12" ? 12 : 24;
}

/** The catalog message for each way a time can be wrong. */
const MESSAGES: Record<TimeValueError, MessageKey> = {
  "invalid-format": "timeField.invalidFormat",
  "out-of-range": "timeField.outOfRange",
  "seconds-required": "timeField.secondsRequired",
  "seconds-not-allowed": "timeField.secondsNotAllowed",
  "range-underflow": "timeField.rangeUnderflow",
  "range-overflow": "timeField.rangeOverflow",
};

/**
 * TimeField: a segmented time input (hour : minute [: second] [AM/PM]). Each
 * segment is a `role="spinbutton"` driven by the headless time field
 * (`useTimeField`): ArrowUp and ArrowDown step with wrapping, ArrowLeft and
 * ArrowRight move between segments, digits type with auto-advance, Backspace
 * clears, A and P set the period, Escape puts back the last finished value.
 * The value is the canonical 24-hour string (`HH:mm` or `HH:mm:ss`), `null`
 * while a segment is empty. The hour cycle follows the provider's locale
 * unless `hourCycle` says otherwise; labels come from the catalog.
 *
 * With `name`, a hidden input submits the value, and a form reset puts back
 * the current default without reporting (ADR 0012). Inside a disabled
 * `<fieldset>` the field is disabled too. A time outside `min` and `max` is
 * reported, never corrected. Themeable via `--ds-time-field-*`.
 */
export function TimeField({
  value = null,
  hourCycle,
  withSeconds = false,
  disabled = false,
  invalid = false,
  error,
  label,
  name,
  form,
  min,
  max,
  onValueChange,
  onValueCommit,
  onValidationChange,
}: TimeFieldProps) {
  const { t, locale } = useI18n();
  const errorId = `ds-time-field-${useId()}-error`;
  const rootRef = useRef<HTMLDivElement>(null);
  const hiddenRef = useRef<HTMLInputElement>(null);

  const api = useTimeField({
    value,
    hourCycle: hourCycle ?? localeHourCycle(locale),
    withSeconds,
    min,
    max,
    disabled,
    invalid: invalid || Boolean(error),
    describedBy: errorId,
    messages: {
      hour: t("timeField.hour"),
      minute: t("timeField.minute"),
      second: t("timeField.second"),
      dayPeriod: t("timeField.dayPeriod"),
      empty: t("timeField.empty"),
    },
    onValueChange,
    onValueCommit,
    onValidationChange,
    rootRef,
    controlRef: hiddenRef,
  });

  const message =
    error ??
    (api.validationError
      ? t(MESSAGES[api.validationError], { min: min ?? "", max: max ?? "" })
      : undefined);
  const isInvalid = invalid || Boolean(message);

  return (
    <div className="time-field-control">
      <div
        {...api.rootProps}
        ref={rootRef}
        className={cx(
          "time-field",
          api.disabled && "time-field--disabled",
          isInvalid && "time-field--invalid",
        )}
        aria-label={label ?? t("timeField.label")}
        aria-invalid={isInvalid || undefined}
        aria-describedby={message ? errorId : undefined}
      >
        {/* Always present: it tells a form reset which form the field is in,
            and a disabled fieldset whether it disables the field. Only a
            named input is submitted, and a disabled one sends nothing. */}
        <input
          ref={hiddenRef}
          type="hidden"
          name={name}
          form={form}
          value={api.value ?? ""}
          disabled={disabled || undefined}
        />
        {api.segments.map((seg, index) => (
          <Fragment key={seg}>
            {index > 0 ? (
              <span className="time-field__separator" aria-hidden="true">
                {seg === "dayPeriod" ? " " : ":"}
              </span>
            ) : null}
            <span
              {...api.getSegmentProps(seg)}
              className={cx(
                "time-field__segment",
                api.isPlaceholder(seg) && "time-field__segment--placeholder",
                seg === "dayPeriod" && "time-field__segment--period",
              )}
              // The core intercepts every edit; React keeps the text.
              suppressContentEditableWarning
            >
              {api.getSegmentText(seg)}
            </span>
          </Fragment>
        ))}
      </div>
      <p id={errorId} className="time-field__error" aria-live="polite" hidden={!message}>
        {message ?? ""}
      </p>
    </div>
  );
}
