// packages/react/src/date-picker/DatePicker.tsx
import { i18n as coreI18n } from "@design-system/core";
import { useRef } from "react";
import { Calendar, type CalendarEvent } from "../calendar/Calendar";
import type { WeekStart } from "../calendar/use-calendar";
import { useI18n } from "../i18n/i18n";
import { asDate, localDate } from "../internal/date";
import { useResettable } from "../internal/form-reset";
import { PickerField } from "../internal/picker-field";

/** The `Intl` date style the field shows the value in. */
export type DateStyle = "full" | "long" | "medium" | "short";

export interface DatePickerProps {
  /** Initial (uncontrolled) or current (controlled) date, ISO `YYYY-MM-DD`, or `null`. */
  value?: string | null;
  /** Earliest selectable date (ISO), inclusive. */
  min?: string;
  /** Latest selectable date (ISO), inclusive. */
  max?: string;
  /** First day of the week, 0 = Sunday to 6. */
  weekStartsOn?: WeekStart;
  /** BCP-47 locale for the field and the calendar. Defaults to the provider's locale. */
  locale?: string;
  /** `Intl` date style for the field. */
  dateStyle?: DateStyle;
  /** Accessible label for the field. Defaults to the catalog's. */
  label?: string;
  /** Placeholder while empty. Defaults to the catalog's. */
  placeholder?: string;
  disabled?: boolean;
  /** Show a clear button when a date is selected. */
  clearable?: boolean;
  /** Appointment dots, forwarded to the calendar. */
  events?: CalendarEvent[];
  /** Per-day price labels, forwarded to the calendar. */
  prices?: Record<string, string>;
  /** Form field name; the ISO date is submitted under it. */
  name?: string;
  /** Called when the user picks or clears a date. */
  onValueChange?: (value: string | null) => void;
}

/**
 * DatePicker: a date field that opens a `Calendar` in a popup. The readonly
 * field is a combobox that opens a dialog popup; a click, Enter, Space or
 * ArrowDown opens it and focus moves to the calendar's focused day, where the
 * WAI-ARIA date grid keys apply. Picking a day fills the field, closes the
 * popup and puts focus back on the field; Escape does the same without a pick.
 *
 * The field shows the date formatted with `Intl` (`dateStyle`); the value is
 * the ISO `YYYY-MM-DD` string, a controllable mirror (ADR 0011). With `name`,
 * a hidden input submits it, and a form reset puts back the current default
 * without reporting (ADR 0012). `min`, `max`, `events` and `prices` are
 * forwarded to the calendar. Themeable via `--ds-date-picker-*` and the
 * calendar's `--ds-calendar-*`.
 */
export function DatePicker({
  value = null,
  min,
  max,
  weekStartsOn = 1,
  locale,
  dateStyle = "medium",
  label,
  placeholder,
  disabled = false,
  clearable = false,
  events,
  prices,
  name,
  onValueChange,
}: DatePickerProps) {
  const i18n = useI18n();
  const { t } = i18n;
  const rootRef = useRef<HTMLDivElement>(null);
  const [current, setCurrent] = useResettable(asDate(value), onValueChange, rootRef);
  const format = coreI18n.dateTimeFormat(locale ?? i18n.locale, { dateStyle });
  const fieldLabel = label ?? t("datePicker.label");

  return (
    <PickerField
      rootRef={rootRef}
      label={fieldLabel}
      placeholder={placeholder ?? t("datePicker.placeholder")}
      clearLabel={t("datePicker.clear")}
      text={current ? format.format(localDate(current)) : ""}
      active={current != null}
      clearable={clearable && current != null}
      disabled={disabled}
      fields={[{ name, value: current }]}
      onClear={() => setCurrent(null)}
    >
      {(done) => (
        <Calendar
          value={current}
          focusedDate={current ?? undefined}
          min={min}
          max={max}
          weekStartsOn={weekStartsOn}
          locale={locale}
          events={events}
          prices={prices}
          label={fieldLabel}
          onValueChange={(iso) => {
            // Closed before the pick is reported (ADR 0011).
            done();
            setCurrent(iso);
          }}
        />
      )}
    </PickerField>
  );
}

// packages/svelte/src/lib/date-picker/DatePicker.svelte
<script lang="ts">
  /**
   * DatePicker — a date input that opens a `Calendar` in a popover. Composes the
   * headless popover (`@design-system/core`, via `createPopover`) with the
   * styled `Calendar`: the readonly field is the trigger (click / Enter / Space
   * to open), focus moves into the calendar, picking a day fills the field and
   * closes the popover, and Escape returns focus to the field.
   *
   * The field shows the selected date formatted with `Intl` (`dateStyle`); the
   * value is the ISO `YYYY-MM-DD` string. `min`/`max`, `events` (appointment
   * dots) and `prices` are forwarded to the calendar. Themeable via
   * `--ds-date-picker-*` and the calendar's `--ds-calendar-*`.
   */
  import { createPopover } from "../popover/create-popover";
  import Calendar, { type CalendarEvent } from "../calendar/Calendar.svelte";
  import type { WeekStart } from "../calendar/create-calendar";
  import Icon from "../icon/Icon.svelte";
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  export let value: string | null = null;
  export let min: string | undefined = undefined;
  export let max: string | undefined = undefined;
  export let weekStartsOn: WeekStart = 1;
  export let locale: string | undefined = undefined;
  /** Intl date style for the field display. */
  export let dateStyle: "full" | "long" | "medium" | "short" = "medium";
  /** Accessible label for the field (required for a meaningful control). */
  export let label: string | undefined = undefined;
  export let placeholder: string | undefined = undefined;
  export let disabled = false;
  /** Show a clear button when a date is selected. */
  export let clearable = false;
  /** Forwarded to the calendar. */
  export let events: CalendarEvent[] = [];
  export let prices: Record<string, string> = {};

  /** Form field name — the selected ISO date is submitted under it (via a hidden input). */
  export let name: string | undefined = undefined;
  export let onValueChange: ((value: string | null) => void) | undefined = undefined;

  const popover = createPopover({ placement: "bottom-start" });
  const { triggerAction, contentAction, open: isOpen, setOpen } = popover;

  const dt = (iso: string) => new Date(`${iso}T00:00:00`);
  $: displayFmt = new Intl.DateTimeFormat(locale, { dateStyle });
  $: displayValue = value ? displayFmt.format(dt(value)) : "";

  const pick = (iso: string) => {
    value = iso;
    onValueChange?.(iso);
    setOpen(false);
  };

  const clear = () => {
    value = null;
    onValueChange?.(null);
  };
</script>

<div class="date-picker" class:date-picker--disabled={disabled}>
  {#if name}
    <input type="hidden" {name} value={value ?? ""} />
  {/if}
  <div class="date-picker__field">
    <span class="date-picker__icon" aria-hidden="true">
      <Icon size="1.1rem">
        <rect x="3" y="4" width="18" height="18" rx="2" />
        <line x1="16" y1="2" x2="16" y2="6" />
        <line x1="8" y1="2" x2="8" y2="6" />
        <line x1="3" y1="10" x2="21" y2="10" />
      </Icon>
    </span>
    <input
      class="date-picker__input"
      type="text"
      role="combobox"
      readonly
      {disabled}
      aria-label={label ?? $t("datePicker.label")}
      placeholder={placeholder ?? $t("datePicker.placeholder")}
      value={displayValue}
      use:triggerAction
    />
    {#if clearable && value && !disabled}
      <button
        class="date-picker__clear"
        type="button"
        aria-label={$t("datePicker.clear")}
        on:click={clear}
      >
        <Icon size="0.9rem"
          ><line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" /></Icon
        >
      </button>
    {/if}
  </div>

  {#if $isOpen}
    <div class="date-picker__popover" use:contentAction>
      <Calendar
        {value}
        focusedDate={value ?? undefined}
        {min}
        {max}
        {weekStartsOn}
        {locale}
        {events}
        {prices}
        onValueChange={pick}
        label={label ?? $t("datePicker.label")}
      />
    </div>
  {/if}
</div>

<style>
  .date-picker {
    display: inline-flex;
    flex-direction: column;
    font: inherit;
    color: var(--ds-color-text, #0f172a);
  }
  .date-picker__field {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding-inline: 0.6rem;
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-radius-control, 0.5rem);
  }
  .date-picker__field:focus-within {
    border-color: var(--ds-color-focus-ring, #2563eb);
    box-shadow: 0 0 0 var(--ds-focus-ring-width, 2px) var(--ds-color-focus-ring, #2563eb);
  }
  .date-picker--disabled .date-picker__field {
    opacity: 0.55;
  }
  .date-picker__icon {
    display: inline-flex;
    color: var(--ds-color-text-secondary, #64748b);
  }
  .date-picker__input {
    flex: 1;
    min-inline-size: 8rem;
    padding-block: 0.5rem;
    font: inherit;
    color: inherit;
    background: none;
    border: 0;
    outline: none;
    cursor: pointer;
  }
  .date-picker__input::placeholder {
    color: var(--ds-color-text-secondary, #94a3b8);
  }
  .date-picker__input:disabled {
    cursor: not-allowed;
  }
  .date-picker__clear {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.2rem;
    color: var(--ds-color-text-secondary, #64748b);
    background: none;
    border: 0;
    border-radius: 50%;
    cursor: pointer;
  }
  .date-picker__clear:hover {
    background: var(--ds-color-neutral-surface, #f1f5f9);
  }
  .date-picker__clear:focus-visible {
    outline: var(--ds-focus-ring-width, 2px) solid var(--ds-color-focus-ring, #2563eb);
    outline-offset: 1px;
  }

  .date-picker__popover {
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-popover-z-index, 50);
    box-sizing: border-box;
    inline-size: max-content;
    max-inline-size: min(92vw, 22rem);
    padding: var(--ds-popover-padding, 0.875rem 1rem);
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-popover-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(
      --ds-elevation-overlay,
      0 10px 15px -3px rgb(0 0 0 / 0.1),
      0 4px 6px -4px rgb(0 0 0 / 0.1)
    );
  }
</style>
