// packages/react/src/rating-group/RatingGroup.tsx
import { useId, useRef, useState } from "react";
import { useI18n } from "../i18n/i18n";
import { Icon } from "../icon/Icon";
import { cx } from "../internal/cx";
import { useRatingGroup } from "./use-rating-group";

export interface RatingGroupProps {
  /** Accessible name for the rating group (required). */
  label: string;
  /** Number of stars. */
  max?: number;
  /** Selected rating (1..max), or null. */
  value?: number | null;
  disabled?: boolean;
  /** Form field name; the rating is submitted under it. */
  name?: string;
  /** Called whenever the rating changes. */
  onValueChange?: (value: number) => void;
}

const STAR = (
  <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
);

/**
 * RatingGroup — a star rating built on native `<input type="radio">` stars
 * sharing a `name`. The browser provides single selection, roving tabindex,
 * arrow-key navigation, focus and form participation; this layer renders the
 * stars and adds a pointer-hover preview.
 *
 * The group needs an accessible name via `label`; each star is a radio
 * labelled "N star(s)" from the catalog. Themeable via `--ds-rating-*`.
 */
export function RatingGroup({
  label,
  max = 5,
  value = null,
  disabled = false,
  name,
  onValueChange,
}: RatingGroupProps) {
  const labelId = `ds-rating-${useId()}-label`;
  const rootRef = useRef<HTMLDivElement>(null);
  const { t } = useI18n();
  const {
    items,
    api,
    value: rating,
  } = useRatingGroup({
    max,
    value,
    disabled,
    name,
    onValueChange,
    rootRef,
  });
  // While hovering, stars up to `hovered` show a grey preview; otherwise the
  // selected stars show the selection color.
  const [hovered, setHovered] = useState(0);

  return (
    <div className="rating-field">
      <span className="rating__label" id={labelId}>
        {label}
      </span>
      <div
        ref={rootRef}
        {...api.rootProps}
        className={cx("rating", disabled && "rating--disabled")}
        aria-labelledby={labelId}
        onPointerLeave={() => setHovered(0)}
      >
        {items.map((item) => (
          <label
            key={item.value}
            className={cx(
              "rating__star",
              !hovered && item.position <= (rating ?? 0) && "rating__star--filled",
              hovered > 0 && item.position <= hovered && "rating__star--preview",
            )}
            onPointerEnter={() => {
              if (!disabled) setHovered(item.position);
            }}
          >
            <input
              {...api.getItemProps(item.value)}
              className="rating__input"
              aria-label={t("rating.stars", { count: item.position })}
            />
            <Icon size="var(--ds-rating-size, 1.5rem)">{STAR}</Icon>
          </label>
        ))}
      </div>
    </div>
  );
}

// packages/svelte/src/lib/rating-group/RatingGroup.svelte
<script lang="ts">
  /**
   * RatingGroup — a star rating built on **native** `<input type="radio">`
   * stars sharing a `name`. The browser provides single selection, roving
   * tabindex, arrow-key navigation, focus and form participation; this layer
   * renders the stars and adds a pointer-hover preview.
   *
   * The group needs an accessible name via `label`; each star is a radio
   * labelled "N star(s)". Themeable via `--ds-rating-*`.
   */
  import { getI18n } from "../i18n/create-i18n";
  import { createRatingGroup } from "./create-rating-group";
  import Icon from "../icon/Icon.svelte";
  import { stableId } from "../internal/stable-id";

  /** Accessible name for the rating group. */
  export let label: string;
  /** Number of stars. */
  export let max = 5;
  /** Selected rating (1..max), or null. */
  export let value: number | null = null;
  export let disabled = false;
  /** Form field name — the rating is submitted under it. */
  export let name: string | undefined = undefined;
  /** Called whenever the rating changes. */
  export let onValueChange: ((value: number) => void) | undefined = undefined;

  const rating = createRatingGroup({ max, value, disabled, name, onValueChange });
  const { items, setValue, name: groupName, value: selected } = rating;

  // While hovering, stars up to `hovered` show a grey preview; otherwise the
  // selected stars show the selection color.
  let hovered = 0;

  const labelId = stableId("ds-rating");
  const { t } = getI18n();
  const starLabel = (n: number, translate: typeof $t) => translate("rating.stars", { count: n });
</script>

<div class="rating-field">
  <span class="rating__label" id={labelId}>{label}</span>
  <!-- The native radios own focus and the roving tabindex, so the group
       itself takes none. -->
  <!-- svelte-ignore a11y-interactive-supports-focus -->
  <div
    class="rating"
    class:rating--disabled={disabled}
    role="radiogroup"
    aria-labelledby={labelId}
    aria-orientation="horizontal"
    on:pointerleave={() => (hovered = 0)}
  >
    {#each items as item (item.value)}
      <label
        class="rating__star"
        class:rating__star--filled={!hovered && item.position <= ($selected ?? 0)}
        class:rating__star--preview={hovered > 0 && item.position <= hovered}
        on:pointerenter={() => {
          if (!disabled) hovered = item.position;
        }}
      >
        <input
          class="rating__input"
          type="radio"
          name={groupName}
          value={item.value}
          checked={$selected === item.position}
          {disabled}
          aria-label={starLabel(item.position, $t)}
          on:change={() => setValue(item.position)}
        />
        <Icon size="var(--ds-rating-size, 1.5rem)">
          <polygon
            points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"
          />
        </Icon>
      </label>
    {/each}
  </div>
</div>

<style>
  .rating-field {
    display: grid;
    gap: var(--ds-rating-label-gap, 0.5rem);
    font: inherit;
    color: var(--ds-color-text, #282420);
  }
  .rating__label {
    font-size: 0.875rem;
    font-weight: 600;
  }

  .rating {
    display: inline-flex;
    gap: var(--ds-rating-gap, 0.125rem);
  }
  .rating--disabled {
    opacity: 0.5;
  }

  .rating__star {
    display: inline-flex;
    /* Darker outline so empty stars stay visible. */
    color: var(--ds-rating-empty-color, var(--ds-neutral-400, #757067));
    cursor: pointer;
  }
  .rating--disabled .rating__star {
    cursor: not-allowed;
  }
  .rating__star :global(svg) {
    fill: none;
  }
  /* Hover preview: a neutral grey fill (not the selection color) showing the
     stars about to be set. */
  .rating__star--preview {
    color: var(--ds-rating-preview-color, var(--ds-neutral-300, #a8a297));
  }
  .rating__star--preview :global(svg) {
    fill: currentColor;
  }
  .rating__star--filled {
    color: var(--ds-rating-color, var(--ds-color-secondary, #7a52cc));
  }
  .rating__star--filled :global(svg) {
    fill: currentColor;
  }

  /* The native radio is the accessible, focusable control; visually hidden, with
     the star's focus ring painted from its :focus-visible state. */
  .rating__input {
    position: absolute;
    inline-size: 1px;
    block-size: 1px;
    margin: -1px;
    padding: 0;
    border: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    white-space: nowrap;
  }
  .rating__star:has(.rating__input:focus-visible) {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
    border-radius: 2px;
  }
</style>
