// packages/react/src/avatar/Avatar.tsx
import { useState } from "react";

export interface AvatarProps {
  /** Required: the accessible name and the source of the initials. */
  name: string;
  /** Image URL. When absent or it fails to load, the initials show. */
  src?: string;
  /** Accessible name; defaults to `name`. */
  alt?: string;
  size?: "sm" | "md" | "lg";
  shape?: "circle" | "square";
}

// A user-perceived character, not a UTF-16 code unit: an emoji or a combined
// character counts as one initial. Falls back to code units where the runtime
// has no segmenter. One segmenter serves every avatar: it keeps no state.
let segmenter: Intl.Segmenter | null | undefined;

function firstGraphemes(text: string, count: number): string {
  segmenter ??=
    typeof Intl !== "undefined" && "Segmenter" in Intl
      ? new Intl.Segmenter(undefined, { granularity: "grapheme" })
      : null;
  if (!segmenter) return text.slice(0, count);
  let out = "";
  let taken = 0;
  for (const { segment } of segmenter.segment(text)) {
    out += segment;
    if (++taken === count) break;
  }
  return out;
}

/** Derive up to two initials from a name (first and last word). */
export function initialsOf(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return firstGraphemes(parts[0]!, 2).toUpperCase();
  return (firstGraphemes(parts[0]!, 1) + firstGraphemes(parts[parts.length - 1]!, 1)).toUpperCase();
}

/**
 * Avatar: a small account image that falls back to the account's initials
 * when no image is set or the image fails to load.
 *
 * `name` is required: it gives both the accessible name and the initials. The
 * whole avatar is one image to assistive tech (`role="img"` and
 * `aria-label`), so it reads the same with the photo or the initials. Size,
 * shape and colours are themeable (`--ds-avatar-*`).
 */
export function Avatar({ name, src, alt, size = "md", shape = "circle" }: AvatarProps) {
  // The source that failed: a new `src` no longer matches, so it is tried.
  const [failedSrc, setFailedSrc] = useState<string>();
  const showImage = Boolean(src) && failedSrc !== src;
  return (
    <span
      className="avatar"
      data-size={size}
      data-shape={shape}
      role="img"
      aria-label={alt ?? name}
    >
      {showImage ? (
        <img className="avatar__img" src={src} alt="" onError={() => setFailedSrc(src)} />
      ) : (
        <span className="avatar__initials" aria-hidden="true">
          {initialsOf(name)}
        </span>
      )}
    </span>
  );
}

// packages/svelte/src/lib/avatar/Avatar.svelte
<script module lang="ts">
  // A user-perceived character, not a UTF-16 code unit: an emoji or a
  // combined character counts as one initial. Falls back to code units where
  // the runtime has no segmenter.
  function firstGraphemes(text: string, count: number): string {
    if (typeof Intl !== "undefined" && "Segmenter" in Intl) {
      const segments = new Intl.Segmenter(undefined, { granularity: "grapheme" }).segment(text);
      let out = "";
      let taken = 0;
      for (const segment of segments) {
        out += segment.segment;
        taken += 1;
        if (taken === count) break;
      }
      return out;
    }
    return text.slice(0, count);
  }

  /** Derive up to two initials from a name (first + last word). */
  export function initialsOf(name: string): string {
    const parts = name.trim().split(/\s+/).filter(Boolean);
    if (parts.length === 0) return "?";
    if (parts.length === 1) return firstGraphemes(parts[0]!, 2).toUpperCase();
    return (
      firstGraphemes(parts[0]!, 1) + firstGraphemes(parts[parts.length - 1]!, 1)
    ).toUpperCase();
  }
</script>

<script lang="ts">
  /**
   * Avatar — a small account image that falls back to the account's initials
   * when no image is set or the image fails to load.
   *
   * `name` is required: it provides both the accessible name and the initials
   * fallback. The whole avatar is exposed as a single image to assistive tech
   * (`role="img"` + `aria-label`), so it reads the same whether the photo or the
   * initials are showing. Size/shape/colors are themeable (`--ds-avatar-*`).
   */
  interface Props {
    name: string;
    /** Image URL. When absent or it fails to load, initials are shown. */
    src?: string;
    /** Accessible name; defaults to `name`. */
    alt?: string;
    size?: "sm" | "md" | "lg";
    shape?: "circle" | "square";
  }

  let { name, src, alt, size = "md", shape = "circle" }: Props = $props();

  // Set when the image fails to load; a new src clears it and tries again.
  let failed = $derived.by(() => {
    void src;
    return false;
  });
  const showImage = $derived(Boolean(src) && !failed);
  const initials = $derived(initialsOf(name));
</script>

<span class="avatar" data-size={size} data-shape={shape} role="img" aria-label={alt ?? name}>
  {#if showImage}
    <img class="avatar__img" {src} alt="" onerror={() => (failed = true)} />
  {:else}
    <span class="avatar__initials" aria-hidden="true">{initials}</span>
  {/if}
</span>

<style>
  .avatar {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex: none;
    overflow: hidden;
    inline-size: var(--ds-avatar-size, 2.5rem);
    block-size: var(--ds-avatar-size, 2.5rem);
    background-color: var(--ds-avatar-bg, var(--ds-color-surface, #e6e0d8));
    color: var(--ds-avatar-color, var(--ds-color-text, #282420));
    font-weight: 600;
    line-height: 1;
    user-select: none;
  }
  .avatar:global([data-size="sm"]) {
    inline-size: var(--ds-avatar-size, 2rem);
    block-size: var(--ds-avatar-size, 2rem);
    font-size: 0.75rem;
  }
  .avatar:global([data-size="md"]) {
    inline-size: var(--ds-avatar-size, 2.5rem);
    block-size: var(--ds-avatar-size, 2.5rem);
    font-size: 0.875rem;
  }
  .avatar:global([data-size="lg"]) {
    inline-size: var(--ds-avatar-size, 3.5rem);
    block-size: var(--ds-avatar-size, 3.5rem);
    font-size: 1.125rem;
  }
  .avatar:global([data-shape="circle"]) {
    border-radius: 50%;
  }
  .avatar:global([data-shape="square"]) {
    border-radius: var(--ds-avatar-radius, var(--ds-radius-control, 0.5rem));
  }

  .avatar__img {
    inline-size: 100%;
    block-size: 100%;
    object-fit: cover;
    display: block;
  }
</style>
