// packages/react/src/upload-drop-area/UploadDropArea.tsx
import { useEffect, useRef, useState, type ReactNode } from "react";
import { useDropArea } from "../drop-area/use-drop-area";
import { useI18n } from "../i18n/i18n";
import { cx } from "../internal/cx";
import { Loading } from "../loading/Loading";

export interface UploadDropAreaProps {
  /**
   * Accepted file types (the input's `accept` attribute), e.g. `"image/*"` or
   * `".pdf,.docx"`. The picker filters by it, and so does a drop.
   */
  accept?: string;
  /** Allow selecting or dropping more than one file. */
  multiple?: boolean;
  disabled?: boolean;
  /** Form field name (the underlying file input). */
  name?: string;
  /** Optional caption under the text, such as the accepted formats or the size limit. */
  caption?: string;
  /** Called with the selected or dropped files. */
  onFiles?: (files: File[]) => void;
  /** Replaces the default prompt text. */
  children?: ReactNode;
  /** Replaces the built-in upload icon. */
  icon?: ReactNode;
}

// The native file dialog can take up to a second to appear while the system
// builds it; a spinner past this delay covers the wait without a flash.
const PICKER_SPINNER_DELAY = 150;

/**
 * Whether a file matches an `accept` list, the way the file picker reads it:
 * comma-separated extensions (`.pdf`), MIME types (`image/png`) and type
 * wildcards (`image/*`). An empty list accepts everything.
 */
export function acceptsFile(file: File, accept: string | undefined): boolean {
  const tokens = (accept ?? "")
    .split(",")
    .map((token) => token.trim().toLowerCase())
    .filter(Boolean);
  if (tokens.length === 0) return true;
  const name = file.name.toLowerCase();
  const type = file.type.toLowerCase();
  return tokens.some((token) =>
    token.startsWith(".")
      ? name.endsWith(token)
      : token.endsWith("/*")
        ? type.startsWith(token.slice(0, -1))
        : type === token,
  );
}

/**
 * UploadDropArea: a drag-and-drop file area with a click-to-browse fallback.
 *
 * Built on a native `<input type="file">`, so the browser owns file
 * selection, keyboard operation and form participation; the styled area is a
 * `<label>` for that input, so clicking it or pressing Enter or Space opens
 * the picker. A `dragover` highlight gives drag feedback, and dropped files
 * reach the same `onFiles` callback as picked ones. A drop keeps only the
 * files `accept` names, as the picker does, and the component never reads or
 * previews their content.
 *
 * Themeable via `--ds-upload-drop-area-*`. The default prompt comes from the
 * catalog (`uploadDropArea.prompt` and the styled `uploadDropArea.action`
 * word); `children` replace it entirely.
 */
export function UploadDropArea({
  accept,
  multiple = false,
  disabled = false,
  name,
  caption,
  onFiles,
  children,
  icon,
}: UploadDropAreaProps) {
  const { t } = useI18n();
  const inputRef = useRef<HTMLInputElement>(null);

  const emit = (files: File[]) => {
    if (files.length > 0) onFiles?.(files);
  };

  // A dropped file joins the form the way a picked one does: it becomes the
  // input's file list, so it submits, and a form reset clears it. A single
  // file input holds one file, so a multi-file drop keeps the first.
  const adopt = (dropped: FileList) => {
    const kept = Array.from(dropped)
      .filter((file) => acceptsFile(file, accept))
      .slice(0, multiple ? undefined : 1);
    const input = inputRef.current;
    if (input && kept.length > 0 && typeof DataTransfer !== "undefined") {
      const transfer = new DataTransfer();
      for (const file of kept) transfer.items.add(file);
      input.files = transfer.files;
    }
    emit(kept);
  };

  const { dropAreaProps } = useDropArea({
    disabled,
    onDrop: (data) => adopt(data.files),
  });

  // The picker is opening from the click until a file is chosen, the dialog
  // is cancelled, or the window gets focus back as the dialog closes. Loading
  // owns the no-flash delay and the overlay; this owns only that window.
  const [opening, setOpening] = useState(false);
  useEffect(() => {
    const input = inputRef.current;
    if (!opening || !input) return;
    const close = () => setOpening(false);
    window.addEventListener("focus", close, { once: true });
    // React listens for `cancel` on a dialog only, so the input's is wired here.
    input.addEventListener("cancel", close);
    return () => {
      window.removeEventListener("focus", close);
      input.removeEventListener("cancel", close);
    };
  }, [opening]);

  return (
    <label
      {...dropAreaProps}
      className={cx(
        "upload-drop-area",
        disabled && "upload-drop-area--disabled",
        opening && "upload-drop-area--opening",
      )}
      aria-busy={opening ? "true" : undefined}
    >
      <input
        ref={inputRef}
        className="upload-drop-area__input"
        type="file"
        accept={accept}
        multiple={multiple}
        disabled={disabled}
        name={name}
        onClick={() => {
          if (!disabled) setOpening(true);
        }}
        onChange={(event) => {
          setOpening(false);
          emit(Array.from(event.currentTarget.files ?? []));
        }}
      />
      <span className="upload-drop-area__icon" aria-hidden="true">
        {icon ?? (
          <svg
            viewBox="0 0 24 24"
            width="2em"
            height="2em"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.75"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="17 8 12 3 7 8" />
            <line x1="12" y1="3" x2="12" y2="15" />
          </svg>
        )}
      </span>
      <span className="upload-drop-area__text">
        {children ?? (
          // The action word only looks like a link: the label and its file
          // input are the interactive element, so the word stays a plain span.
          <>
            {`${t("uploadDropArea.prompt")} `}
            <span className="upload-drop-area__action">{t("uploadDropArea.action")}</span>
          </>
        )}
      </span>
      {caption ? <span className="upload-drop-area__caption">{caption}</span> : null}
      {opening ? (
        // No veil: the system dialog is already modal.
        <Loading variant="spinner" overlay veil={false} delay={PICKER_SPINNER_DELAY} decorative />
      ) : null}
    </label>
  );
}

// packages/svelte/src/lib/upload-drop-area/UploadDropArea.svelte
<script lang="ts">
  /**
   * UploadDropArea — a drag-and-drop file area with a click-to-browse fallback.
   *
   * Built on a native `<input type="file">` so the browser owns file selection,
   * keyboard operation and form participation; the styled area is a `<label>` for
   * that input, so clicking or pressing Enter/Space on it opens the picker. A
   * `dragover` highlight gives drag feedback, and dropped files are forwarded
   * through the same `onFiles` callback as picked files.
   *
   * Themeable via `--ds-upload-drop-area-*`. The default prompt comes from the i18n
   * catalog (`uploadDropArea.prompt` + the styled `uploadDropArea.action` word); pass your
   * own content as the `children` snippet to replace it entirely.
   */
  import type { Snippet } from "svelte";
  import type { Action } from "svelte/action";
  import { dropArea } from "../drop-area/drop-area";
  import { getI18n } from "../i18n/create-i18n";
  import Loading from "../loading/Loading.svelte";

  const { t } = getI18n();

  interface Props {
    /** Accepted file types (the input's `accept` attribute), e.g. "image/*". */
    accept?: string;
    /** Allow selecting/dropping more than one file. */
    multiple?: boolean;
    disabled?: boolean;
    /** Form field name (the underlying file input). */
    name?: string;
    /** Optional grey caption under the text (e.g. accepted formats / max size). */
    caption?: string;
    /** Called with the selected/dropped files. */
    onFiles?: (files: File[]) => void;
    /** Replaces the default prompt text. */
    children?: Snippet;
    /** Replaces the built-in upload icon. */
    icon?: Snippet;
  }

  let {
    accept,
    multiple = false,
    disabled = false,
    name,
    caption,
    onFiles,
    children,
    icon,
  }: Props = $props();

  let input: HTMLInputElement | undefined;

  // The native file dialog can take up to ~1s to appear (the OS builds the
  // panel). Per response-time UX (a wait past ~0.4–1s needs feedback), show a
  // loading indicator in that gap. The no-flash delay and the overlay live in
  // the shared Loading component (`delay` + `overlay`/`veil` options); here we
  // only own the trigger (the dialog opening) and the clear (the dialog closing
  // — window refocus — or a file being chosen/cancelled).
  let opening = $state(false);

  function resolveOpen() {
    opening = false;
    if (typeof window !== "undefined") window.removeEventListener("focus", resolveOpen);
  }

  function onOpen() {
    if (disabled) return;
    opening = true;
    // `once` removes it when the window is focused again, and the
    // change/cancel paths clear it early: neither happens if the component
    // goes away while the picker is still open, so unmounting clears it too.
    window.addEventListener("focus", resolveOpen, { once: true });
  }

  // An action (not a lifecycle hook) keeps this client-only and SSR-safe: a
  // picker left open when the area goes away drops its listener here.
  const dropListener: Action = () => ({ destroy: resolveOpen });

  const emit = (list: FileList | null | undefined) => {
    if (!list || !list.length) return;
    onFiles?.(Array.from(list));
  };

  // A dropped file joins the form the way a picked one does: it becomes the
  // input's file list, so it submits, and a form reset clears it. A single
  // file input holds one file, so a multi-file drop keeps the first.
  const adopt = (dropped: FileList) => {
    if (typeof DataTransfer === "undefined") {
      onFiles?.(Array.from(dropped));
      return;
    }
    const kept = new DataTransfer();
    for (const file of Array.from(dropped).slice(0, multiple ? undefined : 1)) {
      kept.items.add(file);
    }
    if (input) input.files = kept.files;
    emit(kept.files);
  };

  function onInput(event: Event) {
    resolveOpen();
    emit((event.currentTarget as HTMLInputElement).files);
  }
</script>

<!-- The drag target is the generic dropArea action (shared, Tree-ready); this
     component adds the upload business: the file input and its picker. -->
<label
  use:dropListener
  class={[
    "upload-drop-area",
    disabled && "upload-drop-area--disabled",
    opening && "upload-drop-area--opening",
  ]}
  aria-busy={opening ? "true" : undefined}
  use:dropArea={{ disabled, onDrop: (data) => adopt(data.files) }}
>
  <input
    bind:this={input}
    class="upload-drop-area__input"
    type="file"
    {accept}
    {multiple}
    {disabled}
    {name}
    onclick={onOpen}
    oncancel={resolveOpen}
    onchange={onInput}
  />
  <span class="upload-drop-area__icon" aria-hidden="true">
    {#if icon}
      {@render icon()}
    {:else}
      <svg
        viewBox="0 0 24 24"
        width="2em"
        height="2em"
        fill="none"
        stroke="currentColor"
        stroke-width="1.75"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="17 8 12 3 7 8" />
        <line x1="12" y1="3" x2="12" y2="15" />
      </svg>
    {/if}
  </span>
  <span class="upload-drop-area__text">
    {#if children}
      {@render children()}
    {:else}
      <!-- Link-like affordance only: the real interactive element is the label →
           file input, so the action word stays a non-semantic span. -->
      {$t("uploadDropArea.prompt")}
      <span class="upload-drop-area__action">{$t("uploadDropArea.action")}</span>
    {/if}
  </span>
  {#if caption}
    <span class="upload-drop-area__caption">{caption}</span>
  {/if}

  {#if opening}
    <!-- Reuse Loading's built-in delay (no flash on a fast open) + overlay;
         no veil — the OS dialog is already modal, so nothing to block here. -->
    <Loading variant="spinner" overlay veil={false} delay={150} decorative />
  {/if}
</label>

<style>
  .upload-drop-area {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: var(--ds-upload-drop-area-padding, 2rem 1.5rem);
    text-align: center;
    color: var(--ds-upload-drop-area-text, var(--ds-color-text-secondary, #524c44));
    background: var(--ds-upload-drop-area-bg, var(--ds-color-background, #fff));
    border: var(--ds-upload-drop-area-border-width, 2px) dashed
      var(--ds-upload-drop-area-border, var(--ds-color-control-border, #757067));
    border-radius: var(--ds-upload-drop-area-radius, var(--ds-radius-surface, 0.75rem));
    cursor: pointer;
    transition:
      border-color 120ms ease,
      background-color 120ms ease;
  }
  .upload-drop-area:global([data-dragover]) {
    border-color: var(--ds-color-secondary, #7a52cc);
    background: color-mix(
      in srgb,
      var(--ds-color-secondary, #7a52cc) 8%,
      var(--ds-color-background, #fff)
    );
  }
  .upload-drop-area--disabled {
    opacity: 0.55;
    cursor: not-allowed;
  }
  /* The opening spinner is a Loading overlay (veil off); tint it and scale it
     up a little via the font-size it keys off. */
  .upload-drop-area--opening :global(.loading--overlay) {
    color: var(--ds-color-secondary, #7a52cc);
    font-size: 1.5rem;
  }
  .upload-drop-area__icon {
    /* Neutral (not the selection color) — the selection color is reserved for
       selected states; here a soft grey reads as a quiet affordance. */
    color: var(--ds-upload-drop-area-icon, var(--ds-color-text-secondary, #524c44));
  }
  .upload-drop-area__icon :global(svg) {
    inline-size: 2em;
    block-size: 2em;
  }
  /* The action word ("browse") reads as the clickable action (link-like, underlined). */
  .upload-drop-area__action {
    color: var(--ds-color-secondary-body-text, #7a52cc);
    font-weight: 600;
    text-decoration: underline;
    text-underline-offset: 2px;
  }
  .upload-drop-area__caption {
    font-size: 0.8125rem;
    color: var(--ds-color-text-secondary, #524c44);
  }
  /* Visually hidden but focusable: focus lands on the input, ring on the label. */
  .upload-drop-area__input {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }
  .upload-drop-area:focus-within {
    border-style: solid;
    box-shadow: var(--ds-focus-ring-shadow, 0 0 0 2px var(--ds-color-focus-ring, #8e6cd4));
  }
  /* Forced colors: the focus sits on the hidden file input, and shadows
     are dropped, so the visible area carries the ring itself. */
  @media (forced-colors: active) {
    .upload-drop-area:focus-within {
      outline: var(--ds-focus-ring-width, 2px) solid Highlight;
      outline-offset: 2px;
    }
  }
</style>
