// packages/svelte/src/lib/date-range-picker/DateRangePicker.svelte
<script lang="ts">
  /**
   * DateRangePicker — a field that opens a range `Calendar` in a popover.
   * Composes the headless popover (`createPopover`) with `Calendar` in
   * `mode="range"`: the first click sets the start, the next sets the end (days
   * between are banded); once both are chosen the popover closes. The field
   * shows the range Intl-formatted; the value is two ISO `YYYY-MM-DD` strings.
   *
   * `min`/`max`, `events` and `prices` forward to the calendar; defaults to the
   * two-month view (handy for ranges). Themeable via `--ds-date-picker-*` and
   * the calendar's `--ds-calendar-*`.
   */
  import { createPopover } from "../popover/create-popover";
  import Calendar, { type CalendarEvent } from "../calendar/Calendar.svelte";
  import type { CalendarView, WeekStart } from "../calendar/create-calendar";
  import Icon from "../icon/Icon.svelte";
  import { i18n } from "@design-system/core";
  import { getI18n } from "../i18n/create-i18n";
  import { stableId } from "../internal/stable-id";

  const { t, locale: providerLocale } = getI18n();

  export let start: string | null = null;
  export let end: string | null = null;
  export let min: string | undefined = undefined;
  export let max: string | undefined = undefined;
  export let weekStartsOn: WeekStart = 1;
  export let locale: string | undefined = undefined;
  export let dateStyle: "full" | "long" | "medium" | "short" = "medium";
  /** Calendar view inside the popover. Defaults to two months side by side. */
  export let view: CalendarView = "two-month";
  export let label: string | undefined = undefined;
  export let placeholder: string | undefined = undefined;
  export let disabled = false;
  export let clearable = false;
  export let events: CalendarEvent[] = [];
  export let prices: Record<string, string> = {};

  /** Form field name for the start date (submitted as an ISO value via a hidden input). */
  export let startName: string | undefined = undefined;
  /** Form field name for the end date (submitted as an ISO value via a hidden input). */
  export let endName: string | undefined = undefined;
  export let onChange: ((start: string | null, end: string | null) => void) | undefined = undefined;

  const popover = createPopover({ placement: "bottom-start" });
  const { triggerAction, contentAction, open: isOpen, setOpen } = popover;

  const dt = (iso: string) => new Date(`${iso}T00:00:00`);
  $: resolvedLocale = locale ?? $providerLocale;
  $: displayFmt = i18n.dateTimeFormat(resolvedLocale, { dateStyle });
  $: displayValue =
    start && end
      ? displayFmt.formatRange(dt(start), dt(end))
      : start
        ? `${displayFmt.format(dt(start))} – …`
        : "";

  const handleRange = (s: string | null, e: string | null) => {
    start = s;
    end = e;
    onChange?.(s, e);
    if (s && e) setOpen(false);
  };

  const clear = () => {
    start = null;
    end = null;
    onChange?.(null, null);
  };

  // The combobox names the panel it controls; the panel exists only while open.
  const popupId = `${stableId("dsDateRangePicker")}-popup`;
</script>

<div class="date-picker" class:date-picker--disabled={disabled}>
  {#if startName}
    <input type="hidden" name={startName} value={start ?? ""} />
  {/if}
  {#if endName}
    <input type="hidden" name={endName} value={end ?? ""} />
  {/if}
  <div class="date-picker__field">
    <span
      class="date-picker__icon"
      class:date-picker__icon--active={start || end}
      aria-hidden="true"
    >
      <Icon size="1.1rem">
        <rect x="3" y="4" width="18" height="18" rx="2" />
        <line x1="16" y1="2" x2="16" y2="6" />
        <line x1="8" y1="2" x2="8" y2="6" />
        <line x1="3" y1="10" x2="21" y2="10" />
      </Icon>
    </span>
    <input
      class="date-picker__input"
      type="text"
      role="combobox"
      readonly
      {disabled}
      aria-label={label ?? $t("dateRangePicker.label")}
      placeholder={placeholder ?? $t("dateRangePicker.placeholder")}
      value={displayValue}
      aria-controls={popupId}
      aria-expanded={$isOpen}
      use:triggerAction
    />
    {#if clearable && start && !disabled}
      <button
        class="date-picker__clear"
        type="button"
        aria-label={$t("dateRangePicker.clear")}
        on:click={clear}
      >
        <Icon size="0.9rem"
          ><line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" /></Icon
        >
      </button>
    {/if}
  </div>

  {#if $isOpen}
    <div class="date-picker__popover date-picker__popover--wide" id={popupId} use:contentAction>
      <Calendar
        mode="range"
        rangeStart={start}
        rangeEnd={end}
        focusedDate={start ?? undefined}
        {view}
        {min}
        {max}
        {weekStartsOn}
        {locale}
        {events}
        {prices}
        onRangeChange={handleRange}
        label={label ?? $t("dateRangePicker.label")}
      />
    </div>
  {/if}
</div>

<style>
  .date-picker {
    display: inline-flex;
    flex-direction: column;
    font: inherit;
    color: var(--ds-color-text, #0f172a);
  }
  .date-picker__field {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding-inline: 0.6rem;
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-radius-control, 0.5rem);
  }
  .date-picker__field:focus-within {
    border-color: var(--ds-color-focus-ring, #2563eb);
    box-shadow: var(--ds-focus-ring-shadow);
  }
  .date-picker--disabled .date-picker__field {
    opacity: 0.55;
  }
  .date-picker__icon {
    display: inline-flex;
    color: var(--ds-color-text-secondary, #64748b);
  }
  /* Once a range is set, the icon adopts the selection color (like DatePicker). */
  .date-picker__icon--active {
    color: var(--ds-color-secondary, #7b52cc);
  }
  .date-picker__input {
    flex: 1;
    min-inline-size: 12rem;
    padding-block: 0.5rem;
    font: inherit;
    color: inherit;
    background: none;
    border: 0;
    outline: none;
    cursor: pointer;
  }
  .date-picker__input::placeholder {
    color: var(--ds-color-text-secondary, #94a3b8);
  }
  .date-picker__input:disabled {
    cursor: not-allowed;
  }
  .date-picker__clear {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.2rem;
    color: var(--ds-color-text-secondary, #64748b);
    background: none;
    border: 0;
    border-radius: 50%;
    cursor: pointer;
  }
  .date-picker__clear:hover {
    background: var(--ds-color-neutral-surface, #f1f5f9);
  }
  .date-picker__clear:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 1px;
  }

  .date-picker__popover {
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-popover-z-index, 50);
    box-sizing: border-box;
    inline-size: max-content;
    max-inline-size: min(94vw, 40rem);
    padding: var(--ds-popover-padding, 0.875rem 1rem);
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-popover-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(
      --ds-elevation-overlay,
      0 10px 15px -3px rgb(0 0 0 / 0.1),
      0 4px 6px -4px rgb(0 0 0 / 0.1)
    );
  }
</style>

// packages/react/src/date-range-picker/DateRangePicker.tsx
import { i18n as coreI18n } from "@design-system/core";
import { useRef } from "react";
import { Calendar, type CalendarEvent } from "../calendar/Calendar";
import type { CalendarView, WeekStart } from "../calendar/use-calendar";
import type { DateStyle } from "../date-picker/DatePicker";
import { useI18n } from "../i18n/i18n";
import { asDate, localDate } from "../internal/date";
import { useResettable } from "../internal/form-reset";
import { PickerField } from "../internal/picker-field";

export interface DateRangePickerProps {
  /** Initial (uncontrolled) or current (controlled) range start, ISO `YYYY-MM-DD`, or `null`. */
  start?: string | null;
  /** Initial (uncontrolled) or current (controlled) range end, ISO `YYYY-MM-DD`, or `null`. */
  end?: string | null;
  /** Earliest selectable date (ISO), inclusive. */
  min?: string;
  /** Latest selectable date (ISO), inclusive. */
  max?: string;
  /** First day of the week, 0 = Sunday to 6. */
  weekStartsOn?: WeekStart;
  /** BCP-47 locale for the field and the calendar. Defaults to the provider's locale. */
  locale?: string;
  /** `Intl` date style for the field. */
  dateStyle?: DateStyle;
  /** Calendar view inside the popup. Defaults to two months side by side. */
  view?: CalendarView;
  /** Accessible label for the field. Defaults to the catalog's. */
  label?: string;
  /** Placeholder while empty. Defaults to the catalog's. */
  placeholder?: string;
  disabled?: boolean;
  /** Show a clear button when a range is started. */
  clearable?: boolean;
  /** Appointment dots, forwarded to the calendar. */
  events?: CalendarEvent[];
  /** Per-day price labels, forwarded to the calendar. */
  prices?: Record<string, string>;
  /** Form field name for the start date, submitted as an ISO value. */
  startName?: string;
  /** Form field name for the end date, submitted as an ISO value. */
  endName?: string;
  /** Called after each pick and on clear, with a `null` end while the range is half made. */
  onChange?: (start: string | null, end: string | null) => void;
}

/**
 * DateRangePicker: a field that opens a range `Calendar` in a popup. It shares
 * DatePicker's field and popup: the first pick sets the start, the next sets
 * the end (the days between are banded), and the popup closes once both are
 * chosen, with focus back on the field. A pick before the start becomes the
 * new start. The field shows the range formatted with `Intl`; the value is two
 * ISO `YYYY-MM-DD` strings, each a controllable mirror (ADR 0011). With
 * `startName` and `endName`, hidden inputs submit them, and a form reset puts
 * back the current defaults without reporting (ADR 0012). The view defaults
 * to two months. Themeable via `--ds-date-picker-*` and the calendar's
 * `--ds-calendar-*`.
 */
export function DateRangePicker({
  start = null,
  end = null,
  min,
  max,
  weekStartsOn = 1,
  locale,
  dateStyle = "medium",
  view = "two-month",
  label,
  placeholder,
  disabled = false,
  clearable = false,
  events,
  prices,
  startName,
  endName,
  onChange,
}: DateRangePickerProps) {
  const i18n = useI18n();
  const { t } = i18n;
  const rootRef = useRef<HTMLDivElement>(null);
  // Both ends report through one callback, once per action.
  const [from, setFrom] = useResettable(asDate(start), undefined, rootRef);
  const [to, setTo] = useResettable(asDate(end), undefined, rootRef);
  const format = coreI18n.dateTimeFormat(locale ?? i18n.locale, { dateStyle });
  const fieldLabel = label ?? t("dateRangePicker.label");

  const report = (nextStart: string | null, nextEnd: string | null) => {
    setFrom(nextStart);
    setTo(nextEnd);
    onChange?.(nextStart, nextEnd);
  };

  const text =
    from && to
      ? format.formatRange(localDate(from), localDate(to))
      : from
        ? `${format.format(localDate(from))} – …`
        : "";

  return (
    <PickerField
      rootRef={rootRef}
      label={fieldLabel}
      placeholder={placeholder ?? t("dateRangePicker.placeholder")}
      clearLabel={t("dateRangePicker.clear")}
      text={text}
      active={from != null || to != null}
      clearable={clearable && from != null}
      disabled={disabled}
      inputClass="date-picker__input--range"
      popupClass="date-picker__popover--wide"
      fields={[
        { name: startName, value: from },
        { name: endName, value: to },
      ]}
      onClear={() => report(null, null)}
    >
      {(done) => (
        <Calendar
          mode="range"
          rangeStart={from}
          rangeEnd={to}
          focusedDate={from ?? undefined}
          view={view}
          min={min}
          max={max}
          weekStartsOn={weekStartsOn}
          locale={locale}
          events={events}
          prices={prices}
          label={fieldLabel}
          onRangeChange={(nextStart, nextEnd) => {
            // A finished range closes before it is reported (ADR 0011).
            if (nextStart && nextEnd) done();
            report(nextStart, nextEnd);
          }}
        />
      )}
    </PickerField>
  );
}
