// packages/react/src/collapsible/Collapsible.tsx
import type { ReactNode } from "react";
import { useI18n } from "../i18n/i18n";
import { ChevronGlyph, Icon } from "../icon/Icon";
import { useCollapsible } from "./use-collapsible";

export interface CollapsibleProps {
  /** Initial (uncontrolled) or current (controlled) open state. */
  open?: boolean;
  /** Whether the collapsible is disabled. */
  disabled?: boolean;
  /** Trigger text, used when `trigger` is not given. */
  label?: string;
  /** The trigger's content. Defaults to `label`, then the catalog's "Toggle". */
  trigger?: ReactNode;
  /** Called whenever the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** The collapsible content. */
  children?: ReactNode;
}

/**
 * Collapsible: a styled, single-item disclosure (WAI-ARIA disclosure
 * pattern): one trigger button toggling one content region. Behaviour and
 * accessibility (`aria-expanded`/`aria-controls` wiring, disabled handling)
 * come from the headless collapsible (`@design-system/core`); this layer adds
 * a trigger row with a rotating chevron and a content area.
 *
 * Colors, radius and spacing are themeable via `--ds-collapsible-*`.
 */
export function Collapsible({
  open = false,
  disabled = false,
  label,
  trigger,
  onOpenChange,
  children,
}: CollapsibleProps) {
  const { t } = useI18n();
  const api = useCollapsible({ open, disabled, onOpenChange });
  return (
    <div className="collapsible" {...api.rootProps}>
      <button className="collapsible__trigger" {...api.triggerProps}>
        <span className="collapsible__label">{trigger ?? label ?? t("collapsible.toggle")}</span>
        <span className="collapsible__icon" aria-hidden="true">
          <Icon size="var(--ds-collapsible-icon-size, 1.1em)">
            <ChevronGlyph />
          </Icon>
        </span>
      </button>
      <div className="collapsible__content" {...api.contentProps}>
        {children}
      </div>
    </div>
  );
}

// packages/svelte/src/lib/collapsible/Collapsible.svelte
<script lang="ts">
  /**
   * Collapsible — a styled, single-item disclosure (WAI-ARIA disclosure
   * pattern): one trigger button toggling one content region. Behaviour and
   * accessibility (`aria-expanded`/`aria-controls` wiring, disabled handling)
   * come from the headless collapsible (`@design-system/core`); this layer adds
   * a trigger row with a rotating chevron and a content area.
   *
   * Slots: `trigger` (the trigger's content, falling back to the `label` prop)
   * and the default slot (the collapsible content). Colors, radius and spacing
   * are themeable via `--ds-collapsible-*`.
   */
  import { createCollapsible } from "./create-collapsible";
  import Icon from "../icon/Icon.svelte";
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  /** Initial open state. */
  export let open = false;
  /** Whether the collapsible is disabled. */
  export let disabled = false;
  /** Trigger text, used when the `trigger` slot is not provided. */
  export let label: string | undefined = undefined;
  /** Called whenever the open state changes. */
  export let onOpenChange: ((open: boolean) => void) | undefined = undefined;

  const { rootAction, triggerAction, contentAction } = createCollapsible({
    open,
    disabled,
    onOpenChange,
  });
</script>

<div class="collapsible" use:rootAction>
  <button class="collapsible__trigger" use:triggerAction>
    <span class="collapsible__label"
      ><slot name="trigger">{label ?? $t("collapsible.toggle")}</slot></span
    >
    <span class="collapsible__icon" aria-hidden="true">
      <Icon size="var(--ds-collapsible-icon-size, 1.1em)">
        <polyline points="6 9 12 15 18 9" />
      </Icon>
    </span>
  </button>
  <div class="collapsible__content" use:contentAction>
    <slot />
  </div>
</div>

<style>
  .collapsible {
    inline-size: var(--ds-collapsible-width, 18rem);
  }
  .collapsible__trigger {
    inline-size: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 0.5rem;
    padding: var(--ds-collapsible-trigger-padding, 0.5rem 0.75rem);
    border: 1px solid var(--ds-color-control-border, #757067);
    border-radius: var(--ds-collapsible-radius, var(--ds-radius-control, 0.5rem));
    background: var(--ds-color-background, #fff);
    font: inherit;
    color: var(--ds-color-text, #282420);
    cursor: pointer;
    text-align: start;
  }
  .collapsible__icon {
    display: inline-flex;
    flex: none;
    color: var(--ds-color-text-secondary, #524c44);
    transition: rotate 150ms ease;
  }
  .collapsible__trigger:global([data-state="open"]) .collapsible__icon {
    rotate: 180deg;
  }
  .collapsible__trigger:global(:focus-visible) {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }
  .collapsible__trigger:global([data-disabled]) {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .collapsible__content {
    padding: var(--ds-collapsible-content-padding, 0.625rem 0.75rem);
  }
</style>
