// packages/react/src/code-block/CodeBlock.tsx
import type { ReactNode } from "react";
import { useI18n } from "../i18n/i18n";
import { useCopyFeedback } from "../internal/copy-feedback";

export interface CodeBlockProps {
  /** The source text: what the copy button copies, and what shows without `children`. */
  code?: string;
  /** Optional caption in the header, such as a language or a filename. */
  language?: string;
  /** Render a copy button. Defaults to `true`. */
  copyable?: boolean;
  /** Name of the copy button. Defaults to the catalog's "Copy code". */
  copyLabel?: string;
  /** Already highlighted markup, shown in place of `code`. */
  children?: ReactNode;
}

/**
 * CodeBlock: a multi-line, monospaced, preformatted sample (`<pre><code>`)
 * with an optional caption and copy button. `code` keeps its whitespace and
 * is always rendered as text.
 *
 * There is no syntax highlighting: pass highlighted markup as `children`;
 * `code` still drives the copy button.
 *
 * Accessibility: the block is a named group, and so is the scroller, which
 * takes focus so keyboard users can scroll wide samples; several blocks on a
 * page stay off the landmark list. The copy button shares Button's copy logic
 * (ADR 0016) and announces success through a polite live region present from
 * the first render.
 *
 * Themeable via `--ds-code-block-*`.
 */
export function CodeBlock({
  code = "",
  language,
  copyable = true,
  copyLabel,
  children,
}: CodeBlockProps) {
  const { t } = useI18n();
  const { copied, copy } = useCopyFeedback();
  return (
    <figure
      className="code-block"
      role="group"
      aria-label={language ? t("codeBlock.labelLanguage", { language }) : t("codeBlock.label")}
    >
      {language || copyable ? (
        <figcaption className="code-block__header">
          {language ? <span className="code-block__lang">{language}</span> : null}
          {copyable ? (
            <button
              type="button"
              className="code-block__copy"
              aria-label={copyLabel ?? t("codeBlock.copy")}
              onClick={() => void copy(code)}
            >
              {t(copied ? "codeBlock.copiedText" : "codeBlock.copyText")}
            </button>
          ) : null}
        </figcaption>
      ) : null}
      <pre
        className="code-block__pre"
        // Wide code scrolls sideways, so the scroller is reachable by keyboard.
        tabIndex={0}
        role="group"
        aria-label={language ? t("codeBlock.sampleLanguage", { language }) : t("codeBlock.sample")}
      >
        <code className="code-block__code">{children ?? code}</code>
      </pre>
      <span className="code-block__live" role="status" aria-live="polite">
        {copied && copyable ? t("codeBlock.copied") : ""}
      </span>
    </figure>
  );
}

// packages/svelte/src/lib/code-block/CodeBlock.svelte
<script lang="ts">
  /**
   * CodeBlock — block code: a multi-line, monospaced, preformatted snippet
   * (`<pre><code>`). Pass the source as the `code` prop (preserves whitespace and
   * is what the copy button copies). An optional `language`/`filename` caption and
   * an optional copy-to-clipboard button can be shown.
   *
   * This is a presentational container — it does not do syntax highlighting; wrap
   * already-highlighted markup with the default slot if you need it (the `code`
   * prop still drives the copy button).
   *
   * Accessibility:
   * - The caption labels the region (`aria-label`) so screen-reader users know
   *   what the block contains.
   * - The code scroller is a focusable, named region, so keyboard users can
   *   reach it and scroll wide samples.
   * - The copy button has an accessible name and announces success via a polite
   *   live region; it is omitted entirely when `copyable` is false.
   *
   * Colors are themeable CSS custom properties (`--ds-code-block-*`).
   */
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  /** The source text. Drives the copy button and is rendered when no slot is given. */
  export let code = "";
  /** Optional caption shown in the header (e.g. a language or filename). */
  export let language: string | undefined = undefined;
  /** Render a copy-to-clipboard button. Defaults to `true`. */
  export let copyable = true;
  /** Accessible name for the copy button. Defaults to the i18n catalog's "Copy code". */
  export let copyLabel: string | undefined = undefined;

  $: resolvedCopyLabel = copyLabel ?? $t("codeBlock.copy");

  let copied = false;
  let timer: ReturnType<typeof setTimeout> | undefined;

  async function copy() {
    try {
      await navigator.clipboard?.writeText(code);
      copied = true;
      clearTimeout(timer);
      timer = setTimeout(() => (copied = false), 2000);
    } catch {
      // Clipboard may be unavailable (insecure context / denied permission);
      // fail silently rather than throwing in the user's face.
    }
  }
</script>

<figure class="code-block" role="group" aria-label={language ? `Code: ${language}` : "Code"}>
  {#if language || copyable}
    <figcaption class="code-block__header">
      {#if language}<span class="code-block__lang">{language}</span>{/if}
      {#if copyable}
        <button
          type="button"
          class="code-block__copy"
          on:click={copy}
          aria-label={resolvedCopyLabel}
        >
          {copied ? "Copied" : "Copy"}
        </button>
      {/if}
    </figcaption>
  {/if}
  <!-- Wide code scrolls sideways, so the scroller must be reachable and
       named for keyboard and screen-reader users. A named group, not a
       landmark: several code blocks on one page would all claim the same
       place in the landmark list. -->
  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
  <pre
    class="code-block__pre"
    tabindex="0"
    role="group"
    aria-label={language ? `Code sample, ${language}` : "Code sample"}><code
      class="code-block__code"><slot>{code}</slot></code
    ></pre>
  <span class="code-block__live" role="status" aria-live="polite">
    {copied ? "Copied to clipboard" : ""}
  </span>
</figure>

<style>
  .code-block {
    margin: 0;
    background: var(--ds-code-block-surface, var(--ds-color-surface, #e6e0d8));
    color: var(--ds-code-block-text, var(--ds-color-text, #282420));
    border: 1px solid var(--ds-code-block-border, var(--ds-color-border, #c7c1b7));
    border-radius: var(--ds-code-block-radius, var(--ds-radius-surface, 0.75rem));
    overflow: hidden;
  }

  .code-block__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
    padding: var(--ds-code-block-header-padding, 0.4rem 0.75rem 0.4rem 1rem);
    font-size: 0.75rem;
    border-block-end: 1px solid var(--ds-code-block-border, var(--ds-color-border, #c7c1b7));
  }

  .code-block__lang {
    font-weight: 600;
    letter-spacing: 0.02em;
    text-transform: lowercase;
    opacity: 0.85;
  }

  .code-block__copy {
    margin-inline-start: auto;
    padding: 0.2rem 0.55rem;
    font: inherit;
    font-size: 0.75rem;
    color: inherit;
    background: var(--ds-code-block-copy-bg, rgba(0, 0, 0, 0.05));
    border: 1px solid transparent;
    border-radius: var(--ds-radius-control, 0.5rem);
    cursor: pointer;
    transition: background-color 120ms ease;
  }
  .code-block__copy:hover {
    background: var(--ds-code-block-copy-hover, rgba(0, 0, 0, 0.1));
  }
  .code-block__copy:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }

  .code-block__pre {
    margin: 0;
    padding: var(--ds-code-block-padding, 1rem);
    overflow-x: auto;
  }
  /* The figure clips overflow, so an outer ring would be invisible here:
     the ring is drawn inside the scroller instead. */
  .code-block__pre:focus-visible {
    outline: none;
    box-shadow: inset 0 0 0 var(--ds-focus-ring-width, 2px) var(--ds-color-focus-ring, #8e6cd4);
  }

  .code-block__code {
    font-family: var(
      --ds-font-mono,
      SFMono-Regular,
      Menlo,
      Monaco,
      Consolas,
      "Liberation Mono",
      "Courier New",
      monospace
    );
    font-size: var(--ds-code-block-font-size, 0.875rem);
    line-height: 1.6;
    white-space: pre;
  }

  /* Visually-hidden live region for the "copied" announcement. */
  .code-block__live {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    border: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    white-space: nowrap;
  }
</style>
