// packages/svelte/src/lib/calendar/Calendar.svelte
<script context="module" lang="ts">
  /** An appointment/event on a given day, shown as a coloured dot. */
  export interface CalendarEvent {
    /** ISO `YYYY-MM-DD`. */
    date: string;
    /** Accessible description (announced; also a tooltip via `title`). */
    label?: string;
    /** Semantic tone for the dot. */
    tone?: "primary" | "success" | "warning" | "danger" | "neutral";
  }
</script>

<script lang="ts">
  /**
   * Calendar — the styled, batteries-included calendar (WAI-ARIA date grid).
   * Behaviour, date math and keyboard navigation come from the headless
   * calendar (`@design-system/core`); this layer adds the header (period label,
   * an optional view switcher, prev/next/today) and the bodies for each view.
   *
   * Views: `month`, `two-month` (two months side by side), `week`,
   * `three-day`, `day` (these last three are day-column agendas). Each day can
   * show **appointment dots** (`events`) and a **price** (`prices`), or custom
   * content via the `day` slot
   * (`let:date let:inMonth let:today let:selected let:events let:price`).
   * Colours, radius and sizing are themeable via `--ds-calendar-*`.
   */
  import { createCalendar, type CalendarView, type WeekStart } from "./create-calendar";
  import { calendar as core } from "@design-system/core";
  import SegmentedControl from "../segmented-control/SegmentedControl.svelte";
  import Icon from "../icon/Icon.svelte";
  import { getI18n } from "../i18n/create-i18n";
  import type { MessageKey } from "../i18n/messages";

  const { t } = getI18n();

  const {
    describe,
    monthMatrix,
    weekdayOrder,
    weekDays,
    rangeDays,
    addMonths,
    startOfMonth,
    monthsOfYear,
    toISO,
  } = core;

  export let value: string | null = null;
  export let focusedDate: string | undefined = undefined;
  export let view: CalendarView = "month";
  export let weekStartsOn: WeekStart = 1;
  export let min: string | undefined = undefined;
  export let max: string | undefined = undefined;
  /** BCP-47 locale for month/weekday names. Defaults to the runtime locale. */
  export let locale: string | undefined = undefined;

  /** Appointment dots, keyed by their `date`. */
  export let events: CalendarEvent[] = [];
  /** Per-day price label, keyed by ISO date (e.g. `{ "2026-06-25": "€120" }`). */
  export let prices: Record<string, string> = {};
  /** Maximum dots rendered before a "+N" overflow marker (grid views). */
  export let maxDots = 3;
  /** Year view: how many mini-months per row. Defaults to 1 (stacked). */
  export let yearColumns = 1;

  /** Views offered in the built-in switcher. With one entry no switcher shows. */
  export let views: CalendarView[] = ["month"];
  /** Override the switcher labels per view. */
  export let viewLabels: Partial<Record<CalendarView, string>> = {};

  export let showToday = true;
  // Labels default to the i18n catalog (overridable per instance or via LocaleProvider).
  export let prevLabel: string | undefined = undefined;
  export let nextLabel: string | undefined = undefined;
  export let todayLabel: string | undefined = undefined;
  export let viewsLabel: string | undefined = undefined;
  /** Accessible name for the grid. */
  export let label: string | undefined = undefined;

  /** Selection mode: a single date, or a start–end `range`. */
  export let mode: "single" | "range" = "single";
  /** Range endpoints (ISO), used when `mode="range"`. */
  export let rangeStart: string | null = null;
  export let rangeEnd: string | null = null;

  export let onValueChange: ((iso: string) => void) | undefined = undefined;
  export let onFocusChange: ((iso: string) => void) | undefined = undefined;
  export let onViewChange: ((view: CalendarView) => void) | undefined = undefined;
  export let onRangeChange: ((start: string | null, end: string | null) => void) | undefined =
    undefined;

  // In range mode each click extends/restarts the range; otherwise it's a
  // single selection. Reuses the core day click (which reports the ISO).
  function handleSelect(iso: string) {
    if (mode === "range") {
      if (!rangeStart || rangeEnd) {
        rangeStart = iso;
        rangeEnd = null;
      } else if (iso < rangeStart) {
        rangeEnd = rangeStart;
        rangeStart = iso;
      } else {
        rangeEnd = iso;
      }
      onRangeChange?.(rangeStart, rangeEnd);
    } else {
      onValueChange?.(iso);
    }
  }

  const calendar = createCalendar({
    value,
    focusedDate,
    view,
    weekStartsOn,
    min,
    max,
    onValueChange: handleSelect,
    onFocusChange,
    onViewChange,
  });
  const { state: calState, api, gridAction, rowAction, cellAction, dayAction } = calendar;

  $: switcherItems = views.map((v) => ({
    value: v,
    label: viewLabels[v] ?? $t(`calendar.view.${v}` as MessageKey),
  }));

  // Intl formatters (recomputed if the locale changes).
  const dt = (iso: string) => new Date(`${iso}T00:00:00`);
  $: titleFmt = new Intl.DateTimeFormat(locale, { month: "long", year: "numeric" });
  $: rangeFmt = new Intl.DateTimeFormat(locale, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  $: weekdayShort = new Intl.DateTimeFormat(locale, { weekday: "short" });
  $: weekdayLong = new Intl.DateTimeFormat(locale, { weekday: "long" });
  $: dayFmt = new Intl.DateTimeFormat(locale, {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  // A reference Sunday (2024-01-07) to render weekday names from an index.
  const weekdayName = (fmt: Intl.DateTimeFormat, wd: number) =>
    fmt.format(new Date(Date.UTC(2024, 0, 7 + wd)));

  $: v = $calState.view;
  $: ref = describe($calState.focusedDate);
  $: order = weekdayOrder($calState.weekStartsOn);
  $: isGrid = v === "month" || v === "two-month";

  // The month(s) shown by the grid views.
  $: gridMonths =
    v === "two-month"
      ? [
          { year: ref.year, month: ref.month },
          (() => {
            const n = describe(addMonths($calState.focusedDate, 1));
            return { year: n.year, month: n.month };
          })(),
        ]
      : [{ year: ref.year, month: ref.month }];

  // The consecutive days shown by the agenda views.
  $: agendaDays =
    v === "week"
      ? weekDays($calState.focusedDate, $calState.weekStartsOn)
      : v === "three-day"
        ? rangeDays($calState.focusedDate, 3)
        : v === "day"
          ? rangeDays($calState.focusedDate, 1)
          : [];

  // Group events by date for O(1) per-cell lookup.
  $: eventsByDate = events.reduce<Record<string, CalendarEvent[]>>((acc, ev) => {
    (acc[ev.date] ??= []).push(ev);
    return acc;
  }, {});

  $: yearFmt = new Intl.DateTimeFormat(locale, { year: "numeric" });
  $: shortMonthFmt = new Intl.DateTimeFormat(locale, { month: "long" });
  const shortMonthName = (year: number, month: number) =>
    shortMonthFmt.format(new Date(Date.UTC(year, month - 1, 1)));
  // Narrow weekday initials for the simplified mini-months.
  $: weekdayNarrow = new Intl.DateTimeFormat(locale, { weekday: "narrow" });

  $: periodTitle = (() => {
    const f = $calState.focusedDate;
    if (v === "year") return yearFmt.format(dt(f));
    if (v === "day") return dayFmt.format(dt(f));
    if (v === "week") {
      const days = weekDays(f, $calState.weekStartsOn);
      return rangeFmt.formatRange(dt(days[0]!.date), dt(days[6]!.date));
    }
    if (v === "three-day") {
      const days = rangeDays(f, 3);
      return rangeFmt.formatRange(dt(days[0]!.date), dt(days[2]!.date));
    }
    if (v === "two-month") {
      return titleFmt.formatRange(dt(startOfMonth(f)), dt(addMonths(startOfMonth(f), 1)));
    }
    return titleFmt.format(dt(f));
  })();

  const monthLabel = (gm: { year: number; month: number }) =>
    titleFmt.format(new Date(Date.UTC(gm.year, gm.month - 1, 1)));

  const dayAria = (iso: string, count: number, price: string | undefined) => {
    let aria = dayFmt.format(dt(iso));
    if (count) aria += `, ${count} ${count === 1 ? "event" : "events"}`;
    if (price) aria += `, ${price}`;
    return aria;
  };
</script>

<section class="calendar" data-view={v} data-mode={mode}>
  <header class="calendar__header">
    <h2 class="calendar__title" aria-live="polite">{periodTitle}</h2>
    <div class="calendar__controls">
      {#if switcherItems.length > 1}
        <SegmentedControl
          items={switcherItems}
          value={v}
          label={viewsLabel ?? $t("calendar.viewsLabel")}
          onValueChange={(next) => $api.setView(next as CalendarView)}
        />
      {/if}
      <div class="calendar__nav">
        {#if showToday}
          <button type="button" class="calendar__today" on:click={() => $api.goToday()}>
            {todayLabel ?? $t("calendar.today")}
          </button>
        {/if}
        <button
          type="button"
          class="calendar__arrow"
          aria-label={prevLabel ?? $t("calendar.previous")}
          on:click={() => $api.goPrev()}
        >
          <Icon size="1.25rem"><polyline points="15 18 9 12 15 6" /></Icon>
        </button>
        <button
          type="button"
          class="calendar__arrow"
          aria-label={nextLabel ?? $t("calendar.next")}
          on:click={() => $api.goNext()}
        >
          <Icon size="1.25rem"><polyline points="9 18 15 12 9 6" /></Icon>
        </button>
      </div>
    </div>
  </header>

  {#if isGrid}
    <div class="calendar__months">
      {#each gridMonths as gm (`${gm.year}-${gm.month}`)}
        {@const hideOutside = v === "two-month"}
        <div class="calendar__month">
          {#if v === "two-month"}
            <h3 class="calendar__month-title">{monthLabel(gm)}</h3>
          {/if}
          <div
            class="calendar__grid"
            use:gridAction
            aria-label={v === "two-month" ? monthLabel(gm) : (label ?? $t("calendar.label"))}
          >
            <div class="calendar__row calendar__weekdays" role="row">
              {#each order as wd (wd)}
                <span
                  class="calendar__weekday"
                  role="columnheader"
                  aria-label={weekdayName(weekdayLong, wd)}
                >
                  {weekdayName(weekdayShort, wd)}
                </span>
              {/each}
            </div>

            {#each monthMatrix(gm.year, gm.month, $calState.weekStartsOn) as week, w (w)}
              {#if !hideOutside || week.some((c) => c.month === gm.month)}
                <div class="calendar__row calendar__week" use:rowAction>
                  {#each week as cell (cell.date)}
                    {@const inMonth = cell.month === gm.month}
                    {#if hideOutside && !inMonth}
                      <div class="calendar__cell calendar__cell--blank" aria-hidden="true"></div>
                    {:else}
                      {@const dayEvents = eventsByDate[cell.date] ?? []}
                      {@const price = prices[cell.date]}
                      {@const inSpan =
                        mode === "range" &&
                        rangeStart &&
                        rangeEnd &&
                        cell.date > rangeStart &&
                        cell.date < rangeEnd}
                      <div class="calendar__cell" use:cellAction={cell.date}>
                        <button
                          class="calendar__day"
                          class:calendar__day--outside={!inMonth}
                          use:dayAction={cell.date}
                          data-range-start={mode === "range" && cell.date === rangeStart
                            ? ""
                            : undefined}
                          data-range-end={mode === "range" && cell.date === rangeEnd
                            ? ""
                            : undefined}
                          data-in-range={inSpan ? "" : undefined}
                          aria-label={dayAria(cell.date, dayEvents.length, price)}
                        >
                          <slot
                            name="day"
                            date={cell.date}
                            {inMonth}
                            selected={$calState.value === cell.date}
                            events={dayEvents}
                            {price}
                          >
                            <span class="calendar__daynum">{cell.day}</span>
                            {#if dayEvents.length}
                              <span class="calendar__dots" aria-hidden="true">
                                {#each dayEvents.slice(0, maxDots) as ev (ev.label ?? ev.date)}
                                  <span
                                    class="calendar__dot"
                                    data-tone={ev.tone ?? "primary"}
                                    title={ev.label}
                                  ></span>
                                {/each}
                                {#if dayEvents.length > maxDots}
                                  <span class="calendar__more">+{dayEvents.length - maxDots}</span>
                                {/if}
                              </span>
                            {/if}
                            {#if price}<span class="calendar__price">{price}</span>{/if}
                          </slot>
                        </button>
                      </div>
                    {/if}
                  {/each}
                </div>
              {/if}
            {/each}
          </div>
        </div>
      {/each}
    </div>
  {:else if v === "year"}
    <div class="calendar__year" style="--year-cols: {yearColumns};">
      {#each monthsOfYear(ref.year) as gm (gm.month)}
        <section class="calendar__mini">
          <button
            type="button"
            class="calendar__mini-title"
            on:click={() => {
              $api.setFocus(toISO(gm.year, gm.month, 1));
              $api.setView("month");
            }}
          >
            {shortMonthName(gm.year, gm.month)}
          </button>
          <div
            class="calendar__mini-grid"
            use:gridAction
            aria-label={shortMonthName(gm.year, gm.month)}
          >
            <div class="calendar__row calendar__mini-weekdays" role="row">
              {#each order as wd (wd)}
                <span
                  class="calendar__mini-weekday"
                  role="columnheader"
                  aria-label={weekdayName(weekdayLong, wd)}
                >
                  {weekdayName(weekdayNarrow, wd)}
                </span>
              {/each}
            </div>
            {#each monthMatrix(gm.year, gm.month, $calState.weekStartsOn) as week, w (w)}
              {#if week.some((c) => c.month === gm.month)}
                <div class="calendar__row calendar__mini-week" use:rowAction>
                  {#each week as cell (cell.date)}
                    {#if cell.month !== gm.month}
                      <div class="calendar__cell calendar__cell--blank" aria-hidden="true"></div>
                    {:else}
                      <div class="calendar__cell" use:cellAction={cell.date}>
                        <button
                          class="calendar__mini-day"
                          use:dayAction={cell.date}
                          aria-label={dayFmt.format(dt(cell.date))}
                        >
                          {cell.day}
                        </button>
                      </div>
                    {/if}
                  {/each}
                </div>
              {/if}
            {/each}
          </div>
        </section>
      {/each}
    </div>
  {:else}
    <div
      class="calendar__agenda"
      use:gridAction
      aria-label={label ?? $t("calendar.label")}
      data-cols={agendaDays.length}
    >
      <div class="calendar__row calendar__agenda-row" role="row" use:rowAction>
        {#each agendaDays as cell (cell.date)}
          {@const dayEvents = eventsByDate[cell.date] ?? []}
          {@const price = prices[cell.date]}
          <div class="calendar__cell calendar__agenda-col" use:cellAction={cell.date}>
            <button
              class="calendar__agenda-head"
              use:dayAction={cell.date}
              aria-label={dayAria(cell.date, dayEvents.length, price)}
            >
              <span class="calendar__agenda-weekday">{weekdayName(weekdayShort, cell.weekday)}</span
              >
              <span class="calendar__agenda-num">{cell.day}</span>
            </button>
            <ul class="calendar__agenda-events">
              {#each dayEvents as ev (ev.label ?? ev.date)}
                <li class="calendar__event">
                  <span class="calendar__dot" data-tone={ev.tone ?? "primary"} aria-hidden="true"
                  ></span>
                  <span class="calendar__event-label">{ev.label}</span>
                </li>
              {/each}
              {#if price}<li class="calendar__agenda-price">{price}</li>{/if}
              {#if !dayEvents.length && !price}
                <li class="calendar__agenda-empty" aria-hidden="true">—</li>
              {/if}
            </ul>
          </div>
        {/each}
      </div>
    </div>
  {/if}
</section>

<style>
  .calendar {
    inline-size: 100%;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    color: var(--ds-color-text, #0f172a);
  }

  .calendar__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
    flex-wrap: wrap;
  }
  .calendar__title {
    margin: 0;
    font-size: var(--ds-calendar-title-size, 1.125rem);
    font-weight: 600;
    text-transform: capitalize;
  }
  .calendar__controls {
    display: inline-flex;
    align-items: center;
    gap: 0.75rem;
    flex-wrap: wrap;
  }
  .calendar__nav {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
  }
  .calendar__today {
    font: inherit;
    padding: 0.35rem 0.75rem;
    margin-inline-end: 0.25rem;
    color: inherit;
    background: var(--ds-color-surface, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-radius-control, 0.375rem);
    cursor: pointer;
  }
  .calendar__arrow {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    inline-size: 2rem;
    block-size: 2rem;
    color: inherit;
    background: none;
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-radius-control, 0.375rem);
    cursor: pointer;
  }
  .calendar__today:focus-visible,
  .calendar__arrow:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }

  .calendar__months {
    display: flex;
    gap: 1.5rem;
    flex-wrap: wrap;
  }
  .calendar__month {
    flex: 1 1 16rem;
    min-inline-size: 15rem;
  }
  .calendar__month-title {
    margin: 0 0 0.5rem;
    font-size: 0.95rem;
    font-weight: 600;
    text-align: center;
    text-transform: capitalize;
  }

  .calendar__row {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: var(--ds-calendar-gap, 0.25rem);
  }
  .calendar__weekdays {
    margin-block-end: 0.25rem;
  }
  .calendar__weekday {
    text-align: center;
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--ds-color-text-secondary, #64748b);
    text-transform: uppercase;
    padding-block: 0.25rem;
  }

  .calendar__cell {
    display: flex;
  }
  .calendar__cell--blank {
    visibility: hidden;
  }
  .calendar__day {
    inline-size: 100%;
    min-block-size: var(--ds-calendar-day-size, 3rem);
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.15rem;
    padding: 0.3rem;
    font: inherit;
    color: inherit;
    background: var(--ds-calendar-day-bg, transparent);
    border: 1px solid transparent;
    border-radius: var(--ds-calendar-day-radius, var(--ds-radius-control, 0.375rem));
    cursor: pointer;
  }
  .calendar__day:hover {
    background: var(--ds-calendar-day-hover, var(--ds-color-neutral-surface, #f1f5f9));
  }
  .calendar__day:focus-visible {
    outline: none;
    border-color: var(--ds-color-focus-ring, #2563eb);
    box-shadow: var(--ds-focus-ring-shadow);
  }
  .calendar__day--outside {
    color: var(--ds-color-text-secondary, #94a3b8);
    opacity: 0.6;
  }
  .calendar__day:global([data-today]) .calendar__daynum {
    font-weight: 700;
    color: var(--ds-calendar-today, var(--ds-color-primary, #2563eb));
  }
  .calendar__day:global([data-selected]) {
    background: var(--ds-calendar-selected-bg, var(--ds-color-primary, #2563eb));
    color: var(--ds-calendar-selected-text, #fff);
  }
  .calendar__day:global([data-selected]) .calendar__daynum {
    color: inherit;
  }
  .calendar__day:global([data-disabled]) {
    opacity: 0.35;
    cursor: not-allowed;
  }
  /* Range mode: endpoints look selected; days between get a soft band. */
  .calendar__day[data-range-start],
  .calendar__day[data-range-end] {
    background: var(--ds-calendar-selected-bg, var(--ds-color-primary, #2563eb));
    color: var(--ds-calendar-selected-text, #fff);
  }
  .calendar__day[data-range-start] .calendar__daynum,
  .calendar__day[data-range-end] .calendar__daynum {
    color: inherit;
  }
  .calendar__day[data-in-range] {
    background: var(--ds-calendar-range-band, rgba(37, 99, 235, 0.12));
    border-radius: 0;
  }

  .calendar__daynum {
    font-size: 0.9rem;
    line-height: 1.4;
  }
  .calendar__dots {
    display: inline-flex;
    align-items: center;
    gap: 0.15rem;
    min-block-size: 0.4rem;
  }
  .calendar__dot {
    inline-size: 0.4rem;
    block-size: 0.4rem;
    border-radius: 50%;
    background: var(--ds-calendar-dot, var(--ds-color-primary, #2563eb));
    flex: none;
  }
  .calendar__dot[data-tone="success"] {
    background: var(--ds-color-success, #16a34a);
  }
  .calendar__dot[data-tone="warning"] {
    background: var(--ds-color-warning, #d97706);
  }
  .calendar__dot[data-tone="danger"] {
    background: var(--ds-color-danger, #dc2626);
  }
  .calendar__dot[data-tone="neutral"] {
    background: var(--ds-color-text-secondary, #64748b);
  }
  .calendar__more {
    font-size: 0.65rem;
    color: var(--ds-color-text-secondary, #64748b);
  }
  .calendar__price {
    font-size: 0.7rem;
    font-weight: 600;
    color: var(--ds-calendar-price, var(--ds-color-success-body-text, #15803d));
  }
  .calendar__day:global([data-selected]) .calendar__price,
  .calendar__day:global([data-selected]) .calendar__more {
    color: inherit;
  }

  /* ---- Year view (simplified mini-months, stacked) ---- */
  .calendar__year {
    display: grid;
    grid-template-columns: repeat(var(--year-cols, 1), minmax(0, 1fr));
    gap: 1.25rem;
  }
  .calendar__mini {
    min-inline-size: 0;
  }
  .calendar__mini-title {
    display: block;
    inline-size: 100%;
    margin-block-end: 0.4rem;
    padding: 0.2rem 0.4rem;
    font: inherit;
    font-weight: 600;
    text-align: start;
    text-transform: capitalize;
    color: inherit;
    background: none;
    border: 0;
    border-radius: var(--ds-radius-control, 0.375rem);
    cursor: pointer;
  }
  .calendar__mini-title:hover {
    color: var(--ds-color-primary, #2563eb);
  }
  .calendar__mini-title:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }
  .calendar__mini-grid {
    display: flex;
    flex-direction: column;
    gap: 0.1rem;
  }
  .calendar__mini-week,
  .calendar__mini-weekdays {
    gap: 0.1rem;
  }
  .calendar__mini-weekday {
    text-align: center;
    font-size: 0.65rem;
    color: var(--ds-color-text-secondary, #94a3b8);
  }
  .calendar__mini-day {
    inline-size: 100%;
    aspect-ratio: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    font: inherit;
    font-size: 0.72rem;
    color: inherit;
    background: none;
    border: 0;
    border-radius: 50%;
    cursor: pointer;
  }
  .calendar__mini-day:hover {
    background: var(--ds-calendar-day-hover, var(--ds-color-neutral-surface, #f1f5f9));
  }
  .calendar__mini-day:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: -1px;
  }
  .calendar__mini-day:global([data-today]) {
    color: var(--ds-calendar-today, var(--ds-color-primary, #2563eb));
    font-weight: 700;
  }
  .calendar__mini-day:global([data-selected]) {
    background: var(--ds-calendar-selected-bg, var(--ds-color-primary, #2563eb));
    color: var(--ds-calendar-selected-text, #fff);
  }

  /* ---- Agenda views (week / three-day / day) ---- */
  .calendar__agenda-row {
    grid-template-columns: repeat(var(--cols, 7), 1fr);
    gap: var(--ds-calendar-gap, 0.25rem);
    align-items: stretch;
  }
  .calendar__agenda[data-cols="3"] .calendar__agenda-row {
    --cols: 3;
  }
  .calendar__agenda[data-cols="1"] .calendar__agenda-row {
    --cols: 1;
  }
  .calendar__agenda-col {
    flex-direction: column;
    border: 1px solid var(--ds-color-border, #e2e8f0);
    border-radius: var(--ds-radius-surface, 0.5rem);
    overflow: hidden;
  }
  .calendar__agenda-head {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.1rem;
    padding: 0.4rem;
    font: inherit;
    color: inherit;
    background: var(--ds-color-neutral-surface, #f8fafc);
    border: 0;
    border-block-end: 1px solid var(--ds-color-border, #e2e8f0);
    cursor: pointer;
  }
  .calendar__agenda-head:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: -2px;
  }
  .calendar__agenda-head:global([data-selected]) {
    background: var(--ds-calendar-selected-bg, var(--ds-color-primary, #2563eb));
    color: var(--ds-calendar-selected-text, #fff);
  }
  .calendar__agenda-head:global([data-today]) .calendar__agenda-num {
    color: var(--ds-calendar-today, var(--ds-color-primary, #2563eb));
    font-weight: 700;
  }
  .calendar__agenda-head:global([data-selected]) .calendar__agenda-num {
    color: inherit;
  }
  .calendar__agenda-weekday {
    font-size: 0.7rem;
    text-transform: uppercase;
    color: var(--ds-color-text-secondary, #64748b);
  }
  .calendar__agenda-head:global([data-selected]) .calendar__agenda-weekday {
    color: inherit;
  }
  .calendar__agenda-num {
    font-size: 1.1rem;
    font-weight: 600;
  }
  .calendar__agenda-events {
    list-style: none;
    margin: 0;
    padding: 0.4rem;
    display: flex;
    flex-direction: column;
    gap: 0.3rem;
    min-block-size: var(--ds-calendar-agenda-min, 6rem);
  }
  .calendar__event {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    font-size: 0.8rem;
  }
  .calendar__event-label {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .calendar__agenda-price {
    margin-block-start: auto;
    font-size: 0.75rem;
    font-weight: 600;
    color: var(--ds-calendar-price, var(--ds-color-success, #15803d));
  }
  .calendar__agenda-empty {
    color: var(--ds-color-text-secondary, #cbd5e1);
    text-align: center;
  }
</style>

// packages/react/src/calendar/Calendar.tsx
import { calendar as core, i18n as coreI18n } from "@design-system/core";
import { useMemo, type CSSProperties, type ReactNode } from "react";
import { useI18n, type TranslateFn } from "../i18n/i18n";
import type { MessageKey } from "../i18n/messages";
import { ChevronEndGlyph, ChevronStartGlyph, Icon } from "../icon/Icon";
import { cx } from "../internal/cx";
import { localDate } from "../internal/date";
import { SegmentedControl } from "../segmented-control/SegmentedControl";
import {
  useCalendar,
  type CalendarMode,
  type CalendarView,
  type UseCalendar,
  type WeekStart,
} from "./use-calendar";

/** An appointment on a given day, shown as a colored dot. */
export interface CalendarEvent {
  /** ISO `YYYY-MM-DD`. */
  date: string;
  /** Accessible description, also shown as a tooltip. */
  label?: string;
  /** Semantic tone for the dot. */
  tone?: "primary" | "success" | "warning" | "danger" | "neutral";
}

/** What `renderDay` receives for each day of the grid views. */
export interface CalendarDayContext {
  /** ISO `YYYY-MM-DD`. */
  date: string;
  /** Whether the day belongs to the month shown. */
  inMonth: boolean;
  /** Whether the day is the selected one. */
  selected: boolean;
  /** The day's events. */
  events: CalendarEvent[];
  /** The day's price label, if any. */
  price: string | undefined;
}

export interface CalendarProps {
  /** Initial (uncontrolled) or current (controlled) selected date, ISO `YYYY-MM-DD`. */
  value?: string | null;
  /** The date that drives what is shown and where focus sits. */
  focusedDate?: string;
  /** Initial (uncontrolled) or current (controlled) view. */
  view?: CalendarView;
  /** First day of the week, 0 = Sunday to 6. */
  weekStartsOn?: WeekStart;
  /** Earliest selectable date (ISO), inclusive. */
  min?: string;
  /** Latest selectable date (ISO), inclusive. */
  max?: string;
  /** BCP-47 locale for month and weekday names. Defaults to the provider's locale. */
  locale?: string;
  /** Appointment dots, keyed by their `date`. */
  events?: CalendarEvent[];
  /** Per-day price label, keyed by ISO date (e.g. `{ "2026-06-25": "€120" }`). */
  prices?: Record<string, string>;
  /** Maximum dots rendered before a "+N" overflow marker (grid views). */
  maxDots?: number;
  /** Year view: how many mini-months per row. */
  yearColumns?: number;
  /** Views offered in the built-in switcher. With one entry no switcher shows. */
  views?: CalendarView[];
  /** Override the switcher labels per view. */
  viewLabels?: Partial<Record<CalendarView, string>>;
  showToday?: boolean;
  /** Label of the previous button. Defaults to the catalog's. */
  prevLabel?: string;
  /** Label of the next button. Defaults to the catalog's. */
  nextLabel?: string;
  /** Text of the Today button. Defaults to the catalog's. */
  todayLabel?: string;
  /** Name of the view switcher. Defaults to the catalog's. */
  viewsLabel?: string;
  /** Accessible name for the grid. Defaults to the catalog's. */
  label?: string;
  /** Selection mode: a single date, or a start-to-end `range`. */
  mode?: CalendarMode;
  /** Range start (ISO), used when `mode="range"`. */
  rangeStart?: string | null;
  /** Range end (ISO), used when `mode="range"`. */
  rangeEnd?: string | null;
  /** Called when the user selects a date (single mode). */
  onValueChange?: (value: string) => void;
  /** Called when the user moves the focused date. */
  onFocusChange?: (value: string) => void;
  /** Called when the user changes the view. */
  onViewChange?: (view: CalendarView) => void;
  /** Called after each pick in range mode, with a `null` end while the range is half made. */
  onRangeChange?: (start: string | null, end: string | null) => void;
  /** Custom content of a day in the grid views, replacing the number, dots and price. */
  renderDay?: (day: CalendarDayContext) => ReactNode;
}

type Month = { year: number; month: number };

const NO_EVENTS: CalendarEvent[] = [];

// Local dates, like `localDate`: the formatters read local time, and a UTC
// midnight is the day before west of Greenwich.
/** A reference Sunday, so a weekday name can be rendered from an index. */
const weekdayName = (fmt: Intl.DateTimeFormat, weekday: number) =>
  fmt.format(new Date(2024, 0, 7 + weekday));

const monthDate = ({ year, month }: Month) => new Date(year, month - 1, 1);

/** The formatters a calendar renders with, cached by the core per locale. */
function formatters(locale: string) {
  const fmt = (options: Intl.DateTimeFormatOptions) => coreI18n.dateTimeFormat(locale, options);
  return {
    title: fmt({ month: "long", year: "numeric" }),
    range: fmt({ day: "numeric", month: "short", year: "numeric" }),
    day: fmt({ weekday: "long", day: "numeric", month: "long", year: "numeric" }),
    year: fmt({ year: "numeric" }),
    month: fmt({ month: "long" }),
    short: fmt({ weekday: "short" }),
    long: fmt({ weekday: "long" }),
    narrow: fmt({ weekday: "narrow" }),
  };
}

type Formatters = ReturnType<typeof formatters>;

/** A weekday column header: its index and its names. */
interface Weekday {
  weekday: WeekStart;
  long: string;
  short: string;
  narrow: string;
}

/** The consecutive days an agenda view shows. */
const agendaDays = (view: CalendarView, focused: string, weekStartsOn: WeekStart) =>
  view === "week"
    ? core.weekDays(focused, weekStartsOn)
    : core.rangeDays(focused, view === "three-day" ? 3 : 1);

function periodTitle(view: CalendarView, focused: string, weekStartsOn: WeekStart, f: Formatters) {
  switch (view) {
    case "year":
      return f.year.format(localDate(focused));
    case "day":
      return f.day.format(localDate(focused));
    case "week":
    case "three-day": {
      const days = agendaDays(view, focused, weekStartsOn);
      return f.range.formatRange(localDate(days[0]!.date), localDate(days.at(-1)!.date));
    }
    case "two-month": {
      const start = core.startOfMonth(focused);
      return f.title.formatRange(localDate(start), localDate(core.addMonths(start, 1)));
    }
    default:
      return f.title.format(localDate(focused));
  }
}

/**
 * Calendar: the styled calendar (WAI-ARIA date grid). Behaviour, date math and
 * keyboard navigation come from the headless calendar (`useCalendar`); this
 * layer adds the header (period title, an optional view switcher,
 * previous/next/today) and a body per view: `month`, `two-month`, `week`,
 * `three-day` and `day` (the last three are day-column agendas), and `year`
 * (twelve mini-months). Each day can show appointment dots (`events`) and a
 * price (`prices`), or custom content through `renderDay`.
 *
 * In `mode="range"` the first pick sets the start and the next the end; every
 * day of the range is a selected cell, and the endpoints say so in their name.
 * The value, the range, the focused date and the view are controllable mirrors
 * (ADR 0011). Month and weekday names come from `Intl` for the locale.
 * Themeable via `--ds-calendar-*`.
 */
export function Calendar({
  value = null,
  focusedDate,
  view = "month",
  weekStartsOn = 1,
  min,
  max,
  locale,
  events,
  prices = {},
  maxDots = 3,
  yearColumns = 1,
  views = ["month"],
  viewLabels = {},
  showToday = true,
  prevLabel,
  nextLabel,
  todayLabel,
  viewsLabel,
  label,
  mode = "single",
  rangeStart = null,
  rangeEnd = null,
  onValueChange,
  onFocusChange,
  onViewChange,
  onRangeChange,
  renderDay,
}: CalendarProps) {
  const i18n = useI18n();
  const { t } = i18n;
  const api = useCalendar({
    value,
    focusedDate,
    view,
    weekStartsOn,
    min,
    max,
    mode,
    rangeStart,
    rangeEnd,
    onValueChange,
    onFocusChange,
    onViewChange,
    onRangeChange,
  });
  const resolvedLocale = locale ?? i18n.locale;
  // Rendering a grid formats every day; the formatters, the weekday names and
  // the events by day are kept between renders that do not change them.
  const f = useMemo(() => formatters(resolvedLocale), [resolvedLocale]);
  const current = api.view;
  const focused = api.focusedDate;

  const byDate = useMemo(() => {
    const map = new Map<string, CalendarEvent[]>();
    for (const event of events ?? NO_EVENTS) {
      const list = map.get(event.date);
      if (list) list.push(event);
      else map.set(event.date, [event]);
    }
    return map;
  }, [events]);
  const weekdays = useMemo(
    () =>
      core.weekdayOrder(api.weekStartsOn).map((weekday) => ({
        weekday,
        long: weekdayName(f.long, weekday),
        short: weekdayName(f.short, weekday),
        narrow: weekdayName(f.narrow, weekday),
      })),
    [f, api.weekStartsOn],
  );

  const switcherItems = views.map((entry) => ({
    value: entry,
    label: viewLabels[entry] ?? t(`calendar.view.${entry}` as MessageKey),
  }));
  // The arrows point along the reading direction.
  const rtl = i18n.dir === "rtl";
  const body: BodyProps = {
    api,
    f,
    t,
    byDate,
    weekdays,
    prices,
    maxDots,
    gridLabel: label ?? t("calendar.label"),
    renderDay,
  };

  return (
    <section className="calendar" data-view={current} data-mode={mode}>
      <header className="calendar__header">
        <h2 className="calendar__title" aria-live="polite">
          {periodTitle(current, focused, api.weekStartsOn, f)}
        </h2>
        <div className="calendar__controls">
          {switcherItems.length > 1 ? (
            <SegmentedControl
              items={switcherItems}
              value={current}
              label={viewsLabel ?? t("calendar.viewsLabel")}
              onValueChange={(next) => api.setView(next as CalendarView)}
            />
          ) : null}
          <div className="calendar__nav">
            {showToday ? (
              <button type="button" className="calendar__today" onClick={api.goToday}>
                {todayLabel ?? t("calendar.today")}
              </button>
            ) : null}
            <button
              type="button"
              className="calendar__arrow"
              aria-label={prevLabel ?? t("calendar.previous")}
              onClick={api.goPrev}
            >
              <Icon size="1.25rem">{rtl ? <ChevronEndGlyph /> : <ChevronStartGlyph />}</Icon>
            </button>
            <button
              type="button"
              className="calendar__arrow"
              aria-label={nextLabel ?? t("calendar.next")}
              onClick={api.goNext}
            >
              <Icon size="1.25rem">{rtl ? <ChevronStartGlyph /> : <ChevronEndGlyph />}</Icon>
            </button>
          </div>
        </div>
      </header>
      {current === "month" || current === "two-month" ? (
        <MonthBody {...body} />
      ) : current === "year" ? (
        <YearBody {...body} columns={yearColumns} />
      ) : (
        <AgendaBody {...body} />
      )}
    </section>
  );
}

interface BodyProps {
  api: UseCalendar;
  f: Formatters;
  t: TranslateFn;
  byDate: Map<string, CalendarEvent[]>;
  weekdays: Weekday[];
  prices: Record<string, string>;
  maxDots: number;
  gridLabel: string;
  renderDay: CalendarProps["renderDay"];
}

/** A day's full date, then its events, its price and its place in a range. */
function dayLabel({ api, f, t, byDate, prices }: BodyProps, iso: string) {
  const count = (byDate.get(iso) ?? NO_EVENTS).length;
  const price = prices[iso];
  let text = f.day.format(localDate(iso));
  if (count) text += `, ${t("calendar.events", { count })}`;
  if (price) text += `, ${price}`;
  if (api.mode === "range") {
    if (iso === api.rangeStart) text += `, ${t("calendar.rangeStart")}`;
    if (iso === api.rangeEnd) text += `, ${t("calendar.rangeEnd")}`;
  }
  return text;
}

function WeekdayRow({ weekdays, narrow }: { weekdays: Weekday[]; narrow?: boolean }) {
  const prefix = narrow ? "calendar__mini-weekday" : "calendar__weekday";
  return (
    <div
      className={`calendar__row ${narrow ? "calendar__mini-weekdays" : "calendar__weekdays"}`}
      role="row"
    >
      {weekdays.map((day) => (
        <span key={day.weekday} className={prefix} role="columnheader" aria-label={day.long}>
          {narrow ? day.narrow : day.short}
        </span>
      ))}
    </div>
  );
}

const blankCell = (key: string) => (
  <div key={key} className="calendar__cell calendar__cell--blank" aria-hidden="true" />
);

/** An event's dot, in its tone. */
const Dot = ({ event }: { event: CalendarEvent }) => (
  <span className="calendar__dot" data-tone={event.tone ?? "primary"} title={event.label} />
);

function Dots({ events, maxDots }: { events: CalendarEvent[]; maxDots: number }) {
  return (
    <span className="calendar__dots" aria-hidden="true">
      {/* Events carry no id and two on one day may share a label, so their
          position is their key. */}
      {events.slice(0, maxDots).map((event, index) => (
        <Dot key={index} event={event} />
      ))}
      {events.length > maxDots ? (
        <span className="calendar__more">+{events.length - maxDots}</span>
      ) : null}
    </span>
  );
}

function MonthBody(props: BodyProps) {
  const { api, f, byDate, prices, maxDots, gridLabel, renderDay } = props;
  const twoMonth = api.view === "two-month";
  const ref = core.describe(api.focusedDate);
  const months: Month[] = [{ year: ref.year, month: ref.month }];
  if (twoMonth) {
    const next = core.describe(core.addMonths(api.focusedDate, 1));
    months.push({ year: next.year, month: next.month });
  }

  return (
    <div className="calendar__months">
      {months.map((month) => {
        const monthLabel = f.title.format(monthDate(month));
        return (
          <div className="calendar__month" key={`${month.year}-${month.month}`}>
            {twoMonth ? <h3 className="calendar__month-title">{monthLabel}</h3> : null}
            <div
              {...api.gridProps}
              className="calendar__grid"
              aria-label={twoMonth ? monthLabel : gridLabel}
            >
              <WeekdayRow weekdays={props.weekdays} />
              {core.monthMatrix(month.year, month.month, api.weekStartsOn).map((week, w) =>
                // Two months side by side show each day once, in its own month.
                twoMonth && !week.some((day) => day.month === month.month) ? null : (
                  <div {...api.rowProps} key={w} className="calendar__row calendar__week">
                    {week.map((cell) => {
                      const inMonth = cell.month === month.month;
                      if (twoMonth && !inMonth) return blankCell(cell.date);
                      const dayEvents = byDate.get(cell.date) ?? NO_EVENTS;
                      const price = prices[cell.date];
                      return (
                        <div
                          {...api.getCellProps(cell.date)}
                          key={cell.date}
                          className="calendar__cell"
                        >
                          <button
                            {...api.getDayProps(cell.date)}
                            className={cx("calendar__day", !inMonth && "calendar__day--outside")}
                            aria-label={dayLabel(props, cell.date)}
                          >
                            {renderDay ? (
                              renderDay({
                                date: cell.date,
                                inMonth,
                                selected: api.value === cell.date,
                                events: dayEvents,
                                price,
                              })
                            ) : (
                              <>
                                <span className="calendar__daynum">{cell.day}</span>
                                {dayEvents.length ? (
                                  <Dots events={dayEvents} maxDots={maxDots} />
                                ) : null}
                                {price ? <span className="calendar__price">{price}</span> : null}
                              </>
                            )}
                          </button>
                        </div>
                      );
                    })}
                  </div>
                ),
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function YearBody({ api, f, weekdays, columns }: BodyProps & { columns: number }) {
  const year = core.describe(api.focusedDate).year;
  // The column count is the consumer's number; one column needs no override.
  const style = columns === 1 ? undefined : ({ "--year-cols": columns } as CSSProperties);
  return (
    <div className="calendar__year" style={style}>
      {core.monthsOfYear(year).map((month) => {
        const name = f.month.format(monthDate(month));
        return (
          <section className="calendar__mini" key={month.month}>
            <button
              type="button"
              className="calendar__mini-title"
              onClick={() => {
                api.setFocus(core.toISO(month.year, month.month, 1));
                api.setView("month");
              }}
            >
              {name}
            </button>
            <div {...api.gridProps} className="calendar__mini-grid" aria-label={name}>
              <WeekdayRow weekdays={weekdays} narrow />
              {core.monthMatrix(month.year, month.month, api.weekStartsOn).map((week, w) =>
                week.some((day) => day.month === month.month) ? (
                  <div {...api.rowProps} key={w} className="calendar__row calendar__mini-week">
                    {week.map((cell) =>
                      cell.month === month.month ? (
                        <div
                          {...api.getCellProps(cell.date)}
                          key={cell.date}
                          className="calendar__cell"
                        >
                          <button
                            {...api.getDayProps(cell.date)}
                            className="calendar__mini-day"
                            aria-label={f.day.format(localDate(cell.date))}
                          >
                            {cell.day}
                          </button>
                        </div>
                      ) : (
                        blankCell(cell.date)
                      ),
                    )}
                  </div>
                ) : null,
              )}
            </div>
          </section>
        );
      })}
    </div>
  );
}

function AgendaBody(props: BodyProps) {
  const { api, f, byDate, prices, gridLabel } = props;
  const days = agendaDays(api.view, api.focusedDate, api.weekStartsOn);

  return (
    <div
      {...api.gridProps}
      className="calendar__agenda"
      aria-label={gridLabel}
      data-cols={days.length}
    >
      <div {...api.rowProps} className="calendar__row calendar__agenda-row">
        {days.map((cell) => {
          const dayEvents = byDate.get(cell.date) ?? NO_EVENTS;
          const price = prices[cell.date];
          return (
            <div
              {...api.getCellProps(cell.date)}
              key={cell.date}
              className="calendar__cell calendar__agenda-col"
            >
              <button
                {...api.getDayProps(cell.date)}
                className="calendar__agenda-head"
                aria-label={dayLabel(props, cell.date)}
              >
                <span className="calendar__agenda-weekday">
                  {weekdayName(f.short, cell.weekday)}
                </span>
                <span className="calendar__agenda-num">{cell.day}</span>
              </button>
              <ul className="calendar__agenda-events">
                {/* Events carry no id and two on one day may share a label, so
                    their position is their key. */}
                {dayEvents.map((event, index) => (
                  <li key={index} className="calendar__event">
                    <span
                      className="calendar__dot"
                      data-tone={event.tone ?? "primary"}
                      aria-hidden="true"
                    />
                    <span className="calendar__event-label">{event.label}</span>
                  </li>
                ))}
                {price ? <li className="calendar__agenda-price">{price}</li> : null}
                {!dayEvents.length && !price ? (
                  <li className="calendar__agenda-empty" aria-hidden="true">
                    —
                  </li>
                ) : null}
              </ul>
            </div>
          );
        })}
      </div>
    </div>
  );
}
