// packages/svelte/src/lib/login-form/LoginForm.svelte
<script lang="ts">
  /**
   * LoginForm — a sign-in organism composed from the primitives: an optional
   * logo (slot) on top, optional social-login buttons, the email + password
   * fields, a "forgot password" link, and the submit button.
   *
   * It is a real `<form>`: the fields are native inputs (via TextField) and
   * `onSubmit` receives `{ email, password }`. Presentation is a centered card;
   * themeable via `--ds-login-*` and the underlying component tokens.
   */
  import TextField from "../text-field/TextField.svelte";
  import Button from "../button/Button.svelte";

  export let heading = "Sign in";
  export let subheading: string | undefined = undefined;
  export let submitLabel = "Sign in";
  export let forgotHref: string | undefined = "#";
  export let forgotLabel = "Forgot password?";
  /** Social providers rendered as white buttons above the fields. */
  export let providers: { id: string; label: string }[] = [];
  export let onSubmit: ((value: { email: string; password: string }) => void) | undefined =
    undefined;
  export let onProvider: ((id: string) => void) | undefined = undefined;

  let email = "";
  let password = "";

  function submit(event: SubmitEvent) {
    event.preventDefault();
    onSubmit?.({ email, password });
  }
</script>

<form class="login" on:submit={submit}>
  {#if $$slots.logo}
    <div class="login__logo"><slot name="logo" /></div>
  {/if}

  <div class="login__head">
    <h2 class="login__heading">{heading}</h2>
    {#if subheading}<p class="login__subheading">{subheading}</p>{/if}
  </div>

  {#if providers.length}
    <div class="login__providers">
      {#each providers as p (p.id)}
        <Button variant="default" onpress={() => onProvider?.(p.id)}>
          <svelte:fragment slot="left"
            ><slot name="provider-icon" provider={p.id} /></svelte:fragment
          >
          Continue with {p.label}
        </Button>
      {/each}
    </div>
    <div class="login__divider"><span>or</span></div>
  {/if}

  <TextField
    label="Email"
    type="email"
    name="email"
    placeholder="you@example.com"
    bind:value={email}
  />

  <div class="login__field">
    <TextField label="Password" type="password" name="password" bind:value={password} />
    {#if forgotHref}
      <a class="login__forgot" href={forgotHref}>{forgotLabel}</a>
    {/if}
  </div>

  <Button variant="primary" type="submit">{submitLabel}</Button>
</form>

<style>
  .login {
    display: flex;
    flex-direction: column;
    gap: var(--ds-login-gap, 1rem);
    inline-size: min(100%, var(--ds-login-width, 22rem));
    padding: var(--ds-login-padding, 1.75rem);
    background: var(--ds-login-bg, var(--ds-color-background, #fff));
    border: 1px solid var(--ds-login-border, var(--ds-color-border, #e7e5e4));
    border-radius: var(--ds-login-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(--ds-login-shadow, var(--ds-elevation-overlay, 0 1px 3px rgb(0 0 0 / 0.1)));
  }
  .login__logo {
    display: flex;
    justify-content: center;
  }
  .login__head {
    text-align: center;
  }
  .login__heading {
    margin: 0;
    font-size: 1.25rem;
    color: var(--ds-color-text, #1c1917);
  }
  .login__subheading {
    margin: 0.25rem 0 0;
    font-size: 0.875rem;
    color: var(--ds-color-text-secondary, #57534e);
  }
  .login__providers {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .login__divider {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    color: var(--ds-color-text-secondary, #78716c);
    font-size: 0.8125rem;
  }
  .login__divider::before,
  .login__divider::after {
    content: "";
    flex: 1;
    block-size: 1px;
    background: var(--ds-color-border, #e7e5e4);
  }
  .login__field {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }
  .login__forgot {
    align-self: flex-end;
    font-size: 0.8125rem;
    color: var(--ds-color-secondary, #7b52cc);
  }
</style>

// packages/react/src/login-form/LoginForm.tsx
import type { FormEvent, ReactNode } from "react";
import { Button } from "../button/Button";
import { useI18n } from "../i18n/i18n";
import { TextField } from "../text-field/TextField";

/** A social sign-in provider, rendered as a button above the fields. */
export interface LoginFormProvider {
  id: string;
  label: string;
}

/** What `onSubmit` receives. */
export interface LoginFormValue {
  email: string;
  password: string;
}

export interface LoginFormProps {
  /** The card's heading. Defaults to the catalog's "Sign in". */
  heading?: string;
  subheading?: string;
  /** Submit button label. Defaults to the catalog's "Sign in". */
  submitLabel?: string;
  /** Where the forgot-password link goes. An empty string leaves the link out. */
  forgotHref?: string;
  /** Forgot-password link text. Defaults to the catalog's "Forgot password?". */
  forgotLabel?: string;
  /** Social providers rendered as buttons above the fields. */
  providers?: LoginFormProvider[];
  /** Called with the typed credentials when the form is submitted. */
  onSubmit?: (value: LoginFormValue) => void;
  /** Called with the provider id when a provider button is pressed. */
  onProvider?: (id: string) => void;
  /** A logo shown on top of the card. */
  logo?: ReactNode;
  /** The icon of a provider button, given the provider id. */
  renderProviderIcon?: (provider: string) => ReactNode;
}

const EMPTY: never[] = [];

/**
 * LoginForm: a sign-in form composed from the primitives: an optional logo on
 * top, optional social sign-in buttons, the email and password fields, a
 * "forgot password" link, and the submit button.
 *
 * It is a real `<form>`: the fields are native inputs (through TextField), and
 * `onSubmit` receives `{ email, password }` read from the form itself, so a
 * form reset leaves nothing stale behind. Presentation is a centered card;
 * themeable via `--ds-login-*` and the underlying component tokens.
 */
export function LoginForm({
  heading,
  subheading,
  submitLabel,
  forgotHref = "#",
  forgotLabel,
  providers = EMPTY,
  onSubmit,
  onProvider,
  logo,
  renderProviderIcon,
}: LoginFormProps) {
  const { t } = useI18n();

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    onSubmit?.({
      email: String(data.get("email") ?? ""),
      password: String(data.get("password") ?? ""),
    });
  };

  return (
    <form className="login" onSubmit={submit}>
      {logo != null ? <div className="login__logo">{logo}</div> : null}

      <div className="login__head">
        <h2 className="login__heading">{heading ?? t("loginForm.heading")}</h2>
        {subheading ? <p className="login__subheading">{subheading}</p> : null}
      </div>

      {providers.length > 0 ? (
        <>
          <div className="login__providers">
            {providers.map((provider) => (
              <Button
                key={provider.id}
                variant="default"
                onPress={() => onProvider?.(provider.id)}
                left={renderProviderIcon?.(provider.id)}
              >
                {t("loginForm.provider", { name: provider.label })}
              </Button>
            ))}
          </div>
          <div className="login__divider">
            <span>{t("loginForm.divider")}</span>
          </div>
        </>
      ) : null}

      <TextField
        label={t("loginForm.email")}
        type="email"
        name="email"
        placeholder={t("loginForm.emailPlaceholder")}
      />

      <div className="login__field">
        <TextField label={t("loginForm.password")} type="password" name="password" />
        {forgotHref ? (
          <a className="login__forgot" href={forgotHref}>
            {forgotLabel ?? t("loginForm.forgot")}
          </a>
        ) : null}
      </div>

      <Button variant="primary" type="submit">
        {submitLabel ?? t("loginForm.submit")}
      </Button>
    </form>
  );
}
