// packages/react/src/radio/Radio.tsx
import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import { cx } from "../internal/cx";

export interface RadioProps {
  /** The value submitted / reported when this radio is chosen. */
  value: string;
  /** Group name; radios sharing a name are mutually exclusive. */
  name: string;
  /** Whether this radio is selected. */
  checked?: boolean;
  disabled?: boolean;
  /** Label text, used when no `children` is given. */
  label?: string;
  /** Called with this radio's value when it becomes selected. */
  onChange?: (value: string) => void;
  /** Rich label content, in place of `label`. */
  children?: ReactNode;
}

/**
 * Radio — a single styled radio button paired with its label. Built on a
 * native `<input type="radio">`, so several `Radio`s sharing the same `name`
 * form one group automatically (native keyboard, focus and form semantics);
 * use this when you lay the radios out yourself. For a managed group use
 * `RadioGroup`.
 *
 * The element is the whole state: the radios of one name live in separate
 * components, and only the browser sees all of them, so the input is left
 * uncontrolled and a changed `checked` is written to it. Colors are themeable
 * via `--ds-radio-*`.
 */
export function Radio({
  value,
  name,
  checked = false,
  disabled = false,
  label,
  onChange,
  children,
}: RadioProps) {
  const id = `ds-radio-${useId()}`;
  const ref = useRef<HTMLInputElement>(null);
  // The first render carries the default in markup; later ones go through the
  // effect below, so React never moves the attribute on its own.
  const [initial] = useState(checked);

  // A changed prop is reflected into the element. The reset default follows
  // it, except a give-back of what the element already shows: that is the
  // page echoing the user's choice, and an echo is not a new default
  // (ADR 0012). The `checked` attribute alone carries the reset; there is
  // nothing else to put back.
  useEffect(() => {
    const node = ref.current;
    if (!node || node.checked === checked) return;
    node.defaultChecked = checked;
    node.checked = checked;
  }, [checked]);

  return (
    <label className={cx("radio", disabled && "radio--disabled")} htmlFor={id}>
      <input
        ref={ref}
        id={id}
        className="radio__input"
        type="radio"
        name={name}
        value={value}
        defaultChecked={initial}
        disabled={disabled}
        onChange={() => onChange?.(value)}
      />
      <span className="radio__dot" aria-hidden="true" />
      <span className="radio__label">{children ?? label}</span>
    </label>
  );
}

// packages/svelte/src/lib/radio/Radio.svelte
<script lang="ts">
  /**
   * Radio — a single styled radio button paired with its label. Built on a
   * native `<input type="radio">`, so several `Radio`s sharing the same `name`
   * form one group automatically (native keyboard, focus and form semantics);
   * use this when you want to lay out radios yourself. For a managed group with
   * roving tabindex use `RadioGroup`.
   *
   * The label is the default slot (falling back to the `label` prop). Colors are
   * themeable via `--ds-radio-*`.
   */
  import { stableId } from "../internal/stable-id";
  /** The value submitted / reported when this radio is chosen. */
  export let value: string;
  /** Group name; radios sharing a name are mutually exclusive. */
  export let name: string;
  /** Whether this radio is selected. */
  export let checked = false;
  export let disabled = false;
  /** Label text, used when the default slot is empty. */
  export let label: string | undefined = undefined;
  /** Called with this radio's value when it becomes selected. */
  export let onChange: ((value: string) => void) | undefined = undefined;

  const id = stableId("ds-radio");
</script>

<label class="radio" class:radio--disabled={disabled} for={id}>
  <input
    {id}
    class="radio__input"
    type="radio"
    {name}
    {value}
    {checked}
    {disabled}
    on:change={() => onChange?.(value)}
  />
  <span class="radio__dot" aria-hidden="true"></span>
  <span class="radio__label"><slot>{label}</slot></span>
</label>

<style>
  .radio {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    font: inherit;
    color: var(--ds-color-text, #282420);
    cursor: pointer;
  }
  .radio--disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  /* Hide the native control but keep it focusable and in the a11y tree. */
  .radio__input {
    position: absolute;
    inline-size: 1px;
    block-size: 1px;
    margin: -1px;
    padding: 0;
    border: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    white-space: nowrap;
  }
  .radio__dot {
    inline-size: var(--ds-radio-size, 1.1rem);
    block-size: var(--ds-radio-size, 1.1rem);
    border: 1px solid var(--ds-color-control-border, #757067);
    border-radius: 50%;
    display: inline-grid;
    place-content: center;
    flex: none;
  }
  .radio__input:checked + .radio__dot {
    border-color: var(--ds-color-secondary, #7a52cc);
  }
  .radio__input:checked + .radio__dot::after {
    content: "";
    inline-size: 0.6rem;
    block-size: 0.6rem;
    border-radius: 50%;
    background: var(--ds-color-secondary, #7a52cc);
  }
  .radio__input:focus-visible + .radio__dot {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }
</style>
