// packages/svelte/src/lib/dropdown-menu/DropdownMenu.svelte
<script lang="ts">
  /**
   * DropdownMenu — the styled, batteries-included menu button (WAI-ARIA menu
   * button pattern). A trigger opens a `role="menu"` of action items; behaviour
   * and accessibility (open/close, arrow & Home/End navigation, typeahead,
   * focus moving into the menu and returning to the trigger, Escape/outside to
   * close) come from the headless menu (`@design-system/core`). Popup
   * positioning (flip/shift, stays attached on scroll) is handled via
   * `@floating-ui/dom`.
   *
   * Pass `items` ({ value, label?, disabled? }) and an accessible `label` for
   * the trigger; `onSelect(value)` runs when an item is chosen. Colors, radius
   * and elevation are themeable CSS custom properties (`--ds-menu-*`).
   */
  import { createDropdownMenu, type MenuItem } from "./create-dropdown-menu";
  import { portal } from "../internal/portal";
  import Icon from "../icon/Icon.svelte";
  import { getI18n } from "../i18n/create-i18n";

  const { locale: i18nLocale, dir: i18nDir } = getI18n();

  export let label: string;
  export let items: MenuItem[];
  export let disabled = false;
  /** Called with the chosen item's value. */
  export let onSelect: ((value: string) => void) | undefined = undefined;

  const menu = createDropdownMenu({ items, disabled, onSelect });
  const { triggerAction, menuAction, itemAction } = menu;
</script>

<div class="menu">
  <button class="menu__trigger" type="button" use:triggerAction>
    <span>{label}</span>
    <span class="menu__chevron" aria-hidden="true">
      <Icon size="100%"><polyline points="6 9 12 15 18 9" /></Icon>
    </span>
  </button>

  <div class="menu__popup" lang={$i18nLocale} dir={$i18nDir} use:portal use:menuAction>
    {#each items as item (item.value)}
      <button class="menu__item" type="button" use:itemAction={item.value}>
        {item.label ?? item.value}
      </button>
    {/each}
  </div>
</div>

<style>
  .menu {
    display: inline-block;
    font: inherit;
    color: var(--ds-color-text, #0f172a);
  }

  .menu__trigger {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding: var(--ds-menu-trigger-padding, 0.5rem 0.75rem);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-menu-radius, var(--ds-radius-control, 0.5rem));
    background: var(--ds-color-background, #fff);
    color: inherit;
    font: inherit;
    font-weight: 600;
    cursor: pointer;
    touch-action: manipulation;
  }
  .menu__trigger:focus-visible {
    outline: none;
    border-color: var(--ds-color-focus-ring, #2563eb);
    box-shadow: var(--ds-focus-ring-shadow);
  }
  .menu__trigger:global([data-disabled]) {
    background: var(--ds-color-disabled, #e2e8f0);
    color: var(--ds-color-text-disabled, #94a3b8);
    cursor: not-allowed;
  }
  .menu__chevron {
    display: inline-flex;
    inline-size: 1.1em;
    block-size: 1.1em;
    color: var(--ds-color-text-secondary, #64748b);
    transition: rotate 150ms ease;
  }
  .menu__trigger:global([data-state="open"]) .menu__chevron {
    rotate: 180deg;
  }

  .menu__popup {
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-menu-z-index, 50);
    min-inline-size: var(--ds-menu-min-width, 12rem);
    margin: 0;
    padding: var(--ds-menu-padding, 0.25rem);
    display: flex;
    flex-direction: column;
    background: var(--ds-color-background, #fff);
    border: 1px solid var(--ds-color-border, #cbd5e1);
    border-radius: var(--ds-menu-popup-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(--ds-elevation-overlay, 0 10px 15px -3px rgb(0 0 0 / 0.1));
  }
  .menu__popup:global([data-state="closed"]) {
    display: none;
  }

  .menu__item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    inline-size: 100%;
    padding: 0.45rem 0.55rem;
    border: 0;
    border-radius: var(--ds-radius-control, 0.5rem);
    background: transparent;
    color: inherit;
    font: inherit;
    text-align: start;
    cursor: pointer;
  }
  /* Highlight on pointer hover (desktop) or keyboard focus only — never just
     because an item is the roving-active one on open (no grey on tap). */
  .menu__item:hover {
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  .menu__item:focus-visible {
    outline: none;
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
  }
  .menu__item:global([data-disabled]) {
    color: var(--ds-color-text-disabled, #94a3b8);
    cursor: not-allowed;
  }
</style>

// packages/react/src/dropdown-menu/DropdownMenu.tsx
import type { menu as core } from "@design-system/core";
import { useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { ChevronGlyph, Icon } from "../icon/Icon";
import { useI18n } from "../i18n/i18n";
import { attachFloating, ignoreGhostClicks } from "../internal/floating";
import { MenuPopup, useMenu } from "../internal/menu";
import { usePortalHost } from "../internal/portal-host";

export type MenuEntry = core.MenuEntry;
export type MenuItem = core.MenuItem;
export type MenuGroup = core.MenuGroup;
export type MenuSeparator = core.MenuSeparator;
export type MenuSubmenu = core.MenuSubmenu;

export interface DropdownMenuProps {
  /** Visible text of the trigger, and the menu's accessible name. */
  label: string;
  /** Items, separators, groups and submenus, in the order shown. */
  items: MenuEntry[];
  disabled?: boolean;
  /** Called with the chosen item's value, after every level has closed. */
  onSelect?: (value: string) => void;
}

/**
 * DropdownMenu: the styled menu button (WAI-ARIA menu button pattern). A
 * trigger opens a `role="menu"` of items; behaviour and accessibility (arrow,
 * Home and End navigation, typeahead, Escape, Tab and outside press to close,
 * focus moving into the menu and back to the trigger) come from the headless
 * menu (`@design-system/core`). Positioning uses Floating UI.
 *
 * `items` holds actions, checkable items (`kind: "checkbox" | "radio"` with
 * `checked`), separators, groups and submenus (`{ type: "submenu", value,
 * label, items }`), as `docs/menu-submenu-spec.md` describes: a submenu opens
 * by Enter, Space, the arrow toward the inline end, a press or a 100 ms hover,
 * and a grace area keeps it open while the pointer travels to it. Space on a
 * checkable item reports it and keeps the menu open. Themeable via
 * `--ds-menu-*`.
 */
export function DropdownMenu({ label, items, disabled = false, onSelect }: DropdownMenuProps) {
  const { locale, dir } = useI18n();
  const rootRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const host = usePortalHost(rootRef);
  const { api, setOpenPath, dismiss } = useMenu({
    items,
    disabled,
    onSelect,
    direction: dir,
  });

  // Drop iOS's synthesized duplicate click, so the menu does not toggle twice.
  useEffect(() => {
    const node = triggerRef.current;
    return node ? ignoreGhostClicks(node) : undefined;
  }, []);

  return (
    <div className="menu" ref={rootRef}>
      <button className="menu__trigger" type="button" ref={triggerRef} {...api.triggerProps}>
        <span>{label}</span>
        <span className="menu__chevron" aria-hidden="true">
          <Icon size="100%">
            <ChevronGlyph />
          </Icon>
        </span>
      </button>

      {api.open && host
        ? createPortal(
            <MenuPopup
              api={api}
              prefix="menu"
              direction={dir}
              lang={locale}
              setOpenPath={setOpenPath}
              position={(popup) =>
                triggerRef.current
                  ? attachFloating(triggerRef.current, popup, { sameWidth: true })
                  : () => {}
              }
              inside={() => [triggerRef.current]}
              onDismiss={dismiss}
            />,
            host,
          )
        : null}
    </div>
  );
}
