// packages/react/src/dialog/Dialog.tsx
import type { ReactNode } from "react";
import { Button } from "../button/Button";
import type { ButtonVariant } from "../button/use-button";
import { useI18n } from "../i18n/i18n";
import { useDialog } from "./use-dialog";

/** How the dialog body spaces its direct children. */
export type DialogBodyLayout = "plain" | "stack";

export interface DialogProps {
  /** Visual variant for the trigger Button. */
  triggerVariant?: ButtonVariant;
  /** The trigger button's content. */
  trigger?: ReactNode;
  /** Initial / controlled open state. */
  open?: boolean;
  /** Accessible title naming the dialog (required). */
  title: string;
  /**
   * Visually hide the title while keeping it as the dialog's accessible name.
   * The title text is always required; this only controls whether it is shown.
   */
  hideTitle?: boolean;
  /** Optional description, wired via `aria-describedby`. */
  description?: string;
  /** Accessible label for the close button. Defaults to the catalog's "Close". */
  closeLabel?: string;
  /** Leading feedback icon, centered against the title block. */
  icon?: ReactNode;
  /** Content above the title, e.g. "Step 1 of 2". Carries no progress semantics. */
  headerMeta?: ReactNode;
  /** Leading ghost icon button (e.g. a back affordance). */
  headerLead?: ReactNode;
  /** Leading footer actions, e.g. Back. */
  footerLead?: ReactNode;
  /** Trailing action buttons in the footer. */
  footer?: ReactNode;
  /** Show a close/cancel button on the footer's leading edge. */
  footerClose?: boolean;
  /**
   * Body layout. `plain` (the default) leaves the body untouched. `stack`
   * spaces the direct children by `--ds-dialog-body-gap`, which saves a
   * workflow from inventing its own spacing between sections.
   */
  bodyLayout?: DialogBodyLayout;
  /**
   * CSS selector (within the panel) for the element to focus on open. When
   * omitted, focus lands on the panel itself — never on the close button.
   */
  initialFocus?: string;
  /** Whether pressing the backdrop closes. Default `true`. */
  closeOnOutsideClick?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** The dialog body. */
  children?: ReactNode;
}

/**
 * Dialog — a styled modal window (WAI-ARIA dialog pattern).
 *
 * Behaviour and accessibility come from the headless dialog
 * (`@design-system/core`); modality comes from the native `<dialog>` element
 * via `showModal()` — top layer, inert background, `::backdrop` (ADR 0005) —
 * with body scroll lock, backdrop light-dismiss and focus management added by
 * the adapter.
 *
 * Layout: a grid panel with a fixed header and footer and a scrolling body.
 * Themeable via `--ds-dialog-*`.
 */
export function Dialog({
  triggerVariant = "default",
  trigger,
  open = false,
  title,
  hideTitle = false,
  description,
  closeLabel,
  icon,
  headerMeta,
  headerLead,
  footerLead,
  footer,
  footerClose = false,
  bodyLayout = "plain",
  initialFocus,
  closeOnOutsideClick = true,
  onOpenChange,
  children,
}: DialogProps) {
  const { t } = useI18n();
  const {
    api,
    open: isOpen,
    triggerRef,
    panelRef,
  } = useDialog({
    open,
    describedBy: description !== undefined,
    initialFocus,
    closeOnOutsideClick,
    onOpenChange,
  });

  const resolvedCloseLabel = closeLabel ?? t("dialog.close");

  return (
    <>
      <Button variant={triggerVariant} {...api.triggerProps} ref={triggerRef}>
        {trigger ?? "Open"}
      </Button>

      {isOpen && (
        <dialog {...api.contentProps} ref={panelRef} className="dialog__panel">
          <header className="dialog__header">
            {icon && <div className="dialog__header-icon">{icon}</div>}
            {headerLead && <div className="dialog__header-lead">{headerLead}</div>}
            {/* Consumer content above the title, e.g. "Step 1 of 2". It carries
                no progress semantics of its own. */}
            {headerMeta && <div className="dialog__header-meta">{headerMeta}</div>}

            <h2
              {...api.titleProps}
              className={hideTitle ? "dialog__title dialog__title--hidden" : "dialog__title"}
            >
              {title}
            </h2>

            {description !== undefined && (
              <p {...api.descriptionProps} className="dialog__subtitle">
                {description}
              </p>
            )}

            <button
              {...api.closeProps}
              className="dialog__close"
              type="button"
              aria-label={resolvedCloseLabel}
            >
              <svg
                viewBox="0 0 24 24"
                width="1em"
                height="1em"
                aria-hidden="true"
                focusable="false"
              >
                <path
                  d="M6 6l12 12M18 6L6 18"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                />
              </svg>
            </button>
          </header>

          <div className="dialog__body" data-layout={bodyLayout}>
            {children}
          </div>

          {/* One action bar: the leading group first, so source order matches
              focus order, then the trailing group. */}
          {(footer || footerLead || footerClose) && (
            <footer className="dialog__footer">
              {(footerLead || footerClose) && (
                <div className="dialog__footer-lead">
                  {footerLead}
                  {footerClose && (
                    <Button variant="ghost" {...api.closeProps}>
                      {resolvedCloseLabel}
                    </Button>
                  )}
                </div>
              )}
              {footer && <div className="dialog__footer-actions">{footer}</div>}
            </footer>
          )}
        </dialog>
      )}
    </>
  );
}

// packages/svelte/src/lib/dialog/Dialog.svelte
<script lang="ts">
  /**
   * Dialog — a styled modal window (WAI-ARIA dialog pattern). Behaviour and
   * accessibility (open/close, `role="dialog"` + `aria-modal`, labelling via the
   * title, Escape to close) come from the headless dialog
   * (`@design-system/core`); this adapter adds the modal DOM concerns on the
   * native `<dialog>` element (`showModal()`: top layer, inert background,
   * `::backdrop`), plus body scroll lock, backdrop light-dismiss and focus
   * management (focus moves into the panel on open and returns to the trigger
   * on close).
   *
   * Layout: a grid panel with a fixed header and footer and a scrolling body.
   * The header is a grid — optional leading `icon` (a FeedbackIcon) and
   * `headerLead` (a ghost icon button, e.g. back), the title + optional subtitle
   * (`description`) stacked, and the close button trailing, all centered against
   * the title block.
   *
   * Slots: `trigger` (the trigger button's content), the default slot (the
   * body), `icon` (leading feedback icon), `headerMeta` (context above the
   * title), `headerLead` (leading ghost button), `footerLead` (leading footer
   * actions) and `footer` (trailing action buttons). Pass an accessible `title`
   * (required; hide it with `hideTitle`), optional `description` (the subtitle)
   * and `footerClose` for a close button in the footer. Colors, radius
   * and elevation are themeable via `--ds-dialog-*`.
   *
   * Multi-step workflows are a composition, not a separate component: put the
   * step context in `headerMeta`, Back in `footerLead`, and keep the step state
   * in the application.
   */
  import { createDialog } from "./create-dialog";
  import Button from "../button/Button.svelte";
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  /** Visual variant for the trigger Button. */
  export let triggerVariant: "default" | "primary" | "secondary" | "ghost" | "danger" = "default";

  /** Initial open state. */
  export let open = false;
  /** Accessible title naming the dialog (required). */
  export let title: string;
  /**
   * Visually hide the title while keeping it as the dialog's accessible name
   * (announced by screen readers via `aria-labelledby`). The title text is
   * always required; this only controls whether it is shown.
   */
  export let hideTitle = false;
  /** Optional description, wired via `aria-describedby`. */
  export let description: string | undefined = undefined;
  /** Accessible label for the close button. Defaults to the i18n catalog's "Close". */
  export let closeLabel: string | undefined = undefined;
  /**
   * Show an optional close/cancel button on the footer's leading (left) edge.
   * The trailing (right) edge holds the action buttons from the `footer` slot.
   */
  export let footerClose = false;
  /**
   * Body layout. `plain` (the default) leaves the body untouched. `stack`
   * spaces the direct children by `--ds-dialog-body-gap`, which saves a
   * workflow from inventing its own spacing between sections.
   */
  export let bodyLayout: "plain" | "stack" = "plain";
  /**
   * CSS selector (within the panel) for the element to focus on open. When
   * omitted, focus lands on the panel itself — never on the close button.
   */
  export let initialFocus: string | undefined = undefined;
  /** Called whenever the open state changes. */
  export let onOpenChange: ((open: boolean) => void) | undefined = undefined;

  const handleOpenChange = (next: boolean) => {
    open = next;
    onOpenChange?.(next);
  };

  const dialog = createDialog({
    open,
    describedBy: description !== undefined,
    initialFocus,
    onOpenChange: handleOpenChange,
  });
  const {
    open: isOpen,
    triggerAction,
    contentAction,
    titleAction,
    descriptionAction,
    closeAction,
  } = dialog;

  $: dialog.setOpen(open);

  $: resolvedCloseLabel = closeLabel ?? $t("dialog.close");
</script>

<Button variant={triggerVariant} action={triggerAction}>
  <slot name="trigger">{$t("dialog.trigger")}</slot>
</Button>

{#if $isOpen}
  <dialog class="dialog__panel" use:contentAction>
    <header class="dialog__header">
      {#if $$slots.icon}
        <!-- Optional leading feedback icon, centered against title+subtitle. -->
        <div class="dialog__header-icon"><slot name="icon" /></div>
      {/if}
      {#if $$slots.headerLead}
        <!-- Optional ghost icon-only button (e.g. a back affordance). -->
        <div class="dialog__header-lead"><slot name="headerLead" /></div>
      {/if}
      {#if $$slots.headerMeta}
        <!-- Consumer content above the title, e.g. "Step 1 of 2". It carries no
             progress semantics: the meaning belongs to what the consumer puts here. -->
        <div class="dialog__header-meta"><slot name="headerMeta" /></div>
      {/if}
      <h2 class="dialog__title" class:dialog__title--hidden={hideTitle} use:titleAction>{title}</h2>
      {#if description !== undefined}
        <p class="dialog__subtitle" use:descriptionAction>{description}</p>
      {/if}
      <button class="dialog__close" type="button" aria-label={resolvedCloseLabel} use:closeAction>
        <svg viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true" focusable="false">
          <path
            d="M6 6l12 12M18 6L6 18"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
          />
        </svg>
      </button>
    </header>
    <div class="dialog__body" data-layout={bodyLayout}><slot /></div>
    {#if $$slots.footer || $$slots.footerLead || footerClose}
      <!-- One action bar: leading actions at the logical start, the trailing
           group at the logical end. Source order matches focus order. -->
      <footer class="dialog__footer">
        {#if $$slots.footerLead || footerClose}
          <div class="dialog__footer-lead">
            <slot name="footerLead" />
            {#if footerClose}
              <Button variant="ghost" action={closeAction}>{resolvedCloseLabel}</Button>
            {/if}
          </div>
        {/if}
        {#if $$slots.footer}
          <div class="dialog__footer-actions"><slot name="footer" /></div>
        {/if}
      </footer>
    {/if}
  </dialog>
{/if}

<style>
  .dialog__panel::backdrop {
    background: var(--ds-dialog-overlay, rgb(15 23 42 / 0.5));
  }
  .dialog__panel {
    /* The UA centers a :modal dialog via margin auto; CSS resets zero it. */
    margin: auto;
    box-sizing: border-box;
    /* Rows: header sizes to content and stays put, the body takes the rest and
       is the only scrolling region, the footer auto-places into an implicit row
       (so an absent footer leaves no trailing gap). The internal gap spaces the
       rows; the padding is the outer inset. */
    display: grid;
    grid-template-rows: auto 1fr;
    gap: var(--ds-dialog-gap, 1rem);
    inline-size: 100%;
    max-inline-size: var(--ds-dialog-max-width, 30rem);
    max-block-size: calc(100vh - 2rem);
    overflow: hidden;
    padding: var(--ds-dialog-padding, 1.25rem 1.5rem);
    background: var(--ds-color-background, #fff);
    color: var(--ds-color-text, #282420);
    line-height: var(--ds-line-height, 1.4);
    border: 1px solid var(--ds-color-border, #c7c1b7);
    border-radius: var(--ds-dialog-radius, var(--ds-radius-surface, 0.75rem));
    box-shadow: var(
      --ds-elevation-overlay,
      0 10px 15px -3px rgb(0 0 0 / 0.1),
      0 4px 6px -4px rgb(0 0 0 / 0.1)
    );
  }
  .dialog__panel:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }

  /* Columns: icon | back | titles (1fr) | close. Rows: meta / title / subtitle.
     The side items span all rows so they center against the title block. An
     absent row takes no height. No column-gap (empty optional columns must not
     leave phantom space); the present items carry their own margin. */
  .dialog__header {
    display: grid;
    grid-template-columns: auto auto 1fr auto;
    grid-template-rows: auto auto auto;
    align-items: center;
    padding-block-end: 1rem;
  }
  /* Consumer content above the title. Quiet by default so it reads as context;
     the content can restyle itself. */
  .dialog__header-meta {
    grid-column: 3;
    grid-row: 1;
    min-inline-size: 0;
    margin-block-end: 0.25rem;
    font-size: 0.875rem;
    line-height: var(--ds-line-height-tight, 1.2);
    color: var(--ds-color-text-secondary, #524c44);
  }
  .dialog__header-icon {
    grid-column: 1;
    grid-row: 1 / -1;
    display: inline-flex;
    align-items: center;
    margin-inline-end: 0.75rem;
  }
  .dialog__header-lead {
    grid-column: 2;
    grid-row: 1 / -1;
    display: inline-flex;
    align-items: center;
    margin-inline-end: 0.75rem;
  }
  .dialog__title {
    grid-column: 3;
    grid-row: 2;
    min-inline-size: 0;
    margin: 0;
    font-size: 1.125rem;
    font-weight: 600;
    line-height: var(--ds-line-height-tight, 1.2);
  }
  /* Kept in the accessibility tree (labels the dialog), removed from view. */
  .dialog__title--hidden {
    position: absolute;
    inline-size: 1px;
    block-size: 1px;
    margin: -1px;
    padding: 0;
    border: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    white-space: nowrap;
  }
  .dialog__close {
    grid-column: 4;
    grid-row: 1 / -1;
    /* Space from the titles; trailing edge is the last column. */
    margin-inline-start: 0.75rem;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    inline-size: 1.75rem;
    block-size: 1.75rem;
    font-size: 1.25rem;
    padding: 0;
    border: 0;
    border-radius: var(--ds-radius-control, 0.5rem);
    background: transparent;
    color: var(--ds-color-text-secondary, #524c44);
    cursor: pointer;
  }
  .dialog__close:hover {
    background: var(--ds-state-hover, rgb(0 0 0 / 0.06));
    color: inherit;
  }
  .dialog__close:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: 2px;
  }

  .dialog__subtitle {
    grid-column: 3;
    grid-row: 3;
    min-inline-size: 0;
    margin: 0;
    font-size: 0.875rem;
    line-height: var(--ds-line-height-tight, 1.2);
    color: var(--ds-color-text-secondary, #524c44);
  }
  /* The body is the only scrolling region (the 1fr grid row); header and footer
     stay fixed. min-block-size:0 lets it shrink and scroll. */
  .dialog__body {
    min-block-size: 0;
    overflow-y: auto;
  }
  /* Opt-in spacing between the body's direct sections, so a workflow does not
     invent its own. */
  .dialog__body[data-layout="stack"] {
    display: grid;
    align-content: start;
    gap: var(--ds-dialog-body-gap, 1rem);
  }
  /* One action bar: the leading group at the logical start, the trailing group
     at the logical end. It wraps on narrow widths, and wrapping keeps the
     source order, so the visual order never contradicts focus order. */
  .dialog__footer {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
    padding-block-start: 1rem;
  }
  .dialog__footer-lead {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
  }
  .dialog__footer-actions {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
    /* Actions sit on the trailing edge; the leading group stays at the start. */
    margin-inline-start: auto;
  }
</style>
