// packages/react/src/tooltip/Tooltip.tsx
import { useRef, type PointerEvent, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { useI18n } from "../i18n/i18n";
import type { Placement } from "../internal/floating";
import { usePortalHost } from "../internal/portal-host";
import { useTooltip } from "./use-tooltip";

export interface TooltipProps {
  /** Tooltip label text. */
  text: string;
  /** Preferred placement; flips when there is no room. */
  placement?: Placement;
  /** Delay before showing on hover, in ms. */
  openDelay?: number;
  /** Delay before hiding on leave, in ms. */
  closeDelay?: number;
  /** The trigger: wrap a focusable element. */
  children?: ReactNode;
}

/**
 * Tooltip: a styled descriptive label shown on hover and focus of a trigger
 * (WAI-ARIA `role="tooltip"`, linked by `aria-describedby`). Behaviour comes
 * from the headless tooltip (`@design-system/core`); the adapter adds open
 * and close delays, Floating UI positioning, and WCAG 1.4.13 content on
 * hover: the tooltip stays open while hovered and Escape hides it. Keyboard
 * focus shows it at once. On touch, where hover does not exist, a tap toggles
 * it. Inside an open dialog it renders in the dialog (ADR 0016).
 *
 * `children` is the trigger; `text` is the label. For `aria-describedby` on
 * your own element, use `useTooltip`. Themeable via `--ds-tooltip-*`.
 */
export function Tooltip({
  text,
  placement = "top",
  openDelay = 300,
  closeDelay = 100,
  children,
}: TooltipProps) {
  const { locale, dir } = useI18n();
  const { api, open, triggerRef, tooltipRef, show, hide, hold } = useTooltip({
    placement,
    openDelay,
    closeDelay,
  });
  const host = usePortalHost(triggerRef);
  // Touch has no hover: the tap owns touch, so the tooltip does not flash.
  const touch = useRef(false);

  return (
    <>
      <span
        {...api.triggerProps}
        ref={triggerRef}
        className="tooltip__trigger"
        onPointerEnter={(event: PointerEvent) => {
          if (event.pointerType !== "touch") show();
        }}
        onPointerLeave={() => hide()}
        onFocus={() => show(0)}
        onBlur={() => hide(0)}
        onPointerDown={(event: PointerEvent) => {
          touch.current = event.pointerType !== "mouse";
        }}
        onClick={() => {
          if (!touch.current) return;
          if (open) hide(0);
          else show(0);
        }}
      >
        {children}
      </span>
      {open && host
        ? createPortal(
            <div
              {...api.tooltipProps}
              ref={tooltipRef}
              className="tooltip__content"
              lang={locale}
              dir={dir}
              onPointerEnter={hold}
              onPointerLeave={() => hide()}
            >
              {text}
            </div>,
            host,
          )
        : null}
    </>
  );
}

// packages/svelte/src/lib/tooltip/Tooltip.svelte
<script lang="ts">
  /**
   * Tooltip — a styled descriptive label shown on hover/focus of a trigger
   * (WAI-ARIA `role="tooltip"` linked via `aria-describedby`). Behaviour comes
   * from the headless tooltip (`@design-system/core`); the adapter adds open/
   * close delays, Floating-UI positioning (flip/shift), and WCAG 1.4.13 "content
   * on hover" semantics (hoverable + Escape-dismissable).
   *
   * The default slot is the trigger (wrap a focusable element); `text` is the
   * tooltip label. For precise control (e.g. putting `aria-describedby` on your
   * own element), use the headless `createTooltip` instead. Themeable via
   * `--ds-tooltip-*`.
   */
  import { createTooltip, type TooltipContext } from "./create-tooltip";
  import { portal } from "../internal/portal";
  import { getI18n } from "../i18n/create-i18n";

  /** Tooltip label text. */
  const { locale: i18nLocale, dir: i18nDir } = getI18n();

  export let text: string;
  export let placement: TooltipContext["placement"] = "top";
  export let openDelay = 300;
  export let closeDelay = 100;

  const tooltip = createTooltip({ placement, openDelay, closeDelay });
  const { triggerAction, tooltipAction, open } = tooltip;
</script>

<span class="tooltip__trigger" use:triggerAction>
  <slot />
</span>

{#if $open}
  <div class="tooltip__content" lang={$i18nLocale} dir={$i18nDir} use:portal use:tooltipAction>
    {text}
  </div>
{/if}

<style>
  .tooltip__trigger {
    display: inline-flex;
  }

  .tooltip__content {
    /* Positioned by the adapter (Floating UI) with a fixed strategy. */
    position: fixed;
    inset-block-start: 0;
    inset-inline-start: 0;
    z-index: var(--ds-tooltip-z-index, 60);
    max-inline-size: var(--ds-tooltip-max-width, 18rem);
    padding: var(--ds-tooltip-padding, 0.3rem 0.5rem);
    font-size: var(--ds-tooltip-font-size, 0.8125rem);
    line-height: var(--ds-line-height, 1.4);
    background: var(--ds-tooltip-bg, var(--ds-color-emphasis-surface, #1e293b));
    color: var(--ds-tooltip-color, var(--ds-color-on-emphasis, #f8fafc));
    border-radius: var(--ds-tooltip-radius, var(--ds-radius-control, 0.375rem));
    box-shadow: var(--ds-elevation-overlay, 0 10px 15px -3px rgb(0 0 0 / 0.1));
    pointer-events: auto;
  }
</style>
