// packages/svelte/src/lib/switch/Switch.svelte
<script lang="ts">
  /**
   * Switch — the styled, batteries-included switch built on a **native**
   * `<input type="checkbox" role="switch">`. The browser provides Space
   * activation, focus and form participation (`name`/`value`); `role="switch"`
   * makes screen readers announce on/off. This layer adds the sliding track and
   * thumb plus the visible label.
   *
   * Prefer this over a checkbox for instant on/off settings. A `label` is
   * required (the control needs an accessible name); pass the default slot to
   * override it with rich content. The native input is wrapped in a `<label>`,
   * so clicking the track or text toggles it. Colors and sizing are themeable
   * CSS custom properties (`--ds-switch-*`).
   */
  import { createSwitch } from "./create-switch";
  import { getI18n } from "../i18n/create-i18n";

  const { t } = getI18n();

  /** Accessible, visible label (required). Override with the default slot for rich content. */
  export let label: string;
  export let checked = false;
  export let disabled = false;
  /** Form field name — the value is submitted under it when on. */
  export let name: string | undefined = undefined;
  /** Value submitted with the form when on. Defaults to the native `"on"`. */
  export let value = "on";
  /** Mark the control required for native form validation. */
  export let required = false;
  /** Show ON/OFF text inside the track (a wider, labelled variant). */
  export let onOff = false;
  /** Text shown in the track when on / off (only with `onOff`). Default to the i18n catalog's "ON" / "OFF". */
  export let onText: string | undefined = undefined;
  export let offText: string | undefined = undefined;
  /** Called whenever the on/off value changes. */
  export let onCheckedChange: ((c: boolean) => void) | undefined = undefined;

  const { state: swState, setChecked } = createSwitch({ checked, disabled, onCheckedChange });

  $: resolvedOnText = onText ?? $t("switch.on");
  $: resolvedOffText = offText ?? $t("switch.off");

  function onChange(event: Event) {
    setChecked((event.currentTarget as HTMLInputElement).checked);
  }
</script>

<label class="field" class:field--disabled={disabled}>
  <input
    class="switch__input"
    type="checkbox"
    role="switch"
    {name}
    {value}
    {required}
    {disabled}
    checked={$swState.checked}
    on:change={onChange}
    data-state={$swState.checked ? "checked" : "unchecked"}
  />
  <span class="switch" class:switch--onoff={onOff} aria-hidden="true">
    {#if onOff}
      <span class="switch__on">{resolvedOnText}</span>
      <span class="switch__off">{resolvedOffText}</span>
    {/if}
  </span>
  <span class="field__label"><slot>{label}</slot></span>
</label>

<style>
  .field {
    display: inline-flex;
    align-items: center;
    gap: var(--ds-switch-gap, 0.5rem);
    cursor: pointer;
  }
  .field--disabled {
    cursor: not-allowed;
  }
  .field--disabled .field__label {
    color: var(--ds-color-text-disabled, #757067);
  }

  /* The native input is the accessible, focusable control; visually hidden, with
     the sibling `.switch` painted from its :checked / :focus-visible state. */
  .switch__input {
    position: absolute;
    inline-size: 1px;
    block-size: 1px;
    margin: -1px;
    padding: 0;
    border: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    white-space: nowrap;
  }

  .switch {
    inline-size: var(--ds-switch-width, 2.5rem);
    block-size: var(--ds-switch-height, 1.5rem);
    border-radius: var(--ds-radius-pill, 999px);
    /* The track is the switch's whole visible form, so it takes the control
       boundary colour, not the divider colour. */
    background: var(--ds-color-control-border, #757067);
    position: relative;
    flex: none;
    transition: background-color 120ms ease;
  }
  .switch::after {
    content: "";
    position: absolute;
    inset-block-start: 0.125rem;
    inset-inline-start: 0.125rem;
    inline-size: calc(var(--ds-switch-height, 1.5rem) - 0.25rem);
    block-size: calc(var(--ds-switch-height, 1.5rem) - 0.25rem);
    border-radius: 50%;
    /* The thumb is always white (it sits on the track in both states). */
    background: var(--ds-switch-thumb, var(--ds-neutral-0, #ffffff));
    /* A page-coloured rim keeps the thumb separable from the track: the track
       clears 3:1 against the page, so the rim clears it too, in both themes. */
    box-shadow: 0 0 0 1px var(--ds-color-background, #ffffff);
    transition: translate 150ms ease;
  }
  .switch__input:focus-visible + .switch {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: var(--ds-focus-ring-offset, 2px);
  }

  .switch__input:checked + .switch {
    background: var(--ds-color-secondary, #7a52cc);
  }
  .switch__input:checked + .switch::after {
    translate: calc(var(--ds-switch-width, 2.5rem) - var(--ds-switch-height, 1.5rem)) 0;
  }

  .field--disabled .switch,
  .switch__input:disabled + .switch {
    opacity: 0.5;
  }

  /* ---- ON/OFF labelled variant: a wider track with text behind the thumb ---- */
  .switch--onoff {
    inline-size: var(--ds-switch-onoff-width, 3.75rem);
    display: flex;
    align-items: center;
  }
  .switch--onoff .switch__on,
  .switch--onoff .switch__off {
    position: absolute;
    inset-block: 0;
    display: inline-flex;
    align-items: center;
    font-size: var(--ds-switch-onoff-font, 0.625rem);
    font-weight: 700;
    letter-spacing: 0.04em;
    transition: opacity 120ms ease;
  }
  /* ON sits on the left (revealed when the thumb slides right). */
  .switch--onoff .switch__on {
    inset-inline-start: 0.5rem;
    color: var(--ds-switch-onoff-on-text, var(--ds-color-on-secondary, #fff));
    opacity: 0;
  }
  /* OFF sits on the right (shown while off, thumb on the left). */
  .switch--onoff .switch__off {
    inset-inline-end: 0.5rem;
    color: var(--ds-switch-onoff-off-text, var(--ds-color-text-secondary, #524c44));
    opacity: 1;
  }
  .switch__input:checked + .switch--onoff .switch__on {
    opacity: 1;
  }
  .switch__input:checked + .switch--onoff .switch__off {
    opacity: 0;
  }
  .switch--onoff.switch::after {
    translate: 0 0;
  }
  .switch__input:checked + .switch--onoff.switch::after {
    translate: calc(var(--ds-switch-onoff-width, 3.75rem) - var(--ds-switch-height, 1.5rem)) 0;
  }
</style>

// packages/react/src/switch/Switch.tsx
import { useRef, type ReactNode } from "react";
import { useI18n } from "../i18n/i18n";
import { useSwitch } from "./use-switch";

export interface SwitchProps {
  /** Accessible, visible label (required). Override with `children` for rich content. */
  label: string;
  /**
   * Visually hide the label while keeping it as the accessible name. The label
   * text is always required.
   */
  hideLabel?: boolean;
  checked?: boolean;
  disabled?: boolean;
  /** Form field name — the value is submitted under it when on. */
  name?: string;
  /** Value submitted with the form when on. Defaults to the native `"on"`. */
  value?: string;
  /** Mark the control required for native form validation. */
  required?: boolean;
  /** Show ON/OFF text inside the track (a wider, labelled variant). */
  onOff?: boolean;
  /** Track text when on / off (only with `onOff`). Defaults to the catalog's "ON" / "OFF". */
  onText?: string;
  offText?: string;
  /** Called whenever the on/off value changes. */
  onCheckedChange?: (checked: boolean) => void;
  children?: ReactNode;
}

/**
 * Switch — the styled switch built on a native
 * `<input type="checkbox" role="switch">`. The browser provides Space
 * activation, focus and form participation; `role="switch"` makes screen
 * readers announce on/off, which is clearer than a checkbox for settings.
 *
 * Prefer this over a checkbox for instant on/off settings. Themeable via
 * `--ds-switch-*`.
 */
export function Switch({
  label,
  hideLabel = false,
  checked = false,
  disabled = false,
  name,
  value = "on",
  required = false,
  onOff = false,
  onText,
  offText,
  onCheckedChange,
  children,
}: SwitchProps) {
  const ref = useRef<HTMLInputElement>(null);
  const api = useSwitch({ checked, disabled, onCheckedChange, controlRef: ref });
  const { t } = useI18n();

  return (
    <label className={disabled ? "field field--disabled" : "field"}>
      <input
        {...api.rootProps}
        ref={ref}
        className="switch__input"
        name={name}
        value={value}
        required={required}
        checked={api.checked}
      />
      <span className={onOff ? "switch switch--onoff" : "switch"} aria-hidden="true">
        {onOff && (
          <>
            <span className="switch__on">{onText ?? t("switch.on")}</span>
            <span className="switch__off">{offText ?? t("switch.off")}</span>
          </>
        )}
      </span>
      <span className={hideLabel ? "field__label field__label--hidden" : "field__label"}>
        {children ?? label}
      </span>
    </label>
  );
}
