// packages/react/src/scroll-area/ScrollArea.tsx
import type { CSSProperties, ReactNode } from "react";
import { useScrollArea, type ScrollOrientation } from "./use-scroll-area";

export interface ScrollAreaProps {
  /** Which axes scroll. Defaults to `vertical`. */
  orientation?: ScrollOrientation;
  /** Largest block size of the viewport, the scroll constraint, such as `"12rem"`. */
  maxHeight?: string;
  /**
   * Optional accessible name; makes the viewport a labelled region. Two
   * scroll areas on a page should not share one: the landmark list would show
   * the same entry twice.
   */
  label?: string;
  /** The scrolling content. */
  children?: ReactNode;
}

const OVERFLOW: Record<ScrollOrientation, CSSProperties> = {
  vertical: { overflowY: "auto", overflowX: "hidden" },
  horizontal: { overflowX: "auto", overflowY: "hidden" },
  both: { overflow: "auto" },
};

/**
 * ScrollArea: a scrollable viewport with overlay scrollbars. The scrollbar
 * geometry comes from the headless scroll area (`@design-system/core`);
 * `useScrollArea` measures the viewport and lets a thumb be dragged. Native
 * scrollbars are hidden, while keyboard and wheel scrolling stay native: the
 * viewport takes focus and scrolls with the arrow keys.
 *
 * Themeable via `--ds-scroll-area-*`.
 */
export function ScrollArea({
  orientation = "vertical",
  maxHeight = "12rem",
  label,
  children,
}: ScrollAreaProps) {
  const { viewportRef, vertical, horizontal, getThumbProps } = useScrollArea();
  const showVertical = orientation !== "horizontal" && vertical.overflow;
  const showHorizontal = orientation !== "vertical" && horizontal.overflow;
  // The shared sheet leaves the scroll constraint, the overflow axes and the
  // thumb geometry to the adapter, so they go inline as in the other adapters.
  return (
    <div className="scroll-area" data-orientation={orientation}>
      <div
        ref={viewportRef}
        className="scroll-area__viewport"
        // A scrollable region has to be reachable by keyboard.
        tabIndex={0}
        role={label ? "region" : undefined}
        aria-label={label}
        style={{ maxBlockSize: maxHeight, ...OVERFLOW[orientation] }}
      >
        {children}
      </div>
      {showVertical ? (
        <div className="scroll-area__bar scroll-area__bar--v" aria-hidden="true">
          <div
            {...getThumbProps("vertical")}
            className="scroll-area__thumb"
            style={{
              blockSize: `${vertical.sizeFraction * 100}%`,
              insetBlockStart: `${vertical.offsetFraction * 100}%`,
            }}
          />
        </div>
      ) : null}
      {showHorizontal ? (
        <div className="scroll-area__bar scroll-area__bar--h" aria-hidden="true">
          <div
            {...getThumbProps("horizontal")}
            className="scroll-area__thumb"
            style={{
              inlineSize: `${horizontal.sizeFraction * 100}%`,
              insetInlineStart: `${horizontal.offsetFraction * 100}%`,
            }}
          />
        </div>
      ) : null}
    </div>
  );
}

// packages/svelte/src/lib/scroll-area/ScrollArea.svelte
<script lang="ts">
  /**
   * ScrollArea — a scrollable viewport with custom overlay scrollbars. The
   * scrollbar geometry comes from the headless scroll area (`@design-system/core`);
   * this adapter measures the viewport (scroll + ResizeObserver) and supports
   * dragging the thumb. Native scrollbars are hidden but native keyboard/wheel
   * scrolling is preserved (the focusable viewport scrolls with the arrow keys).
   *
   * Put the scrolling content in `children`. Themeable via
   * `--ds-scroll-area-*`.
   */
  import type { Snippet } from "svelte";
  import { createScrollArea, type ScrollOrientation } from "./create-scroll-area";

  interface Props {
    /** Which axes scroll. Defaults to `vertical`. */
    orientation?: ScrollOrientation;
    /** Max size of the viewport (the scroll constraint), e.g. `"12rem"`. */
    maxHeight?: string;
    /**
     * Optional accessible name; makes the viewport a labelled scroll region.
     * The name is yours to choose, so two scroll areas on a page should not
     * share one: the landmark list would show the same entry twice.
     */
    label?: string;
    children?: Snippet;
  }

  let { orientation = "vertical", maxHeight = "12rem", label, children }: Props = $props();

  const { vertical, horizontal, viewportAction, thumbAction } = createScrollArea();

  const showV = $derived(orientation === "vertical" || orientation === "both");
  const showH = $derived(orientation === "horizontal" || orientation === "both");
  const overflowStyle = $derived(
    orientation === "horizontal"
      ? "overflow-x:auto;overflow-y:hidden;"
      : orientation === "both"
        ? "overflow:auto;"
        : "overflow-y:auto;overflow-x:hidden;",
  );
</script>

<div class="scroll-area" data-orientation={orientation}>
  <!-- A scrollable region has to be reachable by keyboard, so the viewport
       carries tabindex on purpose. -->
  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
  <div
    class="scroll-area__viewport"
    use:viewportAction
    tabindex="0"
    role={label ? "region" : undefined}
    aria-label={label}
    style="max-block-size:{maxHeight}; {overflowStyle}"
  >
    {@render children?.()}
  </div>

  {#if showV && $vertical.overflow}
    <div class="scroll-area__bar scroll-area__bar--v" aria-hidden="true">
      <div
        class="scroll-area__thumb"
        use:thumbAction={"vertical"}
        style="block-size:{$vertical.sizeFraction *
          100}%; inset-block-start:{$vertical.offsetFraction * 100}%"
      ></div>
    </div>
  {/if}

  {#if showH && $horizontal.overflow}
    <div class="scroll-area__bar scroll-area__bar--h" aria-hidden="true">
      <div
        class="scroll-area__thumb"
        use:thumbAction={"horizontal"}
        style="inline-size:{$horizontal.sizeFraction *
          100}%; inset-inline-start:{$horizontal.offsetFraction * 100}%"
      ></div>
    </div>
  {/if}
</div>

<style>
  .scroll-area {
    position: relative;
    font: inherit;
    color: var(--ds-color-text, #282420);
  }
  .scroll-area__viewport {
    max-inline-size: 100%;
    /* Hide native scrollbars; the custom overlay bars are drawn instead. */
    scrollbar-width: none;
  }
  .scroll-area__viewport::-webkit-scrollbar {
    display: none;
  }
  .scroll-area__viewport:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow);
    outline-offset: -2px;
  }

  .scroll-area__bar {
    position: absolute;
    z-index: 1;
    background: var(--ds-scroll-area-track, transparent);
    border-radius: 999px;
  }
  .scroll-area__bar--v {
    inset-block: 2px;
    inset-inline-end: 2px;
    inline-size: var(--ds-scroll-area-size, 0.5rem);
  }
  .scroll-area__bar--h {
    inset-inline: 2px;
    inset-block-end: 2px;
    block-size: var(--ds-scroll-area-size, 0.5rem);
  }
  .scroll-area__thumb {
    position: absolute;
    border-radius: 999px;
    background: var(--ds-scroll-area-thumb, var(--ds-color-border, #c7c1b7));
    cursor: default;
  }
  .scroll-area__thumb:hover {
    background: var(--ds-scroll-area-thumb-hover, var(--ds-color-text-secondary, #524c44));
  }
  .scroll-area__bar--v .scroll-area__thumb {
    inline-size: 100%;
  }
  .scroll-area__bar--h .scroll-area__thumb {
    block-size: 100%;
  }
</style>
