// packages/svelte/src/lib/dialog/DialogStatus.svelte
<script lang="ts">
  /**
   * DialogStatus (internal) — the status area of the dialog family (ADR 0016):
   * notices about the dialog's own task, placed between the body and the
   * footer. Each notice is an Inline Notification with `role="group"`, named
   * by its title, so it is never a live region of its own and never takes
   * focus. One persistent polite live region reads each notice once, when it
   * is added; it stays in the panel, visually hidden, so it is never created
   * at the moment it speaks. The area is hidden while it holds no notice.
   */
  import InlineNotification from "../inline-notification/InlineNotification.svelte";
  import type { CreateDialog } from "./create-dialog";

  interface Props {
    /** The dialog whose status area this is. */
    dialog: Pick<CreateDialog, "notices" | "announcement" | "dismissNotice">;
  }

  let { dialog }: Props = $props();

  const notices = $derived(dialog.notices);
  const announcement = $derived(dialog.announcement);
</script>

<div class="dialog-status" hidden={$notices.length === 0}>
  {#each $notices as notice (notice.id)}
    <InlineNotification
      role="group"
      status={notice.status}
      title={notice.title}
      description={notice.description ?? ""}
      closable={notice.dismissible !== false}
      actions={notice.action
        ? [
            {
              label: notice.action.label,
              // Ghost, as in a notification: the action must not outweigh the message.
              variant: "ghost",
              onClick: () => {
                notice.action?.onAction();
                dialog.dismissNotice(notice.id);
              },
            },
          ]
        : undefined}
      onclose={() => dialog.dismissNotice(notice.id)}
    />
  {/each}
</div>
<div class="dialog-status__live" role="status" aria-atomic="true">
  <!-- Each line ends in a space, so the lines are read as separate words. -->
  {#each $announcement as line (line.id)}<p>{`${line.text} `}</p>{/each}
</div>

<style>
  .dialog-status {
    display: grid;
    gap: 0.5rem;
    margin-block-start: 1rem;
  }
  .dialog-status[hidden] {
    display: none;
  }
  /* The persistent live region: read by screen readers, never shown. Absolute,
     so it takes no row in the panel's grid or flex layout. */
  .dialog-status__live {
    position: absolute;
    inline-size: 1px;
    block-size: 1px;
    margin: -1px;
    padding: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    white-space: nowrap;
    border: 0;
  }
</style>

// packages/react/src/dialog/DialogStatus.tsx
import { Fragment } from "react";
import { Button } from "../button/Button";
import { useI18n } from "../i18n/i18n";
import { FeedbackIcon } from "../feedback-icon/FeedbackIcon";
import { CloseGlyph, Icon } from "../icon/Icon";
import type { DialogNotice } from "./use-dialog-notices";

export interface DialogStatusProps {
  notices: readonly DialogNotice[];
  announcement: readonly string[];
  dismissNotice: (id: string) => void;
}

/**
 * The status area of a dialog (internal, ADR 0016), placed between the body
 * and the footer so its buttons follow the body in the tab order: the notices,
 * with the Inline Notification markup of the other adapters, and one
 * persistent polite live region that announces each notice once. The notices
 * are groups named by their title and never live regions themselves, so none
 * is read twice. The area is hidden while it holds no notice; the live region
 * stays in the panel, visually hidden, so it exists before it speaks.
 */
export function DialogStatus({ notices, announcement, dismissNotice }: DialogStatusProps) {
  const { t } = useI18n();
  const closeLabel = t("inlineNotification.close");

  return (
    <>
      <div className="dialog-status" hidden={notices.length === 0}>
        {notices.map((notice) => {
          const titleId = `${notice.id}-title`;
          return (
            <div key={notice.id} id={notice.id} role="group" aria-labelledby={titleId}>
              <div className="inline-notification" data-status={notice.status}>
                <FeedbackIcon status={notice.status} box="transparent" />
                <div className="inline-notification__content">
                  <p className="inline-notification__title" id={titleId}>
                    {notice.title}
                  </p>
                  {notice.description ? (
                    <div className="inline-notification__body">{notice.description}</div>
                  ) : null}
                  {notice.action ? (
                    <div className="inline-notification__actions">
                      {/* Ghost, as in a notification: the action must not
                          outweigh the message. */}
                      <Button
                        variant="ghost"
                        onPress={() => {
                          notice.action?.onAction();
                          dismissNotice(notice.id);
                        }}
                      >
                        {notice.action.label}
                      </Button>
                    </div>
                  ) : null}
                </div>
                {notice.dismissible ? (
                  <span className="inline-notification__close">
                    <Button
                      variant="ghost"
                      iconOnly
                      ariaLabel={closeLabel}
                      onPress={() => dismissNotice(notice.id)}
                    >
                      <Icon size="100%">
                        <CloseGlyph />
                      </Icon>
                    </Button>
                  </span>
                ) : null}
              </div>
            </div>
          );
        })}
      </div>
      <div className="dialog-status__live" role="status" aria-atomic="true">
        {announcement.map((line, index) => (
          <Fragment key={index}>
            <p>{line}</p>{" "}
          </Fragment>
        ))}
      </div>
    </>
  );
}
