// packages/react/src/link/Link.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from "react";

export type LinkVariant = "primary" | "subtle";

export interface LinkProps extends Omit<
  ComponentPropsWithoutRef<"a">,
  "href" | "children" | "className"
> {
  /** Destination URL, used as given. */
  href: string;
  /** Open in a new tab: adds `target` and a safe `rel`, and a trailing arrow. */
  external?: boolean;
  /** `subtle` takes the surrounding text colour (still underlined on hover). */
  variant?: LinkVariant;
  /** The link text. */
  children?: ReactNode;
}

const EXTERNAL_GLYPH = (
  <svg
    className="link__external"
    viewBox="0 0 24 24"
    width="0.85em"
    height="0.85em"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
    focusable="false"
  >
    <path d="M7 17 17 7" />
    <path d="M8 7h9v9" />
  </svg>
);

/**
 * Link: an inline text link in a semantic `<a>`, underlined, with a clear
 * hover and focus treatment. `external` opens it in a new tab, adds a safe
 * `rel` and marks it with a decorative arrow.
 *
 * `href` is required: a link navigates. An anchor without a destination takes
 * no focus and has no link semantics, so an in-page action belongs to Button.
 * Every other anchor attribute reaches the `<a>`, `onClick` included, for the
 * work that goes with a navigation, such as analytics.
 *
 * Themeable via `--ds-link-*`.
 */
export const Link = /* @__PURE__ */ forwardRef<HTMLAnchorElement, LinkProps>(function Link(
  { href, external = false, variant = "primary", children, ...rest },
  ref,
) {
  // A new tab always gets a safe `rel`, also when the target comes in as a
  // plain attribute; both are set after the spread so nothing overrides them.
  const target = external ? "_blank" : rest.target;
  const rel =
    target === "_blank" ? [rest.rel, "noopener noreferrer"].filter(Boolean).join(" ") : rest.rel;
  return (
    <a
      {...rest}
      ref={ref}
      className="link"
      data-variant={variant}
      href={href}
      target={target}
      rel={rel}
    >
      {children}
      {external ? EXTERNAL_GLYPH : null}
    </a>
  );
});

// packages/svelte/src/lib/link/Link.svelte
<script lang="ts">
  /**
   * Link — a styled inline text link rendered with a semantic `<a>`.
   *
   * Violet and underlined by default (the brand selection colour), with a clear
   * hover/focus treatment. Set `external` for links that open in a new tab — it
   * adds `target="_blank"` + safe `rel`, and an arrow icon marks it visually.
   *
   * `href` is required: a link navigates. An anchor without a destination is not
   * focusable and carries no link semantics, so an in-page action belongs to
   * Button. Every other anchor attribute, `onclick` included, reaches the `<a>`,
   * for the work that accompanies a navigation, such as analytics.
   *
   * Presentational only — themeable via `--ds-link-*`.
   */
  import type { Snippet } from "svelte";
  import type { HTMLAnchorAttributes } from "svelte/elements";

  interface Props extends Omit<HTMLAnchorAttributes, "href" | "children"> {
    /** Destination URL. */
    href: string;
    /** Open in a new tab (adds target/rel and a trailing arrow icon). */
    external?: boolean;
    /** Tone down to the surrounding text colour (still underlined on hover). */
    variant?: "primary" | "subtle";
    /** The link text. */
    children?: Snippet;
  }

  let { href, external = false, variant = "primary", children, ...rest }: Props = $props();

  // A new tab always gets a safe `rel`, also when the target comes in as a
  // plain attribute; it is applied after the spread so nothing overrides it.
  const target = $derived(external ? "_blank" : (rest.target ?? undefined));
  const rel = $derived(
    target === "_blank"
      ? [rest.rel, "noopener noreferrer"].filter(Boolean).join(" ")
      : (rest.rel ?? undefined),
  );
</script>

<a class="link" data-variant={variant} {href} {...rest} {target} {rel}>
  {@render children?.()}
  {#if external}
    <svg
      class="link__external"
      viewBox="0 0 24 24"
      width="0.85em"
      height="0.85em"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M7 17 17 7" />
      <path d="M8 7h9v9" />
    </svg>
  {/if}
</a>

<style>
  .link {
    color: var(--ds-link-color, var(--ds-color-secondary-body-text, #7a52cc));
    text-decoration: underline;
    text-decoration-thickness: var(--ds-link-underline, 1px);
    text-underline-offset: 0.15em;
    border-radius: 0.15em;
    cursor: pointer;
    transition:
      color 120ms ease,
      text-decoration-color 120ms ease;
  }
  .link[data-variant="subtle"] {
    color: inherit;
    text-decoration-color: var(--ds-color-border, #c7c1b7);
  }
  .link:hover {
    color: var(--ds-link-hover, var(--ds-color-secondary-hover, #6840b7));
    text-decoration-color: currentColor;
  }
  .link:focus-visible {
    outline: none;
    box-shadow: var(--ds-focus-ring-shadow, 0 0 0 2px var(--ds-color-focus-ring, #8e6cd4));
  }
  .link__external {
    display: inline-block;
    margin-inline-start: 0.15em;
    vertical-align: baseline;
  }
</style>
